//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGKVOHandle, UIImageView, UILabel;

@interface IGActiveLocationDetailView : UIView
{
    UILabel *_textLabel;
    UILabel *_detailTextLabel;
    UIImageView *_imageView;
    IGKVOHandle *_textLabelObserver;
    IGKVOHandle *_detailTextLabelObserver;
}

@property(retain, nonatomic) IGKVOHandle *detailTextLabelObserver; // @synthesize detailTextLabelObserver=_detailTextLabelObserver;
@property(retain, nonatomic) IGKVOHandle *textLabelObserver; // @synthesize textLabelObserver=_textLabelObserver;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *detailTextLabel; // @synthesize detailTextLabel=_detailTextLabel;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)dealloc;

@end

