//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGUserCell.h"

@class UIImageView, UILabel;

@interface IGDiscoverMorePeopleUserCell : IGUserCell
{
    int _sourceType;
    UIImageView *_sourceTypeImageView;
    UILabel *_userDefailtInfoLabel;
}

+ (float)defaultCellHeight;
@property(retain, nonatomic) UILabel *userDefailtInfoLabel; // @synthesize userDefailtInfoLabel=_userDefailtInfoLabel;
@property(retain, nonatomic) UIImageView *sourceTypeImageView; // @synthesize sourceTypeImageView=_sourceTypeImageView;
@property(nonatomic) int sourceType; // @synthesize sourceType=_sourceType;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)configureCellWithUserInfo:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1 analyticsDelegate:(id)arg2;
- (id)initWithReuseIdentifier:(id)arg1;

@end

