//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "IGFilterTintColorPickerDelegate.h"
#import "UITabBarDelegate.h"

@class IGFilterTintColorPicker, IGSloppyTouchSlider, NSString, UILabel, UITabBar, UITabBarItem, UIView;

@interface IGFilterTintControl : UIControl <UITabBarDelegate, IGFilterTintColorPickerDelegate>
{
    BOOL _hasAdjustHintShown;
    id <IGFilterTintControlDelegate> _delegate;
    unsigned int _currentState;
    UITabBar *_tintTypeTabBar;
    UITabBarItem *_shadowTab;
    UITabBarItem *_highlightTab;
    UIView *_lineSeparator;
    IGFilterTintColorPicker *_colorPicker;
    IGSloppyTouchSlider *_controlSlider;
    UILabel *_valueLabel;
    UILabel *_adjustHintLabel;
    unsigned int _tintShadowsColorIndex;
    unsigned int _tintHighlightsColorIndex;
    float _tintShadowsIntensity;
    float _tintHighlighsIntensity;
}

@property(nonatomic) float tintHighlighsIntensity; // @synthesize tintHighlighsIntensity=_tintHighlighsIntensity;
@property(nonatomic) float tintShadowsIntensity; // @synthesize tintShadowsIntensity=_tintShadowsIntensity;
@property(nonatomic) unsigned int tintHighlightsColorIndex; // @synthesize tintHighlightsColorIndex=_tintHighlightsColorIndex;
@property(nonatomic) unsigned int tintShadowsColorIndex; // @synthesize tintShadowsColorIndex=_tintShadowsColorIndex;
@property(nonatomic) BOOL hasAdjustHintShown; // @synthesize hasAdjustHintShown=_hasAdjustHintShown;
@property(retain, nonatomic) UILabel *adjustHintLabel; // @synthesize adjustHintLabel=_adjustHintLabel;
@property(retain, nonatomic) UILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(retain, nonatomic) IGSloppyTouchSlider *controlSlider; // @synthesize controlSlider=_controlSlider;
@property(retain, nonatomic) IGFilterTintColorPicker *colorPicker; // @synthesize colorPicker=_colorPicker;
@property(retain, nonatomic) UIView *lineSeparator; // @synthesize lineSeparator=_lineSeparator;
@property(retain, nonatomic) UITabBarItem *highlightTab; // @synthesize highlightTab=_highlightTab;
@property(retain, nonatomic) UITabBarItem *shadowTab; // @synthesize shadowTab=_shadowTab;
@property(retain, nonatomic) UITabBar *tintTypeTabBar; // @synthesize tintTypeTabBar=_tintTypeTabBar;
@property(nonatomic) unsigned int currentState; // @synthesize currentState=_currentState;
@property(nonatomic) __weak id <IGFilterTintControlDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)isAnyColorSelected;
- (void)setValuesForTintShadowsColor:(unsigned int)arg1 tintHighlightsColor:(unsigned int)arg2 tintShadowsIntensity:(float)arg3 tintHighlightsIntensity:(float)arg4;
@property(nonatomic) float priorValue;
@property(nonatomic) BOOL isTintTypeShadow;
@property(nonatomic) float value;
- (void)setValue:(float)arg1 animated:(BOOL)arg2;
- (void)onSliderChange:(id)arg1;
- (void)colorPickerShouldPresentIntensitySlider:(id)arg1;
- (void)colorPicker:(id)arg1 didChangeColorFrom:(unsigned int)arg2 to:(unsigned int)arg3;
- (void)tabBar:(id)arg1 didSelectItem:(id)arg2;
- (void)cancelIntensityAdjust;
- (void)applyIntensityAdjust;
- (void)showAdjustHintLabel;
- (struct CGRect)labelRect;
- (void)updateValueLabel;
- (void)hideSliderShowPicker;
- (void)hidePickerShowSlider;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

