//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGGenericMegaphoneView, NSURL;

@protocol IGGenericMegaphoneViewDelegate <NSObject>
- (void)megaphoneDidDismiss:(IGGenericMegaphoneView *)arg1;
- (void)megaphone:(IGGenericMegaphoneView *)arg1 didOpenURL:(NSURL *)arg2;
@end

