//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGLocationDataSource;

@protocol IGLocationDataSourceDelegate
- (void)locationDataSourceWasDeniedAccess;
- (void)locationDataSourceDidFailToLocate;
- (void)locationDataSourceDidFailLoading;
- (void)locationDataSourceDidFinishLoadingDataSource:(IGLocationDataSource *)arg1;
- (void)locationDataSourceDidStartLoading;
@end

