//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "IGNavigationAnimatorDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class IGAnalyticsMetadata, IGHorizontalPanGestureRecognizer, IGNavigationBar, IGNavigationPopAnimator, IGNavigationPushAnimator, IGScrollingHeaderCoordinator, NSString, UIView, UIViewController;

@interface IGNavigationController : UINavigationController <UIGestureRecognizerDelegate, UINavigationControllerDelegate, IGNavigationAnimatorDelegate>
{
    BOOL _transitioning;
    id <IGNavigationControllerDelegate> _navigationDelegate;
    IGAnalyticsMetadata *_analyticsMetadata;
    IGScrollingHeaderCoordinator *_scrollingHeaderCoordinator;
    IGHorizontalPanGestureRecognizer *_panGesture;
    IGNavigationPopAnimator *_navigationPopAnimator;
    IGNavigationPushAnimator *_navigationPushAnimator;
    UIViewController *_poppingViewController;
    UIView *_navigationBarUnderlay;
    struct CGPoint _initialTranslation;
}

@property(retain, nonatomic) UIView *navigationBarUnderlay; // @synthesize navigationBarUnderlay=_navigationBarUnderlay;
@property(nonatomic) struct CGPoint initialTranslation; // @synthesize initialTranslation=_initialTranslation;
@property(nonatomic) __weak UIViewController *poppingViewController; // @synthesize poppingViewController=_poppingViewController;
@property(retain, nonatomic) IGNavigationPushAnimator *navigationPushAnimator; // @synthesize navigationPushAnimator=_navigationPushAnimator;
@property(retain, nonatomic) IGNavigationPopAnimator *navigationPopAnimator; // @synthesize navigationPopAnimator=_navigationPopAnimator;
@property(retain, nonatomic) IGHorizontalPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(readonly, nonatomic) IGScrollingHeaderCoordinator *scrollingHeaderCoordinator; // @synthesize scrollingHeaderCoordinator=_scrollingHeaderCoordinator;
@property(readonly, nonatomic) IGAnalyticsMetadata *analyticsMetadata; // @synthesize analyticsMetadata=_analyticsMetadata;
@property(nonatomic, getter=isTransitioning) BOOL transitioning; // @synthesize transitioning=_transitioning;
@property(nonatomic) __weak id <IGNavigationControllerDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
- (void).cxx_destruct;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (id)navigationController:(id)arg1 animationControllerForOperation:(int)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)updateTabBarVisibilityForViewController:(id)arg1 animated:(BOOL)arg2;
- (void)handlePanGesture:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (id)childViewControllerForStatusBarHidden;
- (id)childViewControllerForStatusBarStyle;
- (int)preferredStatusBarStyle;
- (int)preferredStatusBarUpdateAnimation;
- (void)setNeedsNavigationBarAppearenceUpdateAnimated:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (BOOL)shouldAutorotate;
- (id)popToMainViewController:(BOOL)arg1;
- (id)popToRootViewControllerAnimated:(BOOL)arg1;
- (id)popToViewController:(id)arg1 animated:(BOOL)arg2;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)updateForVisibleChange;
- (id)ig_tabBarController;
@property(readonly, nonatomic) double transitionDuration;
- (void)navigationAnimatorDidFinishTransition:(id)arg1;
- (void)navigationAnimatorWillAnimateTransition:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (id)initWithRootViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) IGNavigationBar *navigationBar; // @dynamic navigationBar;
@property(readonly) Class superclass;

@end

