//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGSimpleButton;

@interface IGNewsEmptyFeedView : UIView
{
    IGSimpleButton *_followButton;
}

@property(retain, nonatomic) IGSimpleButton *followButton; // @synthesize followButton=_followButton;
- (void).cxx_destruct;
- (id)noStoriesTextViewHeader:(id)arg1 body:(id)arg2 cacheKey:(id)arg3;
- (id)heartView;
- (void)setFollowButtonTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithHeader:(id)arg1 body:(id)arg2 cacheKey:(id)arg3 showFollowButton:(BOOL)arg4;

@end

