//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@interface IGOverlayNuxController : NSObject
{
    id <IGOverlayNuxControllerDelegate> _delegate;
    UIView *_NUXView;
}

@property(retain, nonatomic) UIView *NUXView; // @synthesize NUXView=_NUXView;
@property(nonatomic) __weak id <IGOverlayNuxControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showOverlayNux:(struct CGRect)arg1 highlightedElement:(id)arg2 withParent:(id)arg3 withHeader:(id)arg4 withBody:(id)arg5;
- (void)hideNUX;
- (id)initWithDelegate:(id)arg1;

@end

