//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface IGPivotMediaInfo : NSObject
{
    NSArray *_creators;
    NSArray *_pivots;
}

@property(retain, nonatomic) NSArray *pivots; // @synthesize pivots=_pivots;
@property(retain, nonatomic) NSArray *creators; // @synthesize creators=_creators;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

