//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface IGQEExperimentUserGroup : NSObject
{
    BOOL _useDeviceId;
    NSString *_name;
    NSDictionary *_parameters;
}

@property(readonly, nonatomic) BOOL useDeviceId; // @synthesize useDeviceId=_useDeviceId;
@property(readonly, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (id)initWithName:(id)arg1 parameters:(id)arg2 useDeviceId:(BOOL)arg3;
- (id)initWithName:(id)arg1 parameters:(id)arg2;

@end

