//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGSequence, NSString, NSURL;

@interface IGRealtimeSubscription : NSObject
{
    id <IGRealtimeSubscriptionDelegate> _delegate;
    NSString *_topic;
    NSURL *_url;
    IGSequence *_sequence;
    NSString *_authToken;
    unsigned int _status;
}

@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(readonly, copy, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;
@property(readonly, copy, nonatomic) IGSequence *sequence; // @synthesize sequence=_sequence;
@property(readonly, copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, copy, nonatomic) NSString *topic; // @synthesize topic=_topic;
@property(nonatomic) __weak id <IGRealtimeSubscriptionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateStatus:(unsigned int)arg1;
- (void)updateSequence:(id)arg1;
- (void)updateWithSubscription:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

