//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIScrollView, UIViewController;

@interface IGScrollingHeaderItem : NSObject
{
    BOOL _shouldScrollAwayNavigationBar;
    BOOL _shouldScrollAwayStatusBar;
    BOOL _headerIsScrolledAway;
    UIScrollView *_scrollView;
    NSArray *_additionalScrollingViews;
    float _headerHeight;
    UIViewController *_viewController;
}

@property(readonly, nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) BOOL headerIsScrolledAway; // @synthesize headerIsScrolledAway=_headerIsScrolledAway;
@property(nonatomic) float headerHeight; // @synthesize headerHeight=_headerHeight;
@property(readonly, nonatomic) NSArray *additionalScrollingViews; // @synthesize additionalScrollingViews=_additionalScrollingViews;
@property(readonly, nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) BOOL shouldScrollAwayStatusBar; // @synthesize shouldScrollAwayStatusBar=_shouldScrollAwayStatusBar;
@property(readonly, nonatomic) BOOL shouldScrollAwayNavigationBar; // @synthesize shouldScrollAwayNavigationBar=_shouldScrollAwayNavigationBar;
- (void).cxx_destruct;
- (id)description;
- (void)setScrollView:(id)arg1 additionalScrollingViews:(id)arg2 headerHeight:(float)arg3;
- (id)initWithViewController:(id)arg1 shouldScrollAwayNavigationBar:(BOOL)arg2 shouldScrollAwayStatusBar:(BOOL)arg3;
- (float)maximumHeaderOffset;
- (void)setScrollView:(id)arg1 additionalScrollingViews:(id)arg2;

@end

