//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGSearchResultsSectionController, NSIndexPath, UITableView, UITableViewCell, UIViewController;

@protocol IGSearchResultsItemController <NSObject>
- (UIViewController *)tableView:(UITableView *)arg1 viewControllerForItem:(id)arg2 atIndexPath:(NSIndexPath *)arg3;
- (UITableViewCell *)tableView:(UITableView *)arg1 cellForItem:(id)arg2 atIndexPath:(NSIndexPath *)arg3;
- (BOOL)canHandleItem:(id)arg1;

@optional
- (void)sectionController:(IGSearchResultsSectionController *)arg1 tableView:(UITableView *)arg2 didSelectItem:(id)arg3 atIndexPath:(NSIndexPath *)arg4;
@end

