//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGGroupedTableViewCell, IGServiceLoginTableViewController, NSIndexPath, NSString;

@protocol IGServiceHelperLoginProtocol <NSObject>
- (void)prepareCell:(IGGroupedTableViewCell *)arg1 forIndexPath:(NSIndexPath *)arg2;
- (NSString *)loginFooterMessage;
- (NSString *)loginErrorMessage;
- (int)numberOfExtraRowsForLogin;
- (IGServiceLoginTableViewController *)loginViewControllerWithDelegate:(id)arg1;
- (void)doAuthWithUsername:(NSString *)arg1 password:(NSString *)arg2;
- (void)setLoginPending:(BOOL)arg1;
- (BOOL)loginPending;
@end

