//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGPlainTableViewController.h"

@class NSArray, NSString, UILabel, UIView;

@interface IGSuggestedUsernamesViewController : IGPlainTableViewController
{
    id <IGSuggestedUsernamesViewControllerDelegate> _delegate;
    NSArray *_suggestions;
    NSString *_attemptedUsername;
    UIView *_tableHeader;
    UILabel *_infoLabel;
}

@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UIView *tableHeader; // @synthesize tableHeader=_tableHeader;
@property(copy, nonatomic) NSString *attemptedUsername; // @synthesize attemptedUsername=_attemptedUsername;
@property(copy, nonatomic) NSArray *suggestions; // @synthesize suggestions=_suggestions;
@property(nonatomic) __weak id <IGSuggestedUsernamesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onCancel;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)attributedHeaderText;
- (id)initWithSuggestions:(id)arg1 andAttemptedUsername:(id)arg2;

@end

