//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADJLogger.h"

@interface ADJLogger : NSObject <ADJLogger>
{
    int _loglevel;
}

+ (int)LogLevelFromString:(id)arg1;
@property(nonatomic) int loglevel; // @synthesize loglevel=_loglevel;
- (void)logLevel:(id)arg1 format:(id)arg2 parameters:(void *)arg3;
- (void)assert:(id)arg1;
- (void)error:(id)arg1;
- (void)warn:(id)arg1;
- (void)info:(id)arg1;
- (void)debug:(id)arg1;
- (void)verbose:(id)arg1;
- (void)setLogLevel:(int)arg1;

@end

