//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ASRangeHandler.h"

@class NSString;

@interface ASRangeHandlerRender : NSObject <ASRangeHandler>
{
}

+ (id)workingWindow;
- (void)node:(id)arg1 exitedRangeOfType:(int)arg2;
- (void)node:(id)arg1 enteredRangeOfType:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

