//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSURLSessionDelegate.h"

@class NSArray, NSString, NSURL, NSURLSession;

@interface BTHTTP : NSObject <NSURLSessionDelegate, NSCopying>
{
    NSArray *_pinnedCertificates;
    NSURLSession *_session;
    NSURL *_baseURL;
}

+ (id)defaultDomainErrorForStatusCode:(int)arg1 error:(id)arg2;
+ (id)domainRequestErrorForError:(id)arg1;
+ (void)callCompletionBlock:(CDUnknownBlockType)arg1 response:(id)arg2 error:(id)arg3;
+ (void)handleRequestCompletion:(id)arg1 response:(id)arg2 error:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSArray *pinnedCertificates; // @synthesize pinnedCertificates=_pinnedCertificates;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToHTTP:(id)arg1;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)pinnedCertificateData;
- (id)acceptLanguageString;
- (id)acceptString;
- (id)architectureString;
- (id)platformString;
- (id)userAgentString;
- (id)defaultHeaders;
- (void)httpRequest:(id)arg1 path:(id)arg2 parameters:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)DELETE:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)DELETE:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)PUT:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)PUT:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)POST:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)POST:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)GET:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)GET:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setProtocolClasses:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithBaseURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

