//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BTPaymentMethod, NSError, UIViewController;

@protocol BTPaymentMethodCreationDelegate <NSObject>
- (void)paymentMethodCreator:(id)arg1 didFailWithError:(NSError *)arg2;
- (void)paymentMethodCreator:(id)arg1 didCreatePaymentMethod:(BTPaymentMethod *)arg2;
- (void)paymentMethodCreatorDidCancel:(id)arg1;
- (void)paymentMethodCreatorWillProcess:(id)arg1;
- (void)paymentMethodCreatorWillPerformAppSwitch:(id)arg1;
- (void)paymentMethodCreator:(id)arg1 requestsDismissalOfViewController:(UIViewController *)arg2;
- (void)paymentMethodCreator:(id)arg1 requestsPresentationOfViewController:(UIViewController *)arg2;
@end

