//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTUIThemedView.h"

#import "BTUIFormFieldDelegate.h"

@class BTUICardCvvField, BTUICardExpiryField, BTUICardNumberField, BTUICardPostalCodeField, NSArray, NSString;

@interface BTUICardFormView : BTUIThemedView <BTUIFormFieldDelegate>
{
    BOOL _alphaNumericPostalCode;
    BOOL _vibrate;
    id <BTUICardFormViewDelegate> _delegate;
    unsigned int _optionalFields;
    BTUICardNumberField *_numberField;
    BTUICardExpiryField *_expiryField;
    BTUICardCvvField *_cvvField;
    BTUICardPostalCodeField *_postalCodeField;
    NSArray *_fields;
    NSArray *_dynamicConstraints;
}

@property(retain, nonatomic) NSArray *dynamicConstraints; // @synthesize dynamicConstraints=_dynamicConstraints;
@property(retain, nonatomic) NSArray *fields; // @synthesize fields=_fields;
@property(retain, nonatomic) BTUICardPostalCodeField *postalCodeField; // @synthesize postalCodeField=_postalCodeField;
@property(retain, nonatomic) BTUICardCvvField *cvvField; // @synthesize cvvField=_cvvField;
@property(retain, nonatomic) BTUICardExpiryField *expiryField; // @synthesize expiryField=_expiryField;
@property(retain, nonatomic) BTUICardNumberField *numberField; // @synthesize numberField=_numberField;
@property(nonatomic) BOOL vibrate; // @synthesize vibrate=_vibrate;
@property(nonatomic) unsigned int optionalFields; // @synthesize optionalFields=_optionalFields;
@property(nonatomic) BOOL alphaNumericPostalCode; // @synthesize alphaNumericPostalCode=_alphaNumericPostalCode;
@property(nonatomic) __weak id <BTUICardFormViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)switchToPreviousField:(id)arg1;
- (void)advanceToNextInvalidFieldFrom:(id)arg1;
- (BOOL)formFieldShouldReturn:(id)arg1;
- (void)formFieldDidDeleteWhileEmpty:(id)arg1;
- (void)formFieldDidChange:(id)arg1;
@property(readonly, copy, nonatomic) NSString *postalCode;
@property(readonly, copy, nonatomic) NSString *cvv;
@property(readonly, copy, nonatomic) NSString *expirationYear;
@property(readonly, copy, nonatomic) NSString *expirationMonth;
@property(readonly, copy, nonatomic) NSString *number;
@property(readonly, nonatomic) BOOL valid;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateConstraints;
- (void)setup;
- (void)showTopLevelError:(id)arg1;
- (void)showErrorForField:(unsigned int)arg1;
- (struct CGSize)intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

