//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "ASDisplayNodeAsyncTransactionContainer.h"

@class _ASAsyncTransaction;

@interface CALayer (ASDisplayNodeAsyncTransactionContainer) <ASDisplayNodeAsyncTransactionContainer>
@property(readonly, retain, nonatomic) CALayer *asyncdisplaykit_parentTransactionContainer;
@property(readonly, retain, nonatomic) _ASAsyncTransaction *asyncdisplaykit_asyncTransaction;
- (void)asyncdisplaykit_asyncTransactionContainerStateDidChange;
- (void)asyncdisplaykit_cancelAsyncTransactions;
@property(readonly, nonatomic) unsigned int asyncdisplaykit_asyncTransactionContainerState;

// Remaining properties
@property(nonatomic, getter=asyncdisplaykit_isAsyncTransactionContainer, setter=asyncdisplaykit_setAsyncTransactionContainer:) BOOL asyncdisplaykit_asyncTransactionContainer; // @dynamic asyncdisplaykit_asyncTransactionContainer;
@end

