//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class ALAsset, CBLZoomingImageView, UIImageView;

@interface CBLALAssetCollectionViewCell : UICollectionViewCell
{
    BOOL _zoomEnabled;
    ALAsset *_asset;
    UIImageView *_imageView;
    CBLZoomingImageView *_zoomingImageView;
}

@property(nonatomic, getter=isZoomEnabled) BOOL zoomEnabled; // @synthesize zoomEnabled=_zoomEnabled;
@property(retain, nonatomic) CBLZoomingImageView *zoomingImageView; // @synthesize zoomingImageView=_zoomingImageView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) ALAsset *asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

