//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBLBrickLayout, NSIndexPath, NSMutableArray, NSMutableDictionary, NSObject<CBLBrickLayoutDelegate>;

@interface CBLBrickLayoutSection : NSObject
{
    BOOL _alwaysShowSectionHeaders;
    NSObject<CBLBrickLayoutDelegate> *_delegate;
    unsigned int _sectionIndex;
    CBLBrickLayout *_brickLayout;
    unsigned int _numberOfColumns;
    NSMutableArray *_blockSizes;
    NSMutableArray *_indexPaths;
    NSMutableDictionary *_gridBlocks;
    NSIndexPath *_lastPlacedIndexPath;
    unsigned int _maxRows;
    NSMutableArray *_rowsToRevisit;
    NSMutableDictionary *_indexPathToRow;
    NSMutableDictionary *_indexPathToColumn;
    float _furthestBlockPoint;
    NSIndexPath *_lastIndexPathPlaced;
    struct CGPoint _lastBlockPoint;
    struct CGSize _brickSize;
    struct CGRect _sectionHeaderFrame;
}

@property(nonatomic) struct CGRect sectionHeaderFrame; // @synthesize sectionHeaderFrame=_sectionHeaderFrame;
@property(nonatomic) struct CGSize brickSize; // @synthesize brickSize=_brickSize;
@property(nonatomic) struct CGPoint lastBlockPoint; // @synthesize lastBlockPoint=_lastBlockPoint;
@property(retain, nonatomic) NSIndexPath *lastIndexPathPlaced; // @synthesize lastIndexPathPlaced=_lastIndexPathPlaced;
@property(nonatomic) float furthestBlockPoint; // @synthesize furthestBlockPoint=_furthestBlockPoint;
@property(retain, nonatomic) NSMutableDictionary *indexPathToColumn; // @synthesize indexPathToColumn=_indexPathToColumn;
@property(retain, nonatomic) NSMutableDictionary *indexPathToRow; // @synthesize indexPathToRow=_indexPathToRow;
@property(retain, nonatomic) NSMutableArray *rowsToRevisit; // @synthesize rowsToRevisit=_rowsToRevisit;
@property(nonatomic) unsigned int maxRows; // @synthesize maxRows=_maxRows;
@property(retain, nonatomic) NSIndexPath *lastPlacedIndexPath; // @synthesize lastPlacedIndexPath=_lastPlacedIndexPath;
@property(retain, nonatomic) NSMutableDictionary *gridBlocks; // @synthesize gridBlocks=_gridBlocks;
@property(retain, nonatomic) NSMutableArray *indexPaths; // @synthesize indexPaths=_indexPaths;
@property(retain, nonatomic) NSMutableArray *blockSizes; // @synthesize blockSizes=_blockSizes;
@property(nonatomic) unsigned int numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(retain, nonatomic) CBLBrickLayout *brickLayout; // @synthesize brickLayout=_brickLayout;
@property(nonatomic) unsigned int sectionIndex; // @synthesize sectionIndex=_sectionIndex;
@property(nonatomic) BOOL alwaysShowSectionHeaders; // @synthesize alwaysShowSectionHeaders=_alwaysShowSectionHeaders;
@property(nonatomic) __weak NSObject<CBLBrickLayoutDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (float)sectionHeight;
- (struct CGPoint)findNextBestStartingPointFromPoint:(struct CGPoint)arg1;
- (BOOL)traverseOpenAreaForPoint:(struct CGPoint)arg1 size:(struct CGSize)arg2;
- (void)fillBlocks;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;
- (void)invalidateLayout;
- (id)initWithLayout:(id)arg1 sectionIndex:(unsigned int)arg2;

@end

