//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLBaseViewController.h"

#import "CBLPresentedViewControllerDelegate.h"
#import "TTTAttributedLabelDelegate.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"

@class CBLPartnerType, CBLSignupManager, CBLSignupTextField, CBLSignupView, NSMutableArray, NSString, TTTAttributedLabel, UIButton;

@interface CBLBusinessSignupViewController : CBLBaseViewController <UITextFieldDelegate, UIPickerViewDataSource, UIPickerViewDelegate, TTTAttributedLabelDelegate, CBLPresentedViewControllerDelegate>
{
    UIButton *_createButton;
    CBLSignupTextField *_emailAddressField;
    CBLSignupTextField *_passwordField;
    CBLSignupTextField *_businessNameField;
    CBLSignupTextField *_businessTypeField;
    CBLSignupTextField *_websiteField;
    NSMutableArray *_businessTypes;
    TTTAttributedLabel *_privacyLabel;
    CBLSignupView *_signupView;
    CBLPartnerType *_selectedPartnerType;
    CBLSignupManager *_signupManager;
}

@property(retain, nonatomic) CBLSignupManager *signupManager; // @synthesize signupManager=_signupManager;
@property(retain, nonatomic) CBLPartnerType *selectedPartnerType; // @synthesize selectedPartnerType=_selectedPartnerType;
@property(retain, nonatomic) CBLSignupView *signupView; // @synthesize signupView=_signupView;
@property(retain, nonatomic) TTTAttributedLabel *privacyLabel; // @synthesize privacyLabel=_privacyLabel;
@property(retain, nonatomic) NSMutableArray *businessTypes; // @synthesize businessTypes=_businessTypes;
@property(retain, nonatomic) CBLSignupTextField *websiteField; // @synthesize websiteField=_websiteField;
@property(retain, nonatomic) CBLSignupTextField *businessTypeField; // @synthesize businessTypeField=_businessTypeField;
@property(retain, nonatomic) CBLSignupTextField *businessNameField; // @synthesize businessNameField=_businessNameField;
@property(retain, nonatomic) CBLSignupTextField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic) CBLSignupTextField *emailAddressField; // @synthesize emailAddressField=_emailAddressField;
@property(retain, nonatomic) UIButton *createButton; // @synthesize createButton=_createButton;
- (void).cxx_destruct;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)presentedViewControllerShouldBeDismissed:(id)arg1;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (id)pickerView:(id)arg1 titleForRow:(int)arg2 forComponent:(int)arg3;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (void)cblTraitCollectionDidChange:(id)arg1;
- (id)localLayoutAttributes;
- (void)cblViewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (id)barTintColor;
- (id)signupTextFieldWithPlaceholderName:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)didTapCreate:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSignupView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

