//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLTraitCollectionView.h"

@class CBLBoardCell, CBLConversationMessageCellLayoutAttributes, CBLPinCellContentView, CBLPinnerCell, CBLRemoteModelObject, CBLUser, UIImageView, UIView;

@interface CBLConversationMessageObjectView : CBLTraitCollectionView
{
    BOOL _isSenderActiveUser;
    CBLRemoteModelObject *_object;
    CBLUser *_sender;
    id <CBLConversationMessageObjectViewDelegate> _delegate;
    UIImageView *_userImageView;
    UIImageView *_objectCaret;
    UIView *_objectContainer;
    float _cellObjectWidth;
    CBLPinCellContentView *_pinView;
    CBLBoardCell *_boardView;
    CBLPinnerCell *_pinnerView;
    CBLConversationMessageCellLayoutAttributes *_messageCellLayoutAttributes;
}

+ (float)objectHeightForObject:(id)arg1 withWidth:(float)arg2 cropped:(BOOL)arg3;
+ (struct CGSize)objectBubbleSizeForObject:(id)arg1 withCellWidth:(float)arg2 senderIsActiveUser:(BOOL)arg3;
+ (float)totalHeightForObjectViewWithObject:(id)arg1 cellWidth:(float)arg2 senderIsActiveUser:(BOOL)arg3;
@property(retain, nonatomic) CBLConversationMessageCellLayoutAttributes *messageCellLayoutAttributes; // @synthesize messageCellLayoutAttributes=_messageCellLayoutAttributes;
@property(retain, nonatomic) CBLPinnerCell *pinnerView; // @synthesize pinnerView=_pinnerView;
@property(retain, nonatomic) CBLBoardCell *boardView; // @synthesize boardView=_boardView;
@property(retain, nonatomic) CBLPinCellContentView *pinView; // @synthesize pinView=_pinView;
@property(nonatomic) float cellObjectWidth; // @synthesize cellObjectWidth=_cellObjectWidth;
@property(retain, nonatomic) UIView *objectContainer; // @synthesize objectContainer=_objectContainer;
@property(retain, nonatomic) UIImageView *objectCaret; // @synthesize objectCaret=_objectCaret;
@property(retain, nonatomic) UIImageView *userImageView; // @synthesize userImageView=_userImageView;
@property(nonatomic) __weak id <CBLConversationMessageObjectViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CBLUser *sender; // @synthesize sender=_sender;
@property(nonatomic) BOOL isSenderActiveUser; // @synthesize isSenderActiveUser=_isSenderActiveUser;
@property(retain, nonatomic) CBLRemoteModelObject *object; // @synthesize object=_object;
- (void).cxx_destruct;
- (void)objectWasLongPressed:(id)arg1;
- (void)objectWasTapped:(id)arg1;
- (void)userImageWasTapped:(id)arg1;
- (void)cblTraitCollectionDidChange:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

