//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLBaseViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UITableView;

@interface CBLDeactivateAccountViewController : CBLBaseViewController <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate>
{
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)deactivateComplete;
- (void)showPermanentlyCloseSuccessAlertView;
- (void)showDeactivateSuccessAlertView;
- (void)permanentlyCloseAccount;
- (void)deactivateAccount;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)showPermanentlyCloseAccountAlertView;
- (void)showDeactivateAccountAlertView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

