//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol CBLLoginView_Delegate <NSObject>

@optional
- (void)CBLLoginViewiCloudKeychainButtonPressed;
- (void)CBLLoginViewForgotPasswordButtonPressed;
- (void)CBLLoginViewSignInWithEmail:(NSString *)arg1 andPassword:(NSString *)arg2;
- (void)CBLLoginViewRakutenButtonPressed;
- (void)CBLLoginViewGPlusButtonPressed;
- (void)CBLLoginViewTwitterButtonPressed;
- (void)CBLLoginViewFacebookButtonPressed;
@end

