//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIPanGestureRecognizer;

@interface CBLModalSlidingView : UIView
{
    UIPanGestureRecognizer *_panRecognizer;
    UIView *_backgroundView;
    struct CGPoint _restPoint;
    struct CGPoint _velocity;
}

+ (id)slidingModalViewWithHeight:(float)arg1;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) struct CGPoint velocity; // @synthesize velocity=_velocity;
@property(retain, nonatomic) UIPanGestureRecognizer *panRecognizer; // @synthesize panRecognizer=_panRecognizer;
@property(nonatomic) struct CGPoint restPoint; // @synthesize restPoint=_restPoint;
- (void).cxx_destruct;
- (void)setRestPoint:(struct CGPoint)arg1 animated:(BOOL)arg2;
- (void)dismissAnimated:(BOOL)arg1;
- (void)showAnimated:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

