//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLExperienceData.h"

@class NSString, NSURL;

@interface CBLNagExperienceData : CBLExperienceData
{
}

- (int)completeAction;
@property(readonly, nonatomic) BOOL markCompleteOnAction;
@property(readonly, nonatomic) BOOL dismissOnAction;
@property(readonly, nonatomic) NSURL *imageURL;
@property(readonly, nonatomic) NSURL *rightButtonURL;
@property(readonly, nonatomic) NSURL *leftButtonURL;
@property(readonly, nonatomic) NSURL *centerButtonURL;
@property(readonly, nonatomic) NSString *rightButtonText;
@property(readonly, nonatomic) NSString *leftButtonText;
@property(readonly, nonatomic) NSString *centerButtonText;
@property(readonly, nonatomic) NSString *detailText;
@property(readonly, nonatomic) NSString *titleText;
@property(readonly, nonatomic) BOOL enableDismiss;
@property(readonly, nonatomic) int displayType;

@end

