//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLBaseLayoutAttributes.h"

@interface CBLNuxConnectStepLayoutAttributes : CBLBaseLayoutAttributes
{
    float _itemSpacing;
    struct UIEdgeInsets _edgeInsets;
}

@property(nonatomic) float itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
- (id)initWithTraitCollection:(id)arg1;

@end

