//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLModelObject.h"

@class CBLNotificationDateSection, CBLNotificationModelSection, CBLNotificationTemplateSection;

@interface CBLNotificationBalancedSections : CBLModelObject
{
    CBLNotificationModelSection *_leftObject;
    CBLNotificationTemplateSection *_messageBody;
    CBLNotificationModelSection *_rightObject;
    CBLNotificationDateSection *_caption;
}

+ (id)propertyAliases;
@property(readonly, nonatomic) CBLNotificationDateSection *caption; // @synthesize caption=_caption;
@property(readonly, nonatomic) CBLNotificationModelSection *rightObject; // @synthesize rightObject=_rightObject;
@property(readonly, nonatomic) CBLNotificationTemplateSection *messageBody; // @synthesize messageBody=_messageBody;
@property(readonly, nonatomic) CBLNotificationModelSection *leftObject; // @synthesize leftObject=_leftObject;
- (void).cxx_destruct;

@end

