//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CBLIndeterminateActivityIndicatorView, NSString, UIImageView, UILabel;

@interface CBLNuxConnectCollectionViewPlaceholder : UIView
{
    int _state;
    NSString *_loadingText;
    NSString *_noFriendsText;
    UIImageView *_defaultGridImageView;
    CBLIndeterminateActivityIndicatorView *_spinner;
    UILabel *_label;
}

@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) CBLIndeterminateActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UIImageView *defaultGridImageView; // @synthesize defaultGridImageView=_defaultGridImageView;
@property(copy, nonatomic) NSString *noFriendsText; // @synthesize noFriendsText=_noFriendsText;
@property(copy, nonatomic) NSString *loadingText; // @synthesize loadingText=_loadingText;
@property(nonatomic) int state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)updateBackgroundImageForOrientation:(int)arg1;
- (id)placeholderImageForOrientation:(int)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

