//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLCollectionViewController.h"

#import "CBLBuyPinVariantImagesViewControllerDelegate.h"
#import "CBLPinCloseupActionHeaderDelegate.h"
#import "CBLPinCloseupActionViewDelegate.h"
#import "CBLPinCloseupAttributionViewDelegate.h"
#import "CBLPinCloseupBuyableDescriptionViewDelegate.h"
#import "CBLPinCloseupBuyableFooterDelegate.h"
#import "CBLPinCloseupCountsViewDelegate.h"
#import "CBLPinCloseupDescriptionViewDelegate.h"
#import "CBLPinCloseupImageViewDelegate.h"
#import "CBLPinCloseupInlineImageCarouselViewDelegate.h"
#import "CBLPinCloseupLinkModuleViewDelegate.h"
#import "CBLPinCloseupMapViewDelegate.h"
#import "CBLPinCloseupShopMoreViewDelegate.h"
#import "CBLPinCloseupSourceViewDelegate.h"
#import "CBLShareObjectActivityViewDelegate.h"
#import "CBLSharePinViewControllerDelegate.h"
#import "CBLViewControllerPresenter.h"
#import "CBLZoomTransitionProtocol.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class CAGradientLayer, CBLCart, CBLFirstPinExperienceData, CBLPin, CBLPinCloseupActionHeaderView, CBLPinCloseupDataSource, CBLPinCloseupInlineImageCarouselView, CBLTutorialCardView, CBLUserGuidePulserView, MASConstraint, NSIndexPath, NSString, NSUserActivity, UIActionSheet, UIAlertController, UIView;

@interface CBLPinCloseupViewController : CBLCollectionViewController <UICollectionViewDataSource, UICollectionViewDelegate, CBLPinCloseupImageViewDelegate, CBLPinCloseupInlineImageCarouselViewDelegate, CBLPinCloseupDescriptionViewDelegate, CBLPinCloseupCountsViewDelegate, CBLPinCloseupAttributionViewDelegate, CBLPinCloseupLinkModuleViewDelegate, CBLPinCloseupMapViewDelegate, CBLPinCloseupActionViewDelegate, CBLPinCloseupShopMoreViewDelegate, CBLPinCloseupSourceViewDelegate, CBLPinCloseupBuyableFooterDelegate, CBLPinCloseupBuyableDescriptionViewDelegate, CBLBuyPinVariantImagesViewControllerDelegate, SKStoreProductViewControllerDelegate, CBLSharePinViewControllerDelegate, CBLShareObjectActivityViewDelegate, CBLPinCloseupActionHeaderDelegate, CBLViewControllerPresenter, CBLZoomTransitionProtocol>
{
    BOOL _checkingDomainSafety;
    BOOL _didDismissCloseup;
    BOOL _showSimplifiedCloseup;
    id <CBLPinCloseupNavigationDelegate> _navigationDelegate;
    CBLPinCloseupDataSource *_closeupDataSource;
    NSIndexPath *_originalSelectedIndexPath;
    CBLPin *_pin;
    float _closeupEndOffset;
    CBLPinCloseupInlineImageCarouselView *_pinCloseupImageView;
    CBLPinCloseupActionHeaderView *_actionHeaderView;
    CBLFirstPinExperienceData *_experienceData;
    CBLTutorialCardView *_firstPinTutorialCard;
    UIView *_relatedPinsHeader;
    UIActionSheet *_actionSheet;
    UIAlertController *_alertController;
    CAGradientLayer *_relatedPinsLayer;
    MASConstraint *_headerWidthConstraint;
    MASConstraint *_headerTopOffsetConstraint;
    MASConstraint *_collectionViewTopOffsetConstraint;
    CBLCart *_cart;
    NSUserActivity *_closeupActivity;
    int _closeupViewingState;
    CBLUserGuidePulserView *_pulserView;
}

+ (void)presentHost:(id)arg1 withPath:(id)arg2 withParameters:(id)arg3 usingPresenterDelegate:(id)arg4 deferingToControllerDelegate:(id)arg5;
@property(retain, nonatomic) CBLUserGuidePulserView *pulserView; // @synthesize pulserView=_pulserView;
@property(nonatomic) BOOL showSimplifiedCloseup; // @synthesize showSimplifiedCloseup=_showSimplifiedCloseup;
@property(nonatomic) int closeupViewingState; // @synthesize closeupViewingState=_closeupViewingState;
@property(retain, nonatomic) NSUserActivity *closeupActivity; // @synthesize closeupActivity=_closeupActivity;
@property(retain, nonatomic) CBLCart *cart; // @synthesize cart=_cart;
@property(retain, nonatomic) MASConstraint *collectionViewTopOffsetConstraint; // @synthesize collectionViewTopOffsetConstraint=_collectionViewTopOffsetConstraint;
@property(retain, nonatomic) MASConstraint *headerTopOffsetConstraint; // @synthesize headerTopOffsetConstraint=_headerTopOffsetConstraint;
@property(retain, nonatomic) MASConstraint *headerWidthConstraint; // @synthesize headerWidthConstraint=_headerWidthConstraint;
@property(retain, nonatomic) CAGradientLayer *relatedPinsLayer; // @synthesize relatedPinsLayer=_relatedPinsLayer;
@property(retain, nonatomic) UIAlertController *alertController; // @synthesize alertController=_alertController;
@property(retain, nonatomic) UIActionSheet *actionSheet; // @synthesize actionSheet=_actionSheet;
@property(nonatomic) BOOL didDismissCloseup; // @synthesize didDismissCloseup=_didDismissCloseup;
@property(retain, nonatomic) UIView *relatedPinsHeader; // @synthesize relatedPinsHeader=_relatedPinsHeader;
@property(retain, nonatomic) CBLTutorialCardView *firstPinTutorialCard; // @synthesize firstPinTutorialCard=_firstPinTutorialCard;
@property(retain, nonatomic) CBLFirstPinExperienceData *experienceData; // @synthesize experienceData=_experienceData;
@property(nonatomic, getter=isCheckingDomainSafety) BOOL checkingDomainSafety; // @synthesize checkingDomainSafety=_checkingDomainSafety;
@property(retain, nonatomic) CBLPinCloseupActionHeaderView *actionHeaderView; // @synthesize actionHeaderView=_actionHeaderView;
@property(retain, nonatomic) CBLPinCloseupInlineImageCarouselView *pinCloseupImageView; // @synthesize pinCloseupImageView=_pinCloseupImageView;
@property(nonatomic) float closeupEndOffset; // @synthesize closeupEndOffset=_closeupEndOffset;
@property(retain, nonatomic) CBLPin *pin; // @synthesize pin=_pin;
@property(retain, nonatomic) NSIndexPath *originalSelectedIndexPath; // @synthesize originalSelectedIndexPath=_originalSelectedIndexPath;
@property(retain, nonatomic) CBLPinCloseupDataSource *closeupDataSource; // @synthesize closeupDataSource=_closeupDataSource;
@property(nonatomic) __weak id <CBLPinCloseupNavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
- (void).cxx_destruct;
- (id)localLayoutAttributes;
- (void)cblViewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)CBLSharePinActivitiesViewDidTapFlag:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapCopyLink:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapSaveImage:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapOther:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapSMS:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapEmail:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapLine:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapFBMessenger:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapWhatsApp:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapTwitter:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapFacebook:(id)arg1;
- (void)CBLSharePinActivitiesViewDidTapClose:(id)arg1;
- (void)CBLSharePinViewControllerDidTapClose:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)updateHeaderSize;
- (void)productViewControllerDidFinish:(id)arg1;
- (id)animatedViewForZoomTransition;
- (void)CBLBuyPinVariantImagesViewController:(id)arg1 didCloseAtIndex:(unsigned int)arg2;
- (void)presentCheckoutViewController:(id)arg1;
- (void)showCheckoutFlow;
- (void)showAppStoreProduct;
- (void)showShareActionSheetFromButton:(id)arg1;
- (void)showActivitySheet:(id)arg1;
- (void)backgroundTapped:(id)arg1;
- (void)editPinViewControllerShouldDelete:(id)arg1;
- (void)editPinViewControllerDidCancel:(id)arg1;
- (void)editPinViewControllerDidSave:(id)arg1;
- (void)hideTutorialCardAnimated:(BOOL)arg1;
- (void)educationDidComplete:(id)arg1;
- (void)handleNonUserGuideExperience:(id)arg1;
- (id)userGuideContext;
- (id)userGuideAnchorPoints;
- (int)experiencePlacement;
- (BOOL)experienceEnabled;
- (unsigned int)sectionForCollectionViewGrid;
- (void)closeupDateAndSourceViewReportTapped:(id)arg1;
- (void)closeupDateAndSourceViewLabelTapped:(id)arg1;
- (id)indexPathForGrid;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)actionViewTapped:(id)arg1;
- (void)pinCloseupShopMoreViewDidPressShopPins:(id)arg1 withMerchantDomain:(id)arg2;
- (void)pinCloseupBuyableDescriptionViewDidTapReturnPolicy:(id)arg1;
- (void)pinCloseupBuyableDescriptionViewDidTapReadMore:(id)arg1;
- (void)CBLPinCloseupBuyableFooterDidEndScrolling:(id)arg1;
- (void)CBLPinCloseupBuyableFooterDidBeginScrolling:(id)arg1;
- (void)CBLPinCloseupBuyableFooter:(id)arg1 didSelectOptions:(id)arg2;
- (void)mapViewTapped:(id)arg1;
- (void)mapViewDidSelectDirections:(id)arg1;
- (void)pinActionHeaderFacebookButtonPressed:(id)arg1;
- (void)pinActionHeaderBackButtonPressed:(id)arg1;
- (void)pinActionHeaderEditButtonPressed:(id)arg1;
- (void)pinActionHeaderRichActionButtonPressed:(id)arg1;
- (void)pinActionHeaderPinItButtonPressed:(id)arg1;
- (void)pinActionHeaderEditPressed:(id)arg1;
- (void)pinActionHeaderSendButtonPressed:(id)arg1;
- (void)pinActionHeaderShareButtonPressed:(id)arg1;
- (void)pinActionHeaderLikeButtonPressed:(id)arg1;
- (void)pinCloseupAttributionViewWasTapped:(id)arg1;
- (void)pinCloseupCountsViewTappedRepins:(id)arg1;
- (void)pinCloseupCountsViewTappedLikes:(id)arg1;
- (void)pinCloseupCountsViewTappedComments:(id)arg1;
- (void)pinCloseupCountsView:(id)arg1 didTapURL:(id)arg2;
- (void)pinCloseupLinkModuleViewDidTapDomainImage:(id)arg1;
- (void)pinCloseupLinkModuleViewDidTapButton:(id)arg1;
- (void)pinCloseupDescriptionViewDidSelectLink:(id)arg1;
- (void)pinCloseupImageCarouselViewDidScroll:(id)arg1;
- (void)pinCloseupImageCarouselViewDidTap:(id)arg1;
- (void)pinCloseupImageCarouselViewDidLongPress:(id)arg1 gestureRecognizer:(id)arg2;
- (id)displayOptionsForPin:(id)arg1;
- (void)openSourceForPin;
- (void)pinCloseupImageViewDidTap:(id)arg1;
- (void)pinCloseupImageViewDidLongPress:(id)arg1 gestureRecognizer:(id)arg2;
- (void)screenshotIsTaken:(id)arg1;
- (void)hidePinNotificationReceived:(id)arg1;
- (void)transitionToAddPinViewController;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateViewConstraints;
- (void)closeupSectionDidAppear;
- (void)closeupSectionDidDisappear;
- (id)backgroundColorForSection:(int)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionViewLayout:(id)arg1 sizeForHeaderInSection:(int)arg2;
- (id)collectionViewLayout:(id)arg1 headerViewForSection:(int)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (float)collectionViewLayout:(id)arg1 heightForItemAtIndexPath:(id)arg2 forWidth:(int)arg3;
- (struct CGSize)cellSpacingForCollectionViewLayout:(id)arg1 forSection:(int)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionViewLayout:(id)arg1 insetsForSection:(int)arg2;
- (struct _NSRange)columnWidthRangeForCollectionViewLayout:(id)arg1 forSection:(int)arg2;
- (BOOL)contentAvailable;
- (id)scrollViewForChromeHiding;
- (id)barTintColor;
- (BOOL)usesDefaultBackButton;
- (void)setupObserver;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (float)collectionViewTopOffset;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setupDataSource;
- (void)viewDidLoad;
- (id)initWithPin:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

