//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLRemoteModelObject.h"

#import "CBLSearchParameters.h"

@class CBLSearchFilterOption, NSArray, NSString, UIImage;

@interface CBLSearchFilter : CBLRemoteModelObject <CBLSearchParameters>
{
    NSString *_dominantColor;
    UIImage *_backgroundImage;
    NSString *_label;
    NSString *_query;
    int _inputType;
    int _logSelectedIndex;
    NSArray *_options;
    CBLSearchFilterOption *_selectedOption;
}

+ (id)propertyArrayElementClasses;
+ (id)propertyAliases;
@property(retain, nonatomic) CBLSearchFilterOption *selectedOption; // @synthesize selectedOption=_selectedOption;
@property(readonly, copy, nonatomic) NSArray *options; // @synthesize options=_options;
@property(nonatomic) int logSelectedIndex; // @synthesize logSelectedIndex=_logSelectedIndex;
@property(readonly, nonatomic) int inputType; // @synthesize inputType=_inputType;
@property(copy, nonatomic) NSString *query; // @synthesize query=_query;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(copy, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(copy, nonatomic) NSString *dominantColor; // @synthesize dominantColor=_dominantColor;
- (void).cxx_destruct;
@property(readonly) unsigned int hash;
- (BOOL)isEqual:(id)arg1;
- (id)filterLabel;
@property(readonly, nonatomic) unsigned int filterType;
@property(readonly, nonatomic) NSString *filterQuery;
- (id)initWithDictionary:(id)arg1;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

