//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLSelectCheckoutMethodView.h"

@interface CBLSelectShippingDetailsView : CBLSelectCheckoutMethodView
{
}

- (id)titleText;
- (id)addCellText;
- (id)nextButtonText;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 selectedDetails:(id)arg2;

@end

