//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLModelObject.h"

@class NSArray, NSString, NSURL;

@interface CBLStoryRelationships : CBLModelObject
{
    NSURL *_detailNavigationURL;
    id _highlightedObject;
    NSString *_actionButtonText;
    NSURL *_actionButtonDeepLinkURL;
    NSArray *_feedbackIds;
    NSArray *_followIds;
    NSArray *_objects;
    NSString *_highlightedId;
    NSURL *_avatarOverrideURL;
}

+ (id)dynamicProperties;
+ (id)propertyArrayElementClasses;
+ (id)propertyTransformerClasses;
+ (id)propertyAliases;
@property(retain, nonatomic) NSURL *avatarOverrideURL; // @synthesize avatarOverrideURL=_avatarOverrideURL;
@property(copy, nonatomic) NSString *highlightedId; // @synthesize highlightedId=_highlightedId;
@property(copy, nonatomic) NSArray *objects; // @synthesize objects=_objects;
@property(copy, nonatomic) NSArray *followIds; // @synthesize followIds=_followIds;
@property(copy, nonatomic) NSArray *feedbackIds; // @synthesize feedbackIds=_feedbackIds;
@property(retain, nonatomic) NSURL *actionButtonDeepLinkURL; // @synthesize actionButtonDeepLinkURL=_actionButtonDeepLinkURL;
@property(copy, nonatomic) NSString *actionButtonText; // @synthesize actionButtonText=_actionButtonText;
@property(retain, nonatomic) id highlightedObject; // @synthesize highlightedObject=_highlightedObject;
@property(readonly, nonatomic) NSURL *detailNavigationURL; // @synthesize detailNavigationURL=_detailNavigationURL;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSURL *avatarImageURL;
@property(readonly, nonatomic) NSArray *followObjects;
@property(readonly, nonatomic) NSArray *feedbackObjects;
- (id)objectsWithIdentifiers:(id)arg1;
- (id)relationshipObjectOfClass:(Class)arg1;

@end

