//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBLSignupExperimentView, NSDictionary, NSString;

@protocol CBLSignupExperimentViewDelegate <NSObject>
- (void)CBLSignupExperimentView:(CBLSignupExperimentView *)arg1 forgotPasswordForEmail:(NSString *)arg2;
- (void)CBLSignupExperimentView:(CBLSignupExperimentView *)arg1 loginWithEmail:(NSString *)arg2 password:(NSString *)arg3;
- (void)CBLSignupExperimentViewDidPressLogin:(CBLSignupExperimentView *)arg1;
- (void)CBLSignupExperimentView:(CBLSignupExperimentView *)arg1 signupWithMethod:(NSString *)arg2 parameters:(NSDictionary *)arg3;
- (void)CBLSignupExperimentViewDidPressSignup:(CBLSignupExperimentView *)arg1;
- (void)CBLSignupExperimentView:(CBLSignupExperimentView *)arg1 shouldValidateEmail:(NSString *)arg2 block:(void (^)(BOOL))arg3;
- (void)CBLSignupExperimentViewDidPressPolicy:(CBLSignupExperimentView *)arg1;
@end

