//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBLModelObject.h"

@class CBLPin;

@interface CBLTagObject : CBLModelObject
{
    float _relativeCenterX;
    float _relativeCenterY;
    CBLPin *_pin;
}

+ (id)propertyAliases;
@property(retain, nonatomic) CBLPin *pin; // @synthesize pin=_pin;
@property(nonatomic) float relativeCenterY; // @synthesize relativeCenterY=_relativeCenterY;
@property(nonatomic) float relativeCenterX; // @synthesize relativeCenterX=_relativeCenterX;
- (void).cxx_destruct;

@end

