//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "TBase.h"

@class Context, Diagnostics, EventData, NSMutableDictionary, NSString;

@interface Event : NSObject <TBase, NSCoding>
{
    long long __time;
    int __eventType;
    long long __userId;
    long long __objectId;
    NSMutableDictionary *__auxData;
    EventData *__eventData;
    Context *__previousContext;
    Context *__context;
    int __app;
    NSString *__request;
    NSString *__appVersion;
    int __device;
    int __browser;
    int __os;
    NSString *__deviceName;
    NSString *__unauthId;
    NSString *__userIdStr;
    NSString *__objectIdStr;
    NSString *__insertionId;
    int __appState;
    int __site;
    Diagnostics *__diagnostics;
    NSString *__uuid;
    NSMutableDictionary *__pData;
    long long __clientId;
    long long __browserExtensionTrackingId;
    BOOL __time_isset;
    BOOL __eventType_isset;
    BOOL __userId_isset;
    BOOL __objectId_isset;
    BOOL __auxData_isset;
    BOOL __eventData_isset;
    BOOL __previousContext_isset;
    BOOL __context_isset;
    BOOL __app_isset;
    BOOL __request_isset;
    BOOL __appVersion_isset;
    BOOL __device_isset;
    BOOL __browser_isset;
    BOOL __os_isset;
    BOOL __deviceName_isset;
    BOOL __unauthId_isset;
    BOOL __userIdStr_isset;
    BOOL __objectIdStr_isset;
    BOOL __insertionId_isset;
    BOOL __appState_isset;
    BOOL __site_isset;
    BOOL __diagnostics_isset;
    BOOL __uuid_isset;
    BOOL __pData_isset;
    BOOL __clientId_isset;
    BOOL __browserExtensionTrackingId_isset;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)validate;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetBrowserExtensionTrackingId;
- (BOOL)browserExtensionTrackingIdIsSet;
@property(nonatomic, getter=browserExtensionTrackingId, setter=setBrowserExtensionTrackingId:) long long browserExtensionTrackingId;
- (void)unsetClientId;
- (BOOL)clientIdIsSet;
@property(nonatomic, getter=clientId, setter=setClientId:) long long clientId;
- (void)unsetPData;
- (BOOL)pDataIsSet;
@property(retain, nonatomic, getter=pData, setter=setPData:) NSMutableDictionary *pData;
- (void)unsetUuid;
- (BOOL)uuidIsSet;
@property(retain, nonatomic, getter=uuid, setter=setUuid:) NSString *uuid;
- (void)unsetDiagnostics;
- (BOOL)diagnosticsIsSet;
@property(retain, nonatomic, getter=diagnostics, setter=setDiagnostics:) Diagnostics *diagnostics;
- (void)unsetSite;
- (BOOL)siteIsSet;
@property(nonatomic, getter=site, setter=setSite:) int site;
- (void)unsetAppState;
- (BOOL)appStateIsSet;
@property(nonatomic, getter=appState, setter=setAppState:) int appState;
- (void)unsetInsertionId;
- (BOOL)insertionIdIsSet;
@property(retain, nonatomic, getter=insertionId, setter=setInsertionId:) NSString *insertionId;
- (void)unsetObjectIdStr;
- (BOOL)objectIdStrIsSet;
@property(retain, nonatomic, getter=objectIdStr, setter=setObjectIdStr:) NSString *objectIdStr;
- (void)unsetUserIdStr;
- (BOOL)userIdStrIsSet;
@property(retain, nonatomic, getter=userIdStr, setter=setUserIdStr:) NSString *userIdStr;
- (void)unsetUnauthId;
- (BOOL)unauthIdIsSet;
@property(retain, nonatomic, getter=unauthId, setter=setUnauthId:) NSString *unauthId;
- (void)unsetDeviceName;
- (BOOL)deviceNameIsSet;
@property(retain, nonatomic, getter=deviceName, setter=setDeviceName:) NSString *deviceName;
- (void)unsetOs;
- (BOOL)osIsSet;
@property(nonatomic, getter=os, setter=setOs:) int os;
- (void)unsetBrowser;
- (BOOL)browserIsSet;
@property(nonatomic, getter=browser, setter=setBrowser:) int browser;
- (void)unsetDevice;
- (BOOL)deviceIsSet;
@property(nonatomic, getter=device, setter=setDevice:) int device;
- (void)unsetAppVersion;
- (BOOL)appVersionIsSet;
@property(retain, nonatomic, getter=appVersion, setter=setAppVersion:) NSString *appVersion;
- (void)unsetRequest;
- (BOOL)requestIsSet;
@property(retain, nonatomic, getter=request, setter=setRequest:) NSString *request;
- (void)unsetApp;
- (BOOL)appIsSet;
@property(nonatomic, getter=app, setter=setApp:) int app;
- (void)unsetContext;
- (BOOL)contextIsSet;
@property(retain, nonatomic, getter=context, setter=setContext:) Context *context;
- (void)unsetPreviousContext;
- (BOOL)previousContextIsSet;
@property(retain, nonatomic, getter=previousContext, setter=setPreviousContext:) Context *previousContext;
- (void)unsetEventData;
- (BOOL)eventDataIsSet;
@property(retain, nonatomic, getter=eventData, setter=setEventData:) EventData *eventData;
- (void)unsetAuxData;
- (BOOL)auxDataIsSet;
@property(retain, nonatomic, getter=auxData, setter=setAuxData:) NSMutableDictionary *auxData;
- (void)unsetObjectId;
- (BOOL)objectIdIsSet;
@property(nonatomic, getter=objectId, setter=setObjectId:) long long objectId;
- (void)unsetUserId;
- (BOOL)userIdIsSet;
@property(nonatomic, getter=userId, setter=setUserId:) long long userId;
- (void)unsetEventType;
- (BOOL)eventTypeIsSet;
@property(nonatomic, getter=eventType, setter=setEventType:) int eventType;
- (void)unsetTime;
- (BOOL)timeIsSet;
@property(nonatomic, getter=time, setter=setTime:) long long time;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTime:(long long)arg1 eventType:(int)arg2 userId:(long long)arg3 objectId:(long long)arg4 auxData:(id)arg5 eventData:(id)arg6 previousContext:(id)arg7 context:(id)arg8 app:(int)arg9 request:(id)arg10 appVersion:(id)arg11 device:(int)arg12 browser:(int)arg13 os:(int)arg14 deviceName:(id)arg15 unauthId:(id)arg16 userIdStr:(id)arg17 objectIdStr:(id)arg18 insertionId:(id)arg19 appState:(int)arg20 site:(int)arg21 diagnostics:(id)arg22 uuid:(id)arg23 pData:(id)arg24 clientId:(long long)arg25 browserExtensionTrackingId:(long long)arg26;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

