//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "PPDeviceCheckViewDelegate.h"
#import "PPSelectPaymentFlowDelegate.h"

@class NSString, PPSelectPaymentFlowManager;

@interface PayPalPaymentViewController : UINavigationController <PPDeviceCheckViewDelegate, PPSelectPaymentFlowDelegate>
{
    BOOL _rememberUserAfterLibraryDismissal;
    BOOL _collectExpiry;
    BOOL _collectCVV;
    BOOL _collectPostalCode;
    id <PayPalPaymentDelegate> _paymentDelegate;
    int _state;
    PPSelectPaymentFlowManager *_selectPaymentFlow;
}

@property(nonatomic) BOOL collectPostalCode; // @synthesize collectPostalCode=_collectPostalCode;
@property(nonatomic) BOOL collectCVV; // @synthesize collectCVV=_collectCVV;
@property(nonatomic) BOOL collectExpiry; // @synthesize collectExpiry=_collectExpiry;
@property(retain, nonatomic) PPSelectPaymentFlowManager *selectPaymentFlow; // @synthesize selectPaymentFlow=_selectPaymentFlow;
@property(nonatomic) BOOL rememberUserAfterLibraryDismissal; // @synthesize rememberUserAfterLibraryDismissal=_rememberUserAfterLibraryDismissal;
@property(nonatomic) int state; // @synthesize state=_state;
@property(readonly, nonatomic) __weak id <PayPalPaymentDelegate> paymentDelegate; // @synthesize paymentDelegate=_paymentDelegate;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (BOOL)prefersStatusBarHidden;
- (int)preferredStatusBarStyle;
- (BOOL)disablesAutomaticKeyboardDismissal;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)selectPaymentFlowWillComplete:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)selectPaymentFlowUserDidCancel:(id)arg1;
- (void)selectPaymentFlowDidComplete:(id)arg1;
- (void)deviceDidSucceedDeviceCheckViewController:(id)arg1;
- (void)userDidCancelDeviceCheckViewController:(id)arg1;
- (id)initWithPayment:(id)arg1 configuration:(id)arg2 delegate:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

