//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "TBase.h"

@class NSString, PhantomRawResult;

@interface PhantomScraperResult : NSObject <TBase, NSCoding>
{
    NSString *__baseUrl;
    NSString *__amzUrl;
    PhantomRawResult *__rawResult;
    BOOL __baseUrl_isset;
    BOOL __amzUrl_isset;
    BOOL __rawResult_isset;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)validate;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetRawResult;
- (BOOL)rawResultIsSet;
@property(retain, nonatomic, getter=rawResult, setter=setRawResult:) PhantomRawResult *rawResult;
- (void)unsetAmzUrl;
- (BOOL)amzUrlIsSet;
@property(retain, nonatomic, getter=amzUrl, setter=setAmzUrl:) NSString *amzUrl;
- (void)unsetBaseUrl;
- (BOOL)baseUrlIsSet;
@property(retain, nonatomic, getter=baseUrl, setter=setBaseUrl:) NSString *baseUrl;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithBaseUrl:(id)arg1 amzUrl:(id)arg2 rawResult:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

