//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PKPayment.h"

@class NSString;

@interface PKPayment (STPTestKeys)
@property(retain, nonatomic) NSString *stp_testCardNumber; // @dynamic stp_testCardNumber;
@end

