//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PPBaseViewController.h"

#import "UIWebViewDelegate.h"

@class NSDictionary, NSString, UIWebView;

@interface PPHTMLTextViewController : PPBaseViewController <UIWebViewDelegate>
{
    NSString *_htmlText;
    NSDictionary *_analyticsLinks;
    UIWebView *_webView;
}

@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSDictionary *analyticsLinks; // @synthesize analyticsLinks=_analyticsLinks;
@property(retain, nonatomic) NSString *htmlText; // @synthesize htmlText=_htmlText;
- (void).cxx_destruct;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)goBack;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

