//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PKPaymentRequest, STPTestAddressStore, STPTestCardStore, STPTestShippingMethodStore, UIActivityIndicatorView, UIButton, UITableView;

@interface STPTestPaymentSummaryViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    id <PKPaymentAuthorizationViewControllerDelegate> _delegate;
    UIActivityIndicatorView *_activityIndicator;
    UIButton *_payButton;
    UITableView *_tableView;
    PKPaymentRequest *_paymentRequest;
    NSArray *_summaryItems;
    STPTestCardStore *_cardStore;
    STPTestAddressStore *_billingAddressStore;
    STPTestAddressStore *_shippingAddressStore;
    STPTestShippingMethodStore *_shippingMethodStore;
    NSArray *_sectionTitles;
}

@property(retain, nonatomic) NSArray *sectionTitles; // @synthesize sectionTitles=_sectionTitles;
@property(retain, nonatomic) STPTestShippingMethodStore *shippingMethodStore; // @synthesize shippingMethodStore=_shippingMethodStore;
@property(retain, nonatomic) STPTestAddressStore *shippingAddressStore; // @synthesize shippingAddressStore=_shippingAddressStore;
@property(retain, nonatomic) STPTestAddressStore *billingAddressStore; // @synthesize billingAddressStore=_billingAddressStore;
@property(retain, nonatomic) STPTestCardStore *cardStore; // @synthesize cardStore=_cardStore;
@property(retain, nonatomic) NSArray *summaryItems; // @synthesize summaryItems=_summaryItems;
@property(retain, nonatomic) PKPaymentRequest *paymentRequest; // @synthesize paymentRequest=_paymentRequest;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UIButton *payButton; // @synthesize payButton=_payButton;
@property(nonatomic) __weak UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) id <PKPaymentAuthorizationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)didSelectShippingAddress;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)storeForSection:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)cancel:(id)arg1;
- (void)makePayment:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)updateSectionTitles;
- (id)initWithPaymentRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

