//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (GTMUIImageResizeAdditions)
- (id)gtm_imageByRotating:(int)arg1;
- (id)gtm_imageByResizingToSize:(struct CGSize)arg1 preserveAspectRatio:(BOOL)arg2 trimToFit:(BOOL)arg3;
@end

