//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventPublisher, NSDictionary, NSString, NSUserDefaults, ThreadSafeDictionary, XMPPJID;

@interface AccountUserDefaults : NSObject
{
    BOOL _disableNotificationSounds;
    BOOL _displayMentionPushNotifications;
    BOOL _displayOTOCallPushNotifications;
    BOOL _displayOTOMessagePushNotifications;
    BOOL _displayRoomInvitePushNotifications;
    BOOL _notifyByBouncingTheDockIcon;
    BOOL _notifyByShowingAPopup;
    BOOL _notifyForIncomingMessageInOpenRoom;
    BOOL _notifyForIncomingMessageInPrivateRoom;
    BOOL _notifyForIncomingPrivateMessage;
    BOOL _notifyForMentionInARoom;
    BOOL _notifyWhileStatusIsDND;
    BOOL _userExplicitlySignedOut;
    BOOL _userUpdatedPushNotificationSettings;
    NSUserDefaults *_userDefaults;
    NSString *_accountID;
    ThreadSafeDictionary *_userDefaultsDictionary;
    NSDictionary *_commandToKeyDictionary;
    EventPublisher *_eventPublisher;
}

@property(retain, nonatomic) EventPublisher *eventPublisher; // @synthesize eventPublisher=_eventPublisher;
@property(readonly, nonatomic) NSDictionary *commandToKeyDictionary; // @synthesize commandToKeyDictionary=_commandToKeyDictionary;
@property(retain, nonatomic) ThreadSafeDictionary *userDefaultsDictionary; // @synthesize userDefaultsDictionary=_userDefaultsDictionary;
@property(copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(nonatomic) BOOL userUpdatedPushNotificationSettings; // @synthesize userUpdatedPushNotificationSettings=_userUpdatedPushNotificationSettings;
@property(nonatomic) BOOL userExplicitlySignedOut; // @synthesize userExplicitlySignedOut=_userExplicitlySignedOut;
@property(nonatomic) BOOL notifyWhileStatusIsDND; // @synthesize notifyWhileStatusIsDND=_notifyWhileStatusIsDND;
@property(nonatomic) BOOL notifyForMentionInARoom; // @synthesize notifyForMentionInARoom=_notifyForMentionInARoom;
@property(nonatomic) BOOL notifyForIncomingPrivateMessage; // @synthesize notifyForIncomingPrivateMessage=_notifyForIncomingPrivateMessage;
@property(nonatomic) BOOL notifyForIncomingMessageInPrivateRoom; // @synthesize notifyForIncomingMessageInPrivateRoom=_notifyForIncomingMessageInPrivateRoom;
@property(nonatomic) BOOL notifyForIncomingMessageInOpenRoom; // @synthesize notifyForIncomingMessageInOpenRoom=_notifyForIncomingMessageInOpenRoom;
@property(nonatomic) BOOL notifyByShowingAPopup; // @synthesize notifyByShowingAPopup=_notifyByShowingAPopup;
@property(nonatomic) BOOL notifyByBouncingTheDockIcon; // @synthesize notifyByBouncingTheDockIcon=_notifyByBouncingTheDockIcon;
@property(nonatomic) BOOL displayRoomInvitePushNotifications; // @synthesize displayRoomInvitePushNotifications=_displayRoomInvitePushNotifications;
@property(nonatomic) BOOL displayOTOMessagePushNotifications; // @synthesize displayOTOMessagePushNotifications=_displayOTOMessagePushNotifications;
@property(nonatomic) BOOL displayOTOCallPushNotifications; // @synthesize displayOTOCallPushNotifications=_displayOTOCallPushNotifications;
@property(nonatomic) BOOL displayMentionPushNotifications; // @synthesize displayMentionPushNotifications=_displayMentionPushNotifications;
@property(nonatomic) BOOL disableNotificationSounds; // @synthesize disableNotificationSounds=_disableNotificationSounds;
- (void).cxx_destruct;
- (id)description;
- (BOOL)localValueForNotifyWhileDND;
- (void)updatePreferencesWithStartupInfo:(id)arg1;
@property(nonatomic) int soundNotificationVolume;
@property(copy, nonatomic) NSString *cachedMentionRegex;
@property(copy, nonatomic) NSString *emoticonPathPrefix;
@property(copy, nonatomic) NSString *emoticonVersion;
@property(copy, nonatomic) NSString *rosterVersion;
@property(copy, nonatomic) NSString *selectedChatName;
@property(retain, nonatomic) XMPPJID *selectedChatJID;
@property(copy, nonatomic) NSString *userID;
@property(copy, nonatomic) NSString *hostname;
@property(copy, nonatomic) NSString *groupID;
- (BOOL)boolForKey:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)saveObject:(id)arg1 forKey:(id)arg2;
- (void)checkForLegacyDefaults;
- (void)saveUserDefaults;
- (void)setupCommandToKeyDictionary;
- (void)setupUserDefaults;
- (void)defineProperty:(id)arg1 withKey:(id)arg2;
- (id)initWithAccountID:(id)arg1 eventPublisher:(id)arg2;

@end

