//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Browser, NSArray, NSURL;

@protocol BrowserManager <NSObject>
@property(retain, nonatomic) Browser *selectedBrowser;
- (void)openURL:(NSURL *)arg1;
- (BOOL)canOpenURLExternally:(NSURL *)arg1;
- (NSArray *)availableBrowsers;
@end

