//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NRMAInteractionDataStamp, NRMATrace, NSMutableDictionary, NSMutableSet, NSString;

@interface NRMAActivityTrace : NSObject
{
    CDStruct_9170365d _lastCPUTime;
    BOOL _lastCPUTimeValid;
    double _lastRecordVitalsTime;
    BOOL _isComplete;
    NSMutableDictionary *_traces;
    NSString *_initiatingObjectIdentifier;
    NRMATrace *_rootTrace;
    NSMutableSet *_missingChildren;
    NSString *_type;
    NSString *_name;
    NSMutableDictionary *_memoryVitals;
    NSMutableDictionary *_cpuVitals;
    unsigned int _nodes;
    NRMAInteractionDataStamp *_lastActivityStamp;
    double _lastUpdated;
    double _totalExclusiveTimeMillis;
    double _totalNetworkTimeMillis;
    double _startTime;
    double _endTime;
}

@property(retain) NRMAInteractionDataStamp *lastActivityStamp; // @synthesize lastActivityStamp=_lastActivityStamp;
@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) unsigned int nodes; // @synthesize nodes=_nodes;
@property(nonatomic) double totalNetworkTimeMillis; // @synthesize totalNetworkTimeMillis=_totalNetworkTimeMillis;
@property(nonatomic) double totalExclusiveTimeMillis; // @synthesize totalExclusiveTimeMillis=_totalExclusiveTimeMillis;
@property(retain, nonatomic) NSMutableDictionary *cpuVitals; // @synthesize cpuVitals=_cpuVitals;
@property(retain, nonatomic) NSMutableDictionary *memoryVitals; // @synthesize memoryVitals=_memoryVitals;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property BOOL isComplete; // @synthesize isComplete=_isComplete;
@property(nonatomic) double lastUpdated; // @synthesize lastUpdated=_lastUpdated;
@property(retain) NSMutableSet *missingChildren; // @synthesize missingChildren=_missingChildren;
@property(retain, nonatomic) NRMATrace *rootTrace; // @synthesize rootTrace=_rootTrace;
@property(retain, nonatomic) NSString *initiatingObjectIdentifier; // @synthesize initiatingObjectIdentifier=_initiatingObjectIdentifier;
@property(retain, nonatomic) NSMutableDictionary *traces; // @synthesize traces=_traces;
- (void).cxx_destruct;
- (BOOL)shouldRecord;
- (double)durationInSeconds;
- (void)complete;
- (BOOL)hasMissingChildren;
- (void)recordVitals;
- (void)recordVitalsThrottled;
- (void)addTrace:(id)arg1;
- (id)initWithRootTrace:(id)arg1;

@end

