//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSPDFTableViewCell.h"

#import "PSPDFCacheDelegate.h"

@class NSAttributedString, NSString, PSPDFCache, PSPDFDocument, UIImage;

@interface PSPDFSearchResultCell : PSPDFTableViewCell <PSPDFCacheDelegate>
{
    BOOL _useOutlineForPageNames;
    PSPDFDocument *_document;
    unsigned int _page;
    NSAttributedString *_attributedString;
    PSPDFCache *_cache;
    struct CGRect _rotatedPageRect;
}

+ (id)attributedPreviewTextForSearchResult:(id)arg1;
+ (id)detailLabelFont;
+ (id)textLabelFont;
+ (float)heightForSearchResult:(id)arg1 cellWidth:(float)arg2 maxNumberOfPreviewLines:(unsigned int)arg3;
+ (float)heightForSearchPreviewText:(id)arg1 cellWidth:(float)arg2 rotatedPageRect:(struct CGRect)arg3 maxNumberOfPreviewLines:(unsigned int)arg4;
@property(retain, nonatomic) PSPDFCache *cache; // @synthesize cache=_cache;
@property(copy, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
@property(nonatomic) struct CGRect rotatedPageRect; // @synthesize rotatedPageRect=_rotatedPageRect;
@property(nonatomic) BOOL useOutlineForPageNames; // @synthesize useOutlineForPageNames=_useOutlineForPageNames;
@property(nonatomic) unsigned int page; // @synthesize page=_page;
@property(nonatomic) __weak PSPDFDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (id)placeholderImage;
- (void)didRenderImage:(id)arg1 document:(id)arg2 page:(unsigned int)arg3 size:(struct CGSize)arg4;
@property(retain, nonatomic) UIImage *pagePreviewImage;
- (void)configureWithDocument:(id)arg1 page:(unsigned int)arg2 text:(id)arg3 detailText:(id)arg4;
- (void)configureWithSearchResult:(id)arg1;
- (void)contentSizeDidChange;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

