//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSPDFAnnotation.h"

@class NSArray, NSObject<OS_dispatch_queue>, PSPDFNaturalDrawingPaths, UIBezierPath;

@interface PSPDFInkAnnotation : PSPDFAnnotation
{
    BOOL _naturalDrawingEnabled;
    BOOL _isSignature;
    NSArray *_lines;
    NSArray *_lineArray;
    NSObject<OS_dispatch_queue> *_bezierPathQueue;
    UIBezierPath *_bezierPathBackingStore;
    UIBezierPath *_hitTestBezierPathBackingStore;
    PSPDFNaturalDrawingPaths *_naturalDrawingPaths;
}

+ (id)keysForValuesToObserveForUndo;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)lineArrayJSONTransformer;
+ (id)propertyKeys;
+ (id)keyPathsForValuesAffectingLines;
+ (BOOL)isWriteable;
+ (id)supportedTypes;
@property(retain, nonatomic) PSPDFNaturalDrawingPaths *naturalDrawingPaths; // @synthesize naturalDrawingPaths=_naturalDrawingPaths;
@property(copy, nonatomic) UIBezierPath *hitTestBezierPathBackingStore; // @synthesize hitTestBezierPathBackingStore=_hitTestBezierPathBackingStore;
@property(copy, nonatomic) UIBezierPath *bezierPathBackingStore; // @synthesize bezierPathBackingStore=_bezierPathBackingStore;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *bezierPathQueue; // @synthesize bezierPathQueue=_bezierPathQueue;
@property(copy, nonatomic) NSArray *lineArray; // @synthesize lineArray=_lineArray;
@property(nonatomic) BOOL isSignature; // @synthesize isSignature=_isSignature;
@property(nonatomic) BOOL naturalDrawingEnabled; // @synthesize naturalDrawingEnabled=_naturalDrawingEnabled;
- (void).cxx_destruct;
- (void)clearBezierPathBackingStore;
- (void)didReceiveMemoryWarning:(id)arg1;
- (id)decodeAdditionalValues:(id)arg1 model:(unsigned int)arg2;
- (BOOL)hitTest:(struct CGPoint)arg1 minDiameter:(float)arg2;
- (void)recalculateBoundingBox;
- (id)hitTestBezierPathForLineWidth:(float)arg1;
- (BOOL)isEmpty;
@property(readonly, copy, nonatomic) UIBezierPath *bezierPath;
- (void)setLineWidth:(float)arg1;
@property(copy, nonatomic) NSArray *lines; // @synthesize lines=_lines;
- (id)copyLinesByApplyingTransform:(struct CGAffineTransform)arg1;
- (void)setBoundingBox:(struct CGRect)arg1 transformLines:(BOOL)arg2;
- (void)updateOptionalPropertiesWithTransform:(struct CGAffineTransform)arg1 isSizeChange:(BOOL)arg2 meanScale:(float)arg3;
- (void)updatePropertiesWithTransform:(struct CGAffineTransform)arg1 isSizeChange:(BOOL)arg2 meanScale:(float)arg3;
- (BOOL)shouldUpdateOptionalPropertiesOnBoundsChange;
- (BOOL)shouldUpdatePropertiesOnBoundsChange;
- (id)localizedDescription;
- (struct CGPoint)noteIconPoint;
- (BOOL)isResizable;
- (id)PDFDataRepresentationsWithOptions:(id)arg1;
- (void)drawInContext:(struct CGContext *)arg1 withOptions:(id)arg2;
- (void)dealloc;
- (void)commonInit;
- (id)description;
- (id)initWithAnnotationDictionary:(struct CGPDFDictionary *)arg1 inAnnotsArray:(struct CGPDFArray *)arg2 documentRef:(struct CGPDFDocument *)arg3;
- (id)initWithLines:(id)arg1;
- (id)init;

@end

