//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSPDFStaticTableViewController.h"

#import "PSPDFStylusDriverDelegate.h"

@class NSOrderedSet, NSString, PSPDFCellModel, PSPDFSectionModel, PSPDFStylusManager, UIViewController;

@interface PSPDFStylusViewController : PSPDFStaticTableViewController <PSPDFStylusDriverDelegate>
{
    Class _selectedDriverClass;
    PSPDFStylusManager *_stylusManager;
    id <PSPDFStylusViewControllerDelegate> _delegate;
    NSOrderedSet *_driverClasses;
    PSPDFSectionModel *_settingsSection;
    PSPDFCellModel *_settingsCell;
    UIViewController *_embeddedSettingsController;
}

@property(retain, nonatomic) UIViewController *embeddedSettingsController; // @synthesize embeddedSettingsController=_embeddedSettingsController;
@property(retain, nonatomic) PSPDFCellModel *settingsCell; // @synthesize settingsCell=_settingsCell;
@property(retain, nonatomic) PSPDFSectionModel *settingsSection; // @synthesize settingsSection=_settingsSection;
@property(copy, nonatomic) NSOrderedSet *driverClasses; // @synthesize driverClasses=_driverClasses;
@property(nonatomic) __weak id <PSPDFStylusViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) PSPDFStylusManager *stylusManager; // @synthesize stylusManager=_stylusManager;
@property(retain, nonatomic) Class selectedDriverClass; // @synthesize selectedDriverClass=_selectedDriverClass;
- (void).cxx_destruct;
- (void)connectionStatusChanged;
- (void)viewDidLoad;
- (void)dealloc;
- (void)commonInit;
- (id)initWithStylusManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

