//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIButton;

@interface PSPDFToolbarButtonLayoutAttributes : NSObject
{
    BOOL _collapsible;
    BOOL _collapsed;
    BOOL _flexible;
    BOOL _cutOff;
    UIButton *_button;
    float _origin;
    float _length;
}

+ (id)layoutAttributesArrayForButtons:(id)arg1 defaultLength:(float)arg2;
@property(nonatomic) float length; // @synthesize length=_length;
@property(nonatomic) float origin; // @synthesize origin=_origin;
@property(nonatomic, getter=isCutOff) BOOL cutOff; // @synthesize cutOff=_cutOff;
@property(nonatomic, getter=isFlexible) BOOL flexible; // @synthesize flexible=_flexible;
@property(nonatomic, getter=isCollapsed) BOOL collapsed; // @synthesize collapsed=_collapsed;
@property(nonatomic, getter=isCollapsible) BOOL collapsible; // @synthesize collapsible=_collapsible;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
- (void).cxx_destruct;
- (id)description;
- (void)applyToFrameHorizontally:(BOOL)arg1 withHeight:(float)arg2;
- (float)visibleLength;
- (id)initWithButton:(id)arg1 defaultLength:(float)arg2;

@end

