//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSPDFAnnotation.h"

@class NSString;

@interface PSPDFAbstractTextOverlayAnnotation : PSPDFAnnotation
{
    NSString *_highlightedStringCache;
}

+ (id)textOverlayAnnotationWithGlyphs:(id)arg1 pageRotationTransform:(struct CGAffineTransform)arg2;
@property(copy) NSString *highlightedStringCache; // @synthesize highlightedStringCache=_highlightedStringCache;
- (void).cxx_destruct;
- (void)setDirty:(BOOL)arg1;
- (id)highlightedString;
- (id)highlightedStringWithoutNewlines;
- (id)PDFDataRepresentationsWithOptions:(id)arg1;
- (struct CGPoint)noteIconPoint;
- (void)copyToClipboard;
- (id)localizedDescription;
- (BOOL)requriesPopupAnnotation;

@end

