//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AccountConnectionAnalyticsObserverDelegate.h"
#import "CallCenterDelegate.h"
#import "FileViewerHelperDelegate.h"
#import "IncomingCallDelegate.h"
#import "MenuViewControllerDelegate.h"
#import "SignInDelegate.h"

@class AccountContext, FileViewerHelper, HipChatContext, IncomingCallViewController, MenuViewController, NSString, NavigationBannerController, UIAlertView, UINavigationController, VideoViewController, WebViewController, XMPPJID;

@interface RootViewController : UIViewController <CallCenterDelegate, IncomingCallDelegate, MenuViewControllerDelegate, SignInDelegate, AccountConnectionAnalyticsObserverDelegate, FileViewerHelperDelegate>
{
    BOOL _autoConnecting;
    BOOL _disconnected;
    XMPPJID *_launchChatJID;
    NSString *_launchChatName;
    HipChatContext *_context;
    UIViewController *_presentedBaseViewController;
    WebViewController *_webBrowser;
    UINavigationController *_customNavigationController;
    MenuViewController *_menuViewController;
    UIAlertView *_roomInviteAlertView;
    XMPPJID *_roomInviteJID;
    VideoViewController *_videoViewController;
    IncomingCallViewController *_incomingCallViewController;
    NavigationBannerController *_reconnectionBanner;
    AccountContext *_currentAccountContext;
    FileViewerHelper *_fileViewerHelper;
}

@property(retain, nonatomic) FileViewerHelper *fileViewerHelper; // @synthesize fileViewerHelper=_fileViewerHelper;
@property(nonatomic) __weak AccountContext *currentAccountContext; // @synthesize currentAccountContext=_currentAccountContext;
@property(nonatomic, getter=isDisconnected) BOOL disconnected; // @synthesize disconnected=_disconnected;
@property(nonatomic, getter=isAutoConnecting) BOOL autoConnecting; // @synthesize autoConnecting=_autoConnecting;
@property(retain, nonatomic) NavigationBannerController *reconnectionBanner; // @synthesize reconnectionBanner=_reconnectionBanner;
@property(retain, nonatomic) IncomingCallViewController *incomingCallViewController; // @synthesize incomingCallViewController=_incomingCallViewController;
@property(retain, nonatomic) VideoViewController *videoViewController; // @synthesize videoViewController=_videoViewController;
@property(retain, nonatomic) XMPPJID *roomInviteJID; // @synthesize roomInviteJID=_roomInviteJID;
@property(retain, nonatomic) UIAlertView *roomInviteAlertView; // @synthesize roomInviteAlertView=_roomInviteAlertView;
@property(retain, nonatomic) MenuViewController *menuViewController; // @synthesize menuViewController=_menuViewController;
@property(retain, nonatomic) UINavigationController *customNavigationController; // @synthesize customNavigationController=_customNavigationController;
@property(retain, nonatomic) WebViewController *webBrowser; // @synthesize webBrowser=_webBrowser;
@property(retain, nonatomic) UIViewController *presentedBaseViewController; // @synthesize presentedBaseViewController=_presentedBaseViewController;
@property(nonatomic) __weak HipChatContext *context; // @synthesize context=_context;
@property(copy, nonatomic) NSString *launchChatName; // @synthesize launchChatName=_launchChatName;
@property(retain, nonatomic) XMPPJID *launchChatJID; // @synthesize launchChatJID=_launchChatJID;
- (void).cxx_destruct;
- (void)fileViewerHelper:(id)arg1 failedToPresentDocumentAtURL:(id)arg2;
- (void)fileViewerHelper:(id)arg1 didGenerateAnalyticsEvent:(id)arg2 attributes:(id)arg3;
- (id)keyCommands;
- (BOOL)viewControllerCanDisplayReconnectionBanner:(id)arg1;
- (void)hideReconnectionBanner;
- (void)showReconnectionBanner;
- (void)onNetworkReachabilityStatusChangedEvent:(id)arg1;
- (void)onAccountAddedEvent:(id)arg1;
- (void)openBrowserForRequest:(id)arg1;
- (void)handleFile:(id)arg1;
- (int)preferredStatusBarStyle;
- (void)joinCallWithVideo:(id)arg1 inAccountContext:(id)arg2 options:(int)arg3;
- (void)declineCall:(id)arg1;
- (void)ignoreCall:(id)arg1;
- (void)incomingCallHandledInContext:(id)arg1 fromChatID:(id)arg2;
- (void)incomingCallInAccountContext:(id)arg1 fromChatID:(id)arg2 withOptions:(int)arg3;
- (void)activeCallWasHungUpInContext:(id)arg1 byUserWithJid:(id)arg2;
- (void)outgoingCallAcceptedInContext:(id)arg1 byUserWithJid:(id)arg2;
- (void)showIncomingCallView:(id)arg1 forAccountContext:(id)arg2 options:(int)arg3;
- (id)incomingCallViewControllerForAccountContext:(id)arg1;
- (void)focusCurrentVideo:(BOOL)arg1;
- (void)focusVideo:(id)arg1;
- (void)showVideo:(id)arg1 withOptions:(int)arg2 inAccountContext:(id)arg3 isAccept:(BOOL)arg4;
- (void)joinVideo:(id)arg1;
- (id)videoViewControllerForAccountContext:(id)arg1;
- (void)configureChat:(id)arg1 forEntryFromInteractiveNotificationActionWithPayload:(id)arg2;
- (void)focusChatNotificationReceived:(id)arg1;
- (void)focusLobby:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)roomInviteAlertViewForEvent:(id)arg1;
- (void)onRoomRemotelyJoinedEvent:(id)arg1;
- (void)onRoomInviteReceivedEvent:(id)arg1;
- (BOOL)isShowingChatView;
- (void)menuViewController:(id)arg1 didSelectChatWithJID:(id)arg2;
- (void)onRoomLeaveEvent;
- (void)onAccountSignedOutEvent:(id)arg1;
- (void)resetNavigationStackForLaunchChatIfNeeded;
- (id)chatContainerViewControllerForJID:(id)arg1;
- (id)pushChatContainerViewControllerForJIDOnNavigationStack:(id)arg1 animated:(BOOL)arg2;
- (id)presentChatForJID:(id)arg1 animated:(BOOL)arg2;
- (void)transitionToSignInWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentBaseViewController:(id)arg1 animatedWithOptions:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentBaseViewController:(id)arg1;
- (void)addChildViewController:(id)arg1;
- (void)presentSignInInterface;
- (void)presentMenuInterfaceWithAnimation:(BOOL)arg1;
- (void)presentInitialInterface;
- (void)signInViewControllerDidFinish:(id)arg1;
- (void)showAutoSignInFailedAlertFromError:(id)arg1;
- (void)doSignInFailure:(id)arg1;
- (void)autoSignInFailedWithError:(id)arg1;
- (void)performAutoSignIn;
- (void)configureSessionCleanUp;
- (void)registerObservers;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

