//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class IOSIntArray, IOSLongArray;

@interface AndroidUtilSparseLongArray : NSObject <NSCopying>
{
    IOSIntArray *mKeys_;
    IOSLongArray *mValues_;
    int mSize_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (void)growKeyAndValueArraysWithInt:(int)arg1;
- (void)appendWithInt:(int)arg1 withLong:(long long)arg2;
- (void)clear;
- (int)indexOfValueWithLong:(long long)arg1;
- (int)indexOfKeyWithInt:(int)arg1;
- (long long)valueAtWithInt:(int)arg1;
- (int)keyAtWithInt:(int)arg1;
- (int)size;
- (void)putWithInt:(int)arg1 withLong:(long long)arg2;
- (void)removeAtWithInt:(int)arg1;
- (void)delete__WithInt:(int)arg1;
- (long long)getWithInt:(int)arg1 withLong:(long long)arg2;
- (long long)getWithInt:(int)arg1;
- (id)clone;
- (id)initWithInt:(int)arg1;
- (id)init;

@end

