//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton;

@interface ClusterTitleView : UIView
{
    UIButton *title_;
    id <ClusterTitleViewDelegate> _delegate;
}

@property(nonatomic) id <ClusterTitleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)titleTapped:(id)arg1;
- (void)createSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
@property(nonatomic) struct UIEdgeInsets edgeInsets;
@property(copy, nonatomic) NSString *clusterTitle;
- (id)init;

@end

