//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Clusters : NSObject
{
}

+ (id)titleForClusterWithType:(id)arg1;
+ (id)clusterAtticSelectedColorForType:(unsigned int)arg1;
+ (id)clusterTitleColorForType:(unsigned int)arg1;
+ (id)clusterNavbarSeparatorColorForType:(unsigned int)arg1;
+ (id)clusterNavbarColorForType:(unsigned int)arg1;
+ (id)panelIconNameForTopicClusterWithType:(id)arg1;
+ (id)topicClusterGroupTitleForType:(unsigned int)arg1;
+ (id)topicTypeForNavigationType:(unsigned int)arg1;
+ (unsigned int)navigationTypeForTopicClusterWithType:(id)arg1;
+ (unsigned int)navigationTypeForCluster:(id)arg1;
+ (id)systemClusterTitleForType:(unsigned int)arg1;
+ (BOOL)isTopicWithType:(unsigned int)arg1;
+ (BOOL)isSystemClusterWithType:(unsigned int)arg1;
+ (id)starredDescriptionForClusterType:(id)arg1;
+ (id)messageForAutomaticMoveWithCriteria:(id)arg1;
+ (id)titleForClusterSectionWithType:(id)arg1;
+ (id)notificationStringForClusteredItems:(id)arg1;
+ (id)countDisplayStringWithItemCount:(id)arg1;
+ (id)iconColorForTopicClusterGroupWithType:(id)arg1;
+ (id)iconColorForClusterWithType:(id)arg1;
+ (id)iconColorForCluster:(id)arg1;
+ (id)panelIconNameForClusterWithType:(id)arg1;
+ (id)iconNameForTopicClusterWithType:(id)arg1;
+ (id)iconNameForClusterWithType:(id)arg1;
+ (id)iconNameForCluster:(id)arg1;
+ (id)avatarIconNameForTopicClusterWithType:(id)arg1;
+ (id)avatarIconNameForClusterWithType:(id)arg1;
+ (id)stringForApproximateUnseenCount:(id)arg1;
+ (id)displayNameForCluster:(id)arg1;

@end

