//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleAppsBigtopSyncClientLoggingDefaultEventLoggingComponent.h"

@class NSString;

@interface ComGoogleAppsBigtopSyncClientLoggingDaggerDefaultEventLoggingComponent : NSObject <ComGoogleAppsBigtopSyncClientLoggingDefaultEventLoggingComponent>
{
    id <JavaxInjectProvider> provideEventStoreProvider_;
    id <JavaxInjectProvider> getEventUploaderStrategyProvider_;
    id <JavaxInjectProvider> provideEventUploaderProvider_;
    id <JavaxInjectProvider> provideBaseHandlerProvider_;
    id <JavaxInjectProvider> setOfFactoryOfAndLogEventContribution1Provider_;
    id <JavaxInjectProvider> setOfFactoryOfAndLogEventContribution2Provider_;
    id <JavaxInjectProvider> setOfFactoryOfAndLogEventContribution3Provider_;
    id <JavaxInjectProvider> setOfFactoryOfAndLogEventProvider_;
    id <JavaxInjectProvider> provideEventStoreProvider1_;
    id <JavaxInjectProvider> getEventUploaderStrategyProvider1_;
    id <JavaxInjectProvider> provideEventUploaderProvider1_;
    id <JavaxInjectProvider> smarteplyEventPipelineProvider_;
    id <JavaxInjectProvider> provideEventPipelinesProvider_;
    id <JavaxInjectProvider> provideLatencyMeasurementsProvider_;
    id <JavaxInjectProvider> createLoggingManagerProvider_;
    id <JavaxInjectProvider> provideEventLoggersProvider_;
    id <JavaxInjectProvider> provideCumulusMessageProducerProvider_;
    id <JavaxInjectProvider> provideEventUploaderFlushableProvider_;
    id <JavaxInjectProvider> provideLoggingExecutorProvider_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)builder;
- (void)dealloc;
- (id)getExecutor;
- (id)getEventUploaderFlushable;
- (id)getLatencyMeasurements;
- (id)getMessageProducer;
- (id)getLoggingManager;
- (id)getEventLoggers;
- (void)initialize__WithComGoogleAppsBigtopSyncClientLoggingDaggerDefaultEventLoggingComponent_Builder:(id)arg1;
- (id)initWithComGoogleAppsBigtopSyncClientLoggingDaggerDefaultEventLoggingComponent_Builder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

