//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "NSObject.h"

@class ComGoogleCumulusCommonAppMessageProto_AppMessage, NSString;

@protocol ComGoogleCumulusApiPluginWorkerAppMessageReceiver <NSObject, JavaObject>
- (void)acceptWithNSString:(NSString *)arg1 withComGoogleCumulusCommonAppMessageProto_AppMessage:(ComGoogleCumulusCommonAppMessageProto_AppMessage *)arg2;
@end

