//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleCommonCacheLocalCache_WeakEntry.h"

@interface ComGoogleCommonCacheLocalCache_WeakAccessEntry : ComGoogleCommonCacheLocalCache_WeakEntry
{
    // Error parsing type: Aq, name: accessTime_
    id <ComGoogleCommonCacheLocalCache_ReferenceEntry> nextAccess_;
    id <ComGoogleCommonCacheLocalCache_ReferenceEntry> previousAccess_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_initWithJavaLangRefReferenceQueue_withId_withInt_withComGoogleCommonCacheLocalCache_ReferenceEntry__params;
- (void)dealloc;
- (void)setPreviousInAccessQueueWithComGoogleCommonCacheLocalCache_ReferenceEntry:(id)arg1;
- (id)getPreviousInAccessQueue;
- (void)setNextInAccessQueueWithComGoogleCommonCacheLocalCache_ReferenceEntry:(id)arg1;
- (id)getNextInAccessQueue;
- (void)setAccessTimeWithLong:(long long)arg1;
- (long long)getAccessTime;
- (id)initWithJavaLangRefReferenceQueue:(id)arg1 withId:(id)arg2 withInt:(int)arg3 withComGoogleCommonCacheLocalCache_ReferenceEntry:(id)arg4;

@end

