//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangRunnable.h"

@class ComGoogleAppsBigtopServicesSettingsBigTopSettings, ComGoogleAppsBigtopSyncClientImplSettingsClientNongwtFileSettingsWriter, NSString;

@interface ComGoogleAppsBigtopSyncClientImplSettingsClientNongwtFileSettingsWriter_$1 : NSObject <JavaLangRunnable>
{
    ComGoogleAppsBigtopSyncClientImplSettingsClientNongwtFileSettingsWriter *this$0_;
    ComGoogleAppsBigtopServicesSettingsBigTopSettings *val$settings_;
    id <JBTICommonSapiCallback> val$callback_;
    id <JBTICommonSapiSpan> val$span_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)initWithComGoogleAppsBigtopSyncClientImplSettingsClientNongwtFileSettingsWriter:(id)arg1 withComGoogleAppsBigtopServicesSettingsBigTopSettings:(id)arg2 withJBTICommonSapiCallback:(id)arg3 withJBTICommonSapiSpan:(id)arg4;
- (void)run;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

