//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@class ComGoogleAppsBigtopDataCommonCommonSyncProtos_SyncProgress;

@protocol ComGoogleAppsBigtopDataItemsItemsProto_SyncResponseOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (ComGoogleAppsBigtopDataCommonCommonSyncProtos_SyncProgress *)getProgress;
- (BOOL)hasProgress;
@end

