//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@class ComGoogleCalendarV2CommonProtoCalendarProto_Event_Attendee_MembershipInfo_Group;

@protocol ComGoogleCalendarV2CommonProtoCalendarProto_Event_Attendee_MembershipInfoOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (ComGoogleCalendarV2CommonProtoCalendarProto_Event_Attendee_MembershipInfo_Group *)getGroupWithInt:(int)arg1;
- (id <JavaUtilList>)getGroupList;
- (int)getGroupCount;
- (BOOL)getInvitedExplicitly;
- (BOOL)hasInvitedExplicitly;
@end

