//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleCumulusCommonIndexAbstractSyncIndexIterator.h"

@interface ComGoogleCumulusSyncClientMemoryObjectStore_IndexedObjectsIterator : ComGoogleCumulusCommonIndexAbstractSyncIndexIterator
{
    id <JavaUtilIterator> iterator_;
}

- (void)dealloc;
- (id)initWithComGoogleCumulusSyncClientMemoryObjectStore:(id)arg1;
- (BOOL)advanceToInternal;
- (id)description;

@end

