//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ComGoogleCommonCollectGenericMapMaker : NSObject
{
    id <ComGoogleCommonCollectMapMaker_RemovalListener> removalListener_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_makeComputingMapWithComGoogleCommonBaseFunction_;
+ (id)__annotations_softValues;
+ (id)__annotations;
- (void)dealloc;
- (id)makeComputingMapWithComGoogleCommonBaseFunction:(id)arg1;
- (id)makeCustomMap;
- (id)makeMap;
- (id)getRemovalListener;
- (id)expireAfterAccessWithLong:(long long)arg1 withJavaUtilConcurrentTimeUnitEnum:(id)arg2;
- (id)expireAfterWriteWithLong:(long long)arg1 withJavaUtilConcurrentTimeUnitEnum:(id)arg2;
- (id)softValues;
- (id)weakValues;
- (id)weakKeys;
- (id)concurrencyLevelWithInt:(int)arg1;
- (id)maximumSizeWithInt:(int)arg1;
- (id)initialCapacityWithInt:(int)arg1;
- (id)keyEquivalenceWithComGoogleCommonBaseEquivalence:(id)arg1;
- (id)init;

@end

