//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleCumulusCommonIndexIndexIterableWithState.h"

@class NSString;

@interface ComGoogleCumulusCommonIndexIndexIterables_$7 : NSObject <ComGoogleCumulusCommonIndexIndexIterableWithState>
{
    id <ComGoogleCumulusCommonIndexIndexIterable> val$limitingTerm_;
    id <ComGoogleCumulusCommonIndexIndexIterableWithState> val$stateTerm_;
}

- (void)dealloc;
- (id)initWithComGoogleCumulusCommonIndexIndexIterable:(id)arg1 withComGoogleCumulusCommonIndexIndexIterableWithState:(id)arg2;
- (id)createIterator;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

