//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleCumulusCommonIndexAbstractSyncIndexIterator.h"

@interface ComGoogleCumulusSyncClientMemoryFieldIndex_FieldIterator : ComGoogleCumulusCommonIndexAbstractSyncIndexIterator
{
    id <JavaUtilIterator> iterator_;
    id <JavaLangComparable> target_;
}

- (void)dealloc;
- (BOOL)advanceToInternal;
- (id)description;
- (id)initWithJavaUtilIterator:(id)arg1 withJavaLangComparable:(id)arg2;

@end

