//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleAppsBigtopSyncClientImplSettingsSettingsWriter.h"

@class NSString;

@interface ComGoogleAppsBigtopSyncClientImplSettingsDefaultSettingsWriter : NSObject <ComGoogleAppsBigtopSyncClientImplSettingsSettingsWriter>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (id)init;
- (void)delete__WithJBTICommonSapiCallback:(id)arg1 withJBTICommonSapiSpan:(id)arg2;
- (void)writeWithComGoogleAppsBigtopServicesSettingsBigTopSettings:(id)arg1 withJBTICommonSapiCallback:(id)arg2 withJBTICommonSapiSpan:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

