//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ComGoogleCumulusCommonAppExtensionProto_AppExtension;

@interface ComGoogleCumulusApiMetricsAppContext : NSObject
{
    id <ComGoogleCumulusApiMetricsSpan> span_;
    ComGoogleCumulusCommonAppExtensionProto_AppExtension *appExtension_;
}

+ (void)initialize;
+ (id)replaceIfNullWithComGoogleCumulusApiMetricsAppContext:(id)arg1;
+ (id)defaultInstance;
- (void)dealloc;
- (id)toIntent;
- (id)getAppExtension;
- (id)getSpanId;
- (id)initWithComGoogleCumulusApiMetricsSpan:(id)arg1 withComGoogleCumulusCommonAppExtensionProto_AppExtension:(id)arg2;

@end

