//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleAppsBigtopDataItemsSyncServiceMissingItemsSyncProtos_ItemsSyncService_ServerInterface.h"

@class ComGoogleAppsBigtopDataItemsSyncServiceCumulusBackfillProtocolHelper, ComGoogleAppsBigtopDataItemsSyncServiceCumulusFetchDetailsProtocolHelper, ComGoogleAppsBigtopDataItemsSyncServiceCumulusSyncProtocolHelper, ComGoogleAppsBigtopDataNetworkSyncServerRequester, NSString;

@interface ComGoogleAppsBigtopDataItemsSyncServiceItemsSyncServiceServer : NSObject <ComGoogleAppsBigtopDataItemsSyncServiceMissingItemsSyncProtos_ItemsSyncService_ServerInterface>
{
    ComGoogleAppsBigtopDataNetworkSyncServerRequester *syncServerRequester_;
    ComGoogleAppsBigtopDataItemsSyncServiceCumulusSyncProtocolHelper *syncProtocolHelper_;
    ComGoogleAppsBigtopDataItemsSyncServiceCumulusBackfillProtocolHelper *backfillProtocolHelper_;
    ComGoogleAppsBigtopDataItemsSyncServiceCumulusFetchDetailsProtocolHelper *fetchDetailsProtocolHelper_;
    id <JavaUtilConcurrentExecutor> executor_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_initWithComGoogleAppsBigtopDataNetworkSyncServerRequester_withComGoogleAppsBigtopDataItemsSyncServiceCumulusSyncProtocolHelper_withComGoogleAppsBigtopDataItemsSyncServiceCumulusBackfillProtocolHelper_withComGoogleAppsBigtopDataItemsSyncServiceCumulusFetchDetailsProtocolHelper_withJavaUtilConcurrentExecutor_;
- (void)dealloc;
- (id)translateSyncViewResponseWithComGoogleCumulusCommonNetProto_Response:(id)arg1;
- (id)syncViewWithComGoogleAppsXplatRpcRpcServerContext:(id)arg1 withComGoogleAppsBigtopDataItemsItemsSyncProtos_ItemsSyncViewRequest:(id)arg2;
- (id)translateFetchDetailsResponseWithJavaUtilMap:(id)arg1 withComGoogleCumulusCommonNetProto_Response:(id)arg2;
- (id)fetchDetailsWithComGoogleAppsXplatRpcRpcServerContext:(id)arg1 withComGoogleAppsBigtopDataItemsItemsSyncProtos_ItemsFetchDetailsRequest:(id)arg2;
- (id)translateSyncResponseWithComGoogleAppsBigtopDataItemsItemsSyncProtos_ItemsSyncRequest:(id)arg1 withComGoogleCumulusCommonNetProto_Response:(id)arg2;
- (id)syncWithComGoogleAppsXplatRpcRpcServerContext:(id)arg1 withComGoogleAppsBigtopDataItemsItemsSyncProtos_ItemsSyncRequest:(id)arg2;
- (id)initWithComGoogleAppsBigtopDataNetworkSyncServerRequester:(id)arg1 withComGoogleAppsBigtopDataItemsSyncServiceCumulusSyncProtocolHelper:(id)arg2 withComGoogleAppsBigtopDataItemsSyncServiceCumulusBackfillProtocolHelper:(id)arg3 withComGoogleAppsBigtopDataItemsSyncServiceCumulusFetchDetailsProtocolHelper:(id)arg4 withJavaUtilConcurrentExecutor:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

