//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "NSObject.h"

@protocol ComGoogleCumulusCommonIndexIdbAdapter_Index <NSObject, JavaObject>
- (id <ComGoogleCumulusCommonIndexIdbAdapter_Request>)openKeyCursorWithComGoogleCumulusCommonIndexIdbAdapter_KeyRange:(id <ComGoogleCumulusCommonIndexIdbAdapter_KeyRange>)arg1;
- (id <ComGoogleCumulusCommonIndexIdbAdapter_Request>)openCursorWithComGoogleCumulusCommonIndexIdbAdapter_KeyRange:(id <ComGoogleCumulusCommonIndexIdbAdapter_KeyRange>)arg1;
@end

