//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JCGCuWorkUtil_CancellableRunnable.h"

@class ComGoogleCumulusQueryClientWorkerQueryManager_WorkerQueryDispatcherCallback, ComGoogleCumulusQueryQueryProto_Query;

@interface ComGoogleCumulusQueryClientWorkerQueryManager_WorkerQueryDispatcherCallback_$1 : JCGCuWorkUtil_CancellableRunnable
{
    ComGoogleCumulusQueryClientWorkerQueryManager_WorkerQueryDispatcherCallback *this$0_;
    ComGoogleCumulusQueryQueryProto_Query *val$finalQuery_;
}

- (void)dealloc;
- (id)initWithComGoogleCumulusQueryClientWorkerQueryManager_WorkerQueryDispatcherCallback:(id)arg1 withComGoogleCumulusQueryQueryProto_Query:(id)arg2;
- (void)run;

@end

