//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleCommonCacheLocalCache_ValueReference.h"

@class ComGoogleCommonBaseStopwatch, ComGoogleCommonUtilConcurrentSettableFuture, NSString;

@interface ComGoogleCommonCacheLocalCache_LoadingValueReference : NSObject <ComGoogleCommonCacheLocalCache_ValueReference>
{
    // Error parsing type: A^v, name: oldValue_
    ComGoogleCommonUtilConcurrentSettableFuture *futureValue_;
    ComGoogleCommonBaseStopwatch *stopwatch_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_copyForWithJavaLangRefReferenceQueue_withId_withComGoogleCommonCacheLocalCache_ReferenceEntry__params;
+ (id)__annotations_notifyNewValueWithId__params;
+ (id)__annotations_setWithId__params;
- (void)__javaClone;
- (void)dealloc;
- (id)copyForWithJavaLangRefReferenceQueue:(id)arg1 withId:(id)arg2 withComGoogleCommonCacheLocalCache_ReferenceEntry:(id)arg3;
- (id)getEntry;
- (id)getOldValue;
- (id)get;
- (id)waitForValue;
- (long long)elapsedNanos;
- (id)loadFutureWithId:(id)arg1 withComGoogleCommonCacheCacheLoader:(id)arg2;
- (void)notifyNewValueWithId:(id)arg1;
- (id)fullyFailedFutureWithJavaLangThrowable:(id)arg1;
- (BOOL)setExceptionWithJavaLangThrowable:(id)arg1;
- (BOOL)setWithId:(id)arg1;
- (int)getWeight;
- (BOOL)isActive;
- (BOOL)isLoading;
- (id)initWithComGoogleCommonCacheLocalCache_ValueReference:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

