//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@class ComGoogleAppsBigtopDataContactsContactsProto_AutocompleteContactsRequest_RequestStrategyEnum, NSString;

@protocol ComGoogleAppsBigtopDataContactsContactsProto_AutocompleteContactsRequestOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (ComGoogleAppsBigtopDataContactsContactsProto_AutocompleteContactsRequest_RequestStrategyEnum *)getStrategy;
- (BOOL)hasStrategy;
- (int)getMaxResults;
- (BOOL)hasMaxResults;
- (NSString *)getPrefixWithInt:(int)arg1;
- (id <ComGoogleProtobufProtocolStringList>)getPrefixList;
- (int)getPrefixCount;
@end

