//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JBTCGenericQueryConverter.h"

@interface ComGoogleAppsBigtopServicesGmailGmailQueryConverter : JBTCGenericQueryConverter
{
    BOOL clientInstance_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_NO_UPPER_BOUND_;
+ (id)__annotations_NO_LOWER_BOUND_;
+ (id)__annotations_initWithComGoogleAppsBigtopSyncQueryQueryParser_withComGoogleAppsBigtopSyncQueryUserData_withComGoogleAppsBigtopSyncQueryTreeNodePredicateConverter_;
+ (id)__annotations;
+ (void)initialize;
+ (id)getQueryParserStages;
+ (id)newPredicateConverter;
+ (id)newQueryParser;
- (id)toPredicateWithComGoogleCumulusQueryQueryProto_Query:(id)arg1;
- (id)initWithComGoogleAppsBigtopSyncQueryUserData:(id)arg1;
- (id)initWithComGoogleAppsBigtopSyncQueryQueryParser:(id)arg1 withComGoogleAppsBigtopSyncQueryUserData:(id)arg2 withComGoogleAppsBigtopSyncQueryTreeNodePredicateConverter:(id)arg3;

@end

