//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "NSObject.h"

@class ComGoogleAppsXplatSqlSqlColumnConstraint_ForeignKey, ComGoogleAppsXplatSqlSqlColumnConstraint_PrimaryKey;

@protocol ComGoogleAppsXplatSqlSqlColumnConstraintVisitor <NSObject, JavaObject>
- (id)visitWithComGoogleAppsXplatSqlSqlColumnConstraint_PrimaryKey:(ComGoogleAppsXplatSqlSqlColumnConstraint_PrimaryKey *)arg1;
- (id)visitWithComGoogleAppsXplatSqlSqlColumnConstraint_ForeignKey:(ComGoogleAppsXplatSqlSqlColumnConstraint_ForeignKey *)arg1;
@end

