//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JavaLangInteger;

@interface ComGoogleCumulusSyncClientMutationDetail : NSObject
{
    JavaLangInteger *pendingPriority_;
    JavaLangInteger *mutationOrder_;
}

- (void)dealloc;
- (id)getMutationOrder;
- (id)getPendingPriority;
- (id)initWithJavaLangInteger:(id)arg1 withJavaLangInteger:(id)arg2;

@end

