//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JBTCDefaultLocalResultHelper.h"

@interface ComGoogleAppsBigtopServicesLocationaliasesCommonLocationAliasesLocalResultHelper : JBTCDefaultLocalResultHelper
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (id)init;
- (id)getSnippetWithComGoogleCumulusApiTypeObjectId:(id)arg1 withComGoogleCumulusTypeTypeProto_BaseObject:(id)arg2 withComGoogleCumulusQueryQueryProto_Query:(id)arg3;
- (id)getRankWithComGoogleCumulusApiTypeObjectId:(id)arg1 withComGoogleCumulusTypeTypeProto_BaseObject:(id)arg2 withComGoogleCumulusQueryQueryProto_Query:(id)arg3;

@end

