//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleCumulusCommonUtilStringFormatter_BaseFormatter.h"

@interface ComGoogleCumulusCommonBaseProtoUtil_$1 : ComGoogleCumulusCommonUtilStringFormatter_BaseFormatter
{
}

- (id)initWithIOSClass:(id)arg1;
- (void)formatWithComGoogleCumulusCommonUtilStringFormatter:(id)arg1 withId:(id)arg2;

@end

