//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufGeneratedMessage_Builder.h"

#import "ComGooglePersonalizationAssistAnnotateApiCallActionOrBuilder.h"

@class NSString;

@interface ComGooglePersonalizationAssistAnnotateApiCallAction_Builder : ComGoogleProtobufGeneratedMessage_Builder <ComGooglePersonalizationAssistAnnotateApiCallActionOrBuilder>
{
}

+ (id)getDescriptor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

