//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleAppsBigtopSyncQueryTreeNodeTreeTraverser.h"

@class ComGoogleAppsBigtopServicesGmailQueryLabelNameToIdConverter, ComGoogleAppsBigtopSyncQueryParseContext;

@interface ComGoogleAppsBigtopServicesGmailQueryLabelNameToIdConverter_$1 : ComGoogleAppsBigtopSyncQueryTreeNodeTreeTraverser
{
    ComGoogleAppsBigtopServicesGmailQueryLabelNameToIdConverter *this$0_;
    ComGoogleAppsBigtopSyncQueryParseContext *val$ctx_;
    id <ComGoogleAppsBigtopSyncQueryUserData> val$userData_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)initWithComGoogleAppsBigtopServicesGmailQueryLabelNameToIdConverter:(id)arg1 withComGoogleAppsBigtopSyncQueryParseContext:(id)arg2 withComGoogleAppsBigtopSyncQueryUserData:(id)arg3;
- (id)onFieldEqualsNodeWithComGoogleAppsBigtopSyncQueryNodesFieldEqualsNode:(id)arg1;

@end

