//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@protocol ComGoogleCalendarV2CommonProtoCalendarProto_EventMetadataOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (long long)getRangeEndMs;
- (BOOL)hasRangeEndMs;
- (long long)getRangeStartMs;
- (BOOL)hasRangeStartMs;
- (long long)getInstanceStartMsWithInt:(int)arg1;
- (id <JavaUtilList>)getInstanceStartMsList;
- (int)getInstanceStartMsCount;
@end

