//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangRunnable.h"

@class ComGoogleCumulusSyncClientIdbIdbIndexProcessor, ComGoogleCumulusSyncClientIdbIdbIndexProcessor_BucketIndexingWaiter, ComGoogleCumulusSyncClientIdbIdbIndexProcessor_BucketTrancheList, NSString;

@interface ComGoogleCumulusSyncClientIdbIdbIndexProcessor_$10 : NSObject <JavaLangRunnable>
{
    ComGoogleCumulusSyncClientIdbIdbIndexProcessor *this$0_;
    int val$startTimeRelative_;
    ComGoogleCumulusSyncClientIdbIdbIndexProcessor_BucketTrancheList *val$trancheList_;
    ComGoogleCumulusSyncClientIdbIdbIndexProcessor_BucketIndexingWaiter *val$waiter_;
    int val$waiterVersion_;
}

- (void)dealloc;
- (id)initWithComGoogleCumulusSyncClientIdbIdbIndexProcessor:(id)arg1 withInt:(int)arg2 withComGoogleCumulusSyncClientIdbIdbIndexProcessor_BucketTrancheList:(id)arg3 withComGoogleCumulusSyncClientIdbIdbIndexProcessor_BucketIndexingWaiter:(id)arg4 withInt:(int)arg5;
- (void)run;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

