//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleCommonBaseSplitter_Strategy.h"

@class ComGoogleCommonBaseCharMatcher, NSString;

@interface ComGoogleCommonBaseSplitter_$1 : NSObject <ComGoogleCommonBaseSplitter_Strategy>
{
    ComGoogleCommonBaseCharMatcher *val$separatorMatcher_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)initWithComGoogleCommonBaseCharMatcher:(id)arg1;
- (id)iteratorWithComGoogleCommonBaseSplitter:(id)arg1 withJavaLangCharSequence:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

