//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ComGoogleCumulusCommonIndexIndexIterables : NSObject
{
}

+ (id)ofWithComGoogleCumulusCommonIndexIndexIterator:(id)arg1;
+ (id)rankRestrictWithComGoogleCumulusCommonIndexIndexIterable:(id)arg1 withJavaLangInteger:(id)arg2 withJavaLangInteger:(id)arg3;
+ (id)andWithStateWithComGoogleCumulusCommonIndexIndexIterable:(id)arg1 withComGoogleCumulusCommonIndexIndexIterableWithState:(id)arg2;
+ (id)phraseWithJavaUtilList:(id)arg1;
+ (id)concatWithJavaUtilList:(id)arg1;
+ (id)andNotWithComGoogleCumulusCommonIndexIndexIterable:(id)arg1 withComGoogleCumulusCommonIndexIndexIterable:(id)arg2;
+ (id)or__WithJavaUtilList:(id)arg1;
+ (id)prioritizedAndWithJavaUtilList:(id)arg1;
+ (id)and__WithComGoogleCumulusCommonIndexIndexIterableArray:(id)arg1;
+ (id)and__WithJavaUtilList:(id)arg1;
- (id)init;

@end

