//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleCommonCollectMultisets_EntrySet.h"

@class ComGoogleCommonCollectMultimaps_Keys;

@interface ComGoogleCommonCollectMultimaps_Keys_KeysEntrySet : ComGoogleCommonCollectMultisets_EntrySet
{
    ComGoogleCommonCollectMultimaps_Keys *this$0_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_removeWithId__params;
+ (id)__annotations_containsWithId__params;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (void)__javaClone;
- (id)initWithComGoogleCommonCollectMultimaps_Keys:(id)arg1;
- (BOOL)removeWithId:(id)arg1;
- (BOOL)containsWithId:(id)arg1;
- (BOOL)isEmpty;
- (int)size;
- (id)iterator;
- (id)multiset;

@end

