//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleCommonCollectMultimap.h"
#import "JavaObject.h"
#import "NSObject.h"

@protocol ComGoogleCommonCollectListMultimap <ComGoogleCommonCollectMultimap, NSObject, JavaObject>
- (BOOL)isEqual:(id)arg1;
- (id <JavaUtilMap>)asMap;
- (id <JavaUtilList>)replaceValuesWithId:(id)arg1 withJavaLangIterable:(id <JavaLangIterable>)arg2;
- (id <JavaUtilList>)removeAllWithId:(id)arg1;
- (id <JavaUtilList>)getWithId:(id)arg1;
@end

