//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@class ComGoogleAppsBigtopServicesSmartmailSmartMailMetricsProto_SmartMailViewTypeAggregate, NSString;

@protocol ComGoogleAppsBigtopServicesSmartmailSmartMailMetricsProto_SmartMailViewDomainAggregateOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (ComGoogleAppsBigtopServicesSmartmailSmartMailMetricsProto_SmartMailViewTypeAggregate *)getTypeViewWithInt:(int)arg1;
- (id <JavaUtilList>)getTypeViewList;
- (int)getTypeViewCount;
- (NSString *)getSenderDomain;
- (BOOL)hasSenderDomain;
@end

