//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleAppsXplatTracingTracingApi.h"

@class NSString;

@interface ComGoogleAppsXplatTracingNoOpTracingApi : NSObject <ComGoogleAppsXplatTracingTracingApi>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)getInstance;
- (BOOL)isEnabled;
- (id)beginLink;
- (void)instantWithNSString:(id)arg1 withComGoogleAppsXplatTracingInstantScopeEnum:(id)arg2;
- (void)instantWithNSString:(id)arg1;
- (id)beginAsyncWithNSString:(id)arg1;
- (id)beginWithNSString:(id)arg1 withJavaUtilList:(id)arg2;
- (id)beginWithNSString:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

