//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleCumulusApiTypeObjectReader.h"

@class ComGoogleCumulusFrameworkStoreProto_StoredObject, ComGoogleCumulusTypeTypeProto_Command, NSString;

@interface ComGoogleCumulusSyncClientIdbIdbObjectStore_StoredObjectReader : NSObject <ComGoogleCumulusApiTypeObjectReader>
{
    NSString *soid_;
    ComGoogleCumulusFrameworkStoreProto_StoredObject *storedObject_;
    BOOL useSlicedState_;
    ComGoogleCumulusTypeTypeProto_Command *slicedState_;
    id <JavaUtilCollection> slicedSliceIds_;
    id <JavaUtilCollection> storedSliceIds_;
}

- (void)dealloc;
- (id)getSlicedObjectReaderWithComGoogleCumulusApiPluginSlicer:(id)arg1 withJavaUtilSet:(id)arg2;
@property(readonly, copy) NSString *description;
- (id)getSubscriptions;
- (id)getPending;
- (id)getState;
- (id)getSequenceId;
- (int)getInflightCount;
- (id)getStoredSlices;
- (id)getSliceIds;
- (id)getVersion;
- (id)getSoid;
- (id)initWithComGoogleCumulusSyncClientIdbIdbObjectStore_StoredObjectReader:(id)arg1 withComGoogleCumulusTypeTypeProto_Command:(id)arg2 withComGoogleCumulusCommonCollectImmutableSet:(id)arg3;
- (id)initWithNSString:(id)arg1 withComGoogleCumulusFrameworkStoreProto_StoredObject:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

