//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleAppsBigtopServicesGmailSerialExecutor_SerialRunnable.h"

@class ComGoogleAppsBigtopServicesGmailClusterThrottlingHelper, ComGoogleCumulusQueryQueryProto_Query, JBTCGmailThreadRankComparator;

@interface ComGoogleAppsBigtopServicesGmailClusterBackfill : ComGoogleAppsBigtopServicesGmailSerialExecutor_SerialRunnable
{
    ComGoogleAppsBigtopServicesGmailClusterThrottlingHelper *clusterThrottlingHelper_;
    JBTCGmailThreadRankComparator *threadRankComparator_;
    id <ComGoogleCumulusApiTypeObjectIndex> index_;
    ComGoogleCumulusQueryQueryProto_Query *query_;
    id <ComGoogleCumulusCommonIndexIndexIterable> rootIterable_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)createAccumulatorForClusterQueryWithComGoogleAppsBigtopServicesGmailClusterThrottlingHelper:(id)arg1 withComGoogleCumulusApiTypeObjectIndex:(id)arg2 withComGoogleCumulusCommonIndexIndexIterable:(id)arg3 withComGoogleCumulusApiPluginMultiPassQueryRunner_Accumulator:(id)arg4 withComGoogleAppsBigtopServicesGmailClusterCache:(id)arg5 withNSString:(id)arg6;
+ (BOOL)canThreadBelongToClusterWithComGoogleCumulusTypeTypeProto_BaseObject:(id)arg1 withJavaUtilSet:(id)arg2;
- (void)dealloc;
- (id)createBackfillRunnableWithComGoogleAppsBigtopServicesGmailSerialExecutor_RunnableContext:(id)arg1 withComGoogleAppsBigtopServicesGmailLocalQueryResultBuilder_SegmentInfoBuilder:(id)arg2 withComGoogleCumulusApiPluginMultiPassQueryRunner_Accumulator:(id)arg3 withJavaUtilConcurrentAtomicAtomicInteger:(id)arg4 withComGoogleAppsBigtopServicesGmailClusterCache:(id)arg5;
- (void)runWithComGoogleAppsBigtopServicesGmailSerialExecutor_RunnableContext:(id)arg1;
- (id)initWithComGoogleAppsBigtopServicesGmailClusterThrottlingHelper:(id)arg1 withComGoogleCumulusApiTypeObjectIndex:(id)arg2 withComGoogleCumulusQueryQueryProto_Query:(id)arg3 withComGoogleCumulusCommonIndexIndexIterable:(id)arg4;

@end

