//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleCumulusSyncClientIdbIdbObjectStore_IndexWaiter.h"

@class ComGoogleCumulusCommonIndexFieldSpec, ComGoogleCumulusSyncClientIdbIdbObjectStore, NSString;

@interface ComGoogleCumulusSyncClientIdbIdbObjectStore_$28 : ComGoogleCumulusSyncClientIdbIdbObjectStore_IndexWaiter
{
    ComGoogleCumulusSyncClientIdbIdbObjectStore *this$0_;
    NSString *val$prefix_;
    ComGoogleCumulusCommonIndexFieldSpec *val$fieldSpec_;
    NSString *val$ftsField_;
    BOOL val$positionsEnabled_;
}

- (void)dealloc;
- (id)initWithComGoogleCumulusSyncClientIdbIdbObjectStore:(id)arg1 withNSString:(id)arg2 withComGoogleCumulusCommonIndexFieldSpec:(id)arg3 withNSString:(id)arg4 withBoolean:(BOOL)arg5 withComGoogleCumulusSyncClientIdbIdbIndexProcessor:(id)arg6 withNSString:(id)arg7 withInt:(int)arg8 withBoolean:(BOOL)arg9 withBoolean:(BOOL)arg10;
- (id)createIterable;

@end

