//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ComGoogleCumulusApiPluginClientActionRequest;

@interface ComGoogleCumulusApiPluginClientActionRequest_Builder : NSObject
{
    BOOL built_;
    ComGoogleCumulusApiPluginClientActionRequest *this$0_;
}

- (void)dealloc;
- (id)initWithComGoogleCumulusApiPluginClientActionRequest:(id)arg1;
- (id)build;
- (id)addQueryKeysWithJavaUtilCollection:(id)arg1;
- (id)addQueryKeyWithComGoogleCumulusQueryQueryProto_QueryKey:(id)arg1;
- (id)setClientActionWithComGoogleCumulusSyncSyncProto_ClientActionEnum:(id)arg1;
- (id)setTypeIdWithNSString:(id)arg1;
- (id)mergeFromWithComGoogleCumulusApiPluginClientActionRequest:(id)arg1;
- (id)setErrorWithComGoogleCumulusSyncSyncProto_Error:(id)arg1;

@end

