//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaLangEnum.h"

#import "NSCopying.h"

@interface ComGoogleProtobufDescriptors_FieldDescriptor_JavaTypeEnum : JavaLangEnum <NSCopying>
{
    id defaultDefault_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)valueOfWithNSString:(id)arg1;
+ (id)values;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithId:(id)arg1 withNSString:(id)arg2 withInt:(int)arg3;

@end

