//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ComGoogleCumulusCommonConfigConfiguration_Builder_Registration : NSObject
{
    id defaultComponent_;
    id primaryComponent_;
    id <ComGoogleCumulusCommonConfigConfiguration_AdapterFactory> adapter_;
}

- (void)dealloc;
- (id)init;
- (id)getAdapter;
- (void)setAdapterWithComGoogleCumulusCommonConfigConfiguration_AdapterFactory:(id)arg1;
- (BOOL)hasAdapter;
- (id)getPrimary;
- (void)setPrimaryWithId:(id)arg1;
- (BOOL)hasPrimary;
- (id)getDefault;
- (void)setDefaultWithId:(id)arg1;
- (BOOL)hasDefault;

@end

