//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@protocol ComGoogleCumulusFrameworkStoreProto_StoreStateOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (BOOL)getNeedsSaveMutation;
- (BOOL)hasNeedsSaveMutation;
- (BOOL)getNeedsDestroy;
- (BOOL)hasNeedsDestroy;
@end

