//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleAppsBigtopSyncQueryTreeNodeTreeTraverser.h"

@class ComGoogleAppsBigtopSyncQueryParseConfiguration;

@interface ComGoogleAppsBigtopSyncQueryExpandersDefaultFieldConverter_$1 : ComGoogleAppsBigtopSyncQueryTreeNodeTreeTraverser
{
    ComGoogleAppsBigtopSyncQueryParseConfiguration *val$config_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)initWithComGoogleAppsBigtopSyncQueryParseConfiguration:(id)arg1;
- (id)onPhraseNodeWithComGoogleAppsBigtopSyncQueryNodesPhraseNode:(id)arg1;
- (id)onOpenTermNodeWithComGoogleAppsBigtopSyncQueryNodesOpenTermNode:(id)arg1;
- (id)onOpenPhraseNodeWithComGoogleAppsBigtopSyncQueryNodesOpenPhraseNode:(id)arg1;
- (id)onTermNodeWithComGoogleAppsBigtopSyncQueryNodesTermNode:(id)arg1;
- (id)onFieldEqualsNodeWithComGoogleAppsBigtopSyncQueryNodesFieldEqualsNode:(id)arg1;

@end

