//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel;

@interface ContactPopupTableViewCell : UITableViewCell
{
    UILabel *kindLabel_;
    UIImageView *primaryIcon_;
    UIButton *secondaryIcon_;
    UILabel *refLabel_;
    id <JBTContactReference> contactReference_;
}

+ (float)labelHeightForContactReference:(id)arg1 forWidth:(float)arg2;
+ (float)heightForContactReference:(id)arg1 width:(float)arg2;
@property(retain, nonatomic) id <JBTContactReference> contactReference; // @synthesize contactReference=contactReference_;
- (void).cxx_destruct;
- (void)secondaryIconTapped;
- (void)createSubviews;
@property(nonatomic) BOOL firstRowOfType;
- (void)layoutSubviews;
- (id)init;

@end

