//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilLoggingHandler.h"

@class GTMLogger, NSSet;

@interface GBTJavaLogHandler : JavaUtilLoggingHandler
{
    GTMLogger *gtmLogger_;
    NSSet *_loggerNamesToIgnore;
}

@property(retain, nonatomic) NSSet *loggerNamesToIgnore; // @synthesize loggerNamesToIgnore=_loggerNamesToIgnore;
@property(retain, nonatomic) GTMLogger *gtmLogger; // @synthesize gtmLogger=gtmLogger_;
- (void).cxx_destruct;
- (void)logWithJavaUtilLoggingLogRecord:(id)arg1;
- (void)publishWithJavaUtilLoggingLogRecord:(id)arg1;
- (void)flush;
- (void)close;
- (id)initWithLogger:(id)arg1;

@end

