//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GTMLogBasicFormatter.h"

@class NSString;

@interface GBTLogStandardFormatter : GTMLogBasicFormatter
{
    const char *formatString_;
    NSString *pname_;
    int pid_;
}

- (void).cxx_destruct;
- (id)stringForFunc:(id)arg1 withFormat:(id)arg2 valist:(void *)arg3 level:(int)arg4;
- (id)init;

@end

