//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QLPreviewItem.h"

@class NSString, NSURL;

@interface GBTPreviewItem : NSObject <QLPreviewItem>
{
    NSURL *_previewItemURL;
    id <JBTMessageAttachment> _attachmentData;
}

@property(retain, nonatomic) id <JBTMessageAttachment> attachmentData; // @synthesize attachmentData=_attachmentData;
@property(retain) NSURL *previewItemURL; // @synthesize previewItemURL=_previewItemURL;
- (void).cxx_destruct;
@property(readonly) NSString *previewItemTitle;
- (BOOL)isEqual:(id)arg1;
- (id)initWithAttachment:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

