//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class GOOSideViewBackgroundContainerView, GOOSideViewChevronButton, NSArray, NSMutableDictionary, NSSet, NSString, UIPanGestureRecognizer;

@interface GOOSideViewCarouselView : UIView <UIGestureRecognizerDelegate>
{
    GOOSideViewBackgroundContainerView *_backgroundView;
    float _backgroundViewportHeight;
    float _backgroundViewportOutset;
    struct CGRect _lastBounds;
    NSArray *_profiles;
    int _selectedProfileIndex;
    NSMutableDictionary *_carouselItemsByLocation;
    int _panningDirection;
    float _panningTrackDistance;
    UIPanGestureRecognizer *_panRecognizer;
    NSSet *_panTransitions;
    float _lastPanTween;
    GOOSideViewChevronButton *_chevronButton;
    UIView *_carouselAccessibilityView;
    NSArray *_accessibilityViews;
    id <GOOSideViewProfileDataSource> _dataSource;
    id <GOOSideViewCarouselViewDelegate> _delegate;
    int _viewMode;
    id <GOOSideViewProfile> _selectedProfile;
}

@property(retain, nonatomic) id <GOOSideViewProfile> selectedProfile; // @synthesize selectedProfile=_selectedProfile;
@property(nonatomic) int viewMode; // @synthesize viewMode=_viewMode;
@property(nonatomic) __weak id <GOOSideViewCarouselViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <GOOSideViewProfileDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)avatarTouched:(id)arg1;
- (void)updateProfileCount;
- (BOOL)locationShouldReceiveAccessibilityFocus:(int)arg1;
- (BOOL)itemShouldBeHidden:(id)arg1;
- (BOOL)itemShouldBeEnabled:(id)arg1;
- (void)performTransitions:(id)arg1 complete:(BOOL)arg2 shouldSelect:(BOOL)arg3 shouldNotify:(BOOL)arg4 duration:(double)arg5;
- (void)internalSetSelectedProfile:(id)arg1 notifyDelegate:(BOOL)arg2;
- (void)animateTransitionToProfile:(id)arg1 shouldNotify:(BOOL)arg2;
- (id)transitionsWithShift:(int)arg1;
- (void)removeNonVisibleCarouselItems;
- (void)updateNonVisibleCarouselItems;
- (void)updateVisibleCarouselItems;
- (id)generateItemForProfileIndex:(int)arg1;
- (id)carouselItemForLocation:(int)arg1;
- (int)profileIndexForLocation:(int)arg1;
- (int)profileIndexForProfile:(id)arg1;
- (void)chevronTouched;
- (void)handlePanComplete:(BOOL)arg1;
- (void)handlePanCancelled:(id)arg1;
- (void)handlePanEnded:(id)arg1;
- (void)handlePanChange:(id)arg1;
- (void)handlePanBegan:(id)arg1;
- (void)handlePan:(id)arg1;
- (BOOL)isPanning;
- (int)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(int)arg1;
- (int)accessibilityElementCount;
- (id)accessibilityLabelForProfile:(id)arg1;
- (void)updateAccessibilityElements;
- (BOOL)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)layoutSubviews;
- (void)reloadProfile:(id)arg1;
- (void)removeAllCarouselItemsFromSuperviews;
- (void)reloadData;
- (void)setBackgroundViewportHeight:(float)arg1 outset:(float)arg2;
- (void)setSelectedProfile:(id)arg1 animated:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

