//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"
#import "JavaLangReflectAnnotatedElement.h"
#import "JavaLangReflectGenericDeclaration.h"
#import "JavaLangReflectType.h"
#import "NSCopying.h"

@class NSString, Protocol;

@interface IOSClass : NSObject <JavaLangReflectAnnotatedElement, JavaLangReflectGenericDeclaration, JavaIoSerializable, JavaLangReflectType, NSCopying>
{
}

+ (struct J2ObjcClassInfo *)__metadata;
+ (long long)serialVersionUID;
+ (void)initialize;
+ (id)forName:(id)arg1 initialize:(BOOL)arg2 classLoader:(id)arg3;
+ (id)forName:(id)arg1;
+ (id)primitiveClassForChar:(unsigned short)arg1;
+ (id)classForIosName:(id)arg1;
+ (id)voidClass;
+ (id)booleanClass;
+ (id)shortClass;
+ (id)longClass;
+ (id)intClass;
+ (id)floatClass;
+ (id)doubleClass;
+ (id)charClass;
+ (id)byteClass;
- (id)getClass;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)__convertRawValue:(CDUnion_a5829cf6 *)arg1 toType:(id)arg2;
- (void)__writeRawValue:(CDUnion_a5829cf6 *)arg1 toAddress:(const void *)arg2;
- (void)__readRawValue:(CDUnion_a5829cf6 *)arg1 fromAddress:(const void *)arg2;
- (BOOL)__unboxValue:(id)arg1 toRawValue:(CDUnion_a5829cf6 *)arg2;
- (id)__boxValue:(CDUnion_a5829cf6 *)arg1;
- (id)getSigners;
- (id)getProtectionDomain;
- (id)getResourceAsStream:(id)arg1;
- (id)getResource:(id)arg1;
- (unsigned long)getSizeof;
- (Class)objcArrayClass;
- (id)getEnumConstants;
- (BOOL)desiredAssertionStatus;
- (BOOL)isAnonymousClass;
- (id)getDeclaredClasses;
- (id)getClasses;
- (id)getEnclosingConstructor;
- (id)getEnclosingMethod;
- (id)getFields;
- (id)getDeclaredFields;
- (id)getField:(id)arg1;
- (id)getDeclaredField:(id)arg1;
- (id)getClassLoader;
- (id)getPackage;
- (id)getMetadata;
- (id)getDeclaredAnnotations;
- (id)getAnnotations;
- (BOOL)isAnnotationPresentWithIOSClass:(id)arg1;
- (id)getAnnotationWithIOSClass:(id)arg1;
- (id)getTypeParameters;
- (id)getGenericInterfaces;
- (id)getInterfaces;
- (id)getInterfacesInternal;
- (BOOL)isSynthetic;
- (BOOL)isLocalClass;
- (BOOL)isMemberClass;
- (BOOL)isAnnotation;
- (BOOL)isPrimitive;
- (BOOL)isInterface;
- (BOOL)isEnum;
- (BOOL)isArray;
- (id)getEnclosingClass;
- (id)cast:(id)arg1;
- (id)binaryName;
@property(readonly, copy) NSString *description;
- (id)asSubclass:(id)arg1;
- (BOOL)isAssignableFrom:(id)arg1;
- (id)getDeclaredConstructor:(id)arg1;
- (id)getConstructor:(id)arg1;
- (id)getComponentType;
- (id)findConstructorWithTranslatedName:(id)arg1;
- (id)findMethodWithTranslatedName:(id)arg1 checkSupertypes:(BOOL)arg2;
- (id)getDeclaredMethod:(id)arg1 parameterTypes:(id)arg2;
- (id)getMethod:(id)arg1 parameterTypes:(id)arg2;
- (id)getConstructors;
- (id)getMethods;
- (id)getDeclaredConstructors;
- (id)getDeclaredMethods;
- (void)collectMethods:(id)arg1 publicOnly:(BOOL)arg2;
- (int)getModifiers;
- (id)objcName;
- (id)getCanonicalName;
- (id)getSimpleName;
- (id)getName;
- (BOOL)isInstance:(id)arg1;
- (id)getDeclaringClass;
- (id)getGenericSuperclass;
- (id)getSuperclass;
- (id)newInstance;
@property(readonly) Protocol *objcProtocol;
@property(readonly) Class objcClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

