//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaLangRefReference.h"

@interface JavaLangRefWeakReference : JavaLangRefReference
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (id)initWithId:(id)arg1 withJavaLangRefReferenceQueue:(id)arg2;
- (id)initWithId:(id)arg1;

@end

