//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"
#import "JavaUtilConcurrentLocksLock.h"

@class JavaUtilConcurrentLocksReentrantReadWriteLock_Sync, NSString;

@interface JavaUtilConcurrentLocksReentrantReadWriteLock_ReadLock : NSObject <JavaUtilConcurrentLocksLock, JavaIoSerializable>
{
    JavaUtilConcurrentLocksReentrantReadWriteLock_Sync *sync_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)newCondition;
- (void)unlock;
- (BOOL)tryLockWithLong:(long long)arg1 withJavaUtilConcurrentTimeUnitEnum:(id)arg2;
- (BOOL)tryLock;
- (void)lockInterruptibly;
- (void)lock;
- (id)initWithJavaUtilConcurrentLocksReentrantReadWriteLock:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

