//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaIoFilterOutputStream.h"

@class IOSByteArray, JavaUtilZipInflater;

@interface JavaUtilZipInflaterOutputStream : JavaIoFilterOutputStream
{
    JavaUtilZipInflater *inf_;
    IOSByteArray *buf_;
    BOOL closed_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (void)checkClosed;
- (void)write;
- (void)writeWithByteArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (void)writeWithInt:(int)arg1;
- (void)finish;
- (void)flush;
- (void)close;
- (id)initWithJavaIoOutputStream:(id)arg1 withJavaUtilZipInflater:(id)arg2 withInt:(int)arg3;
- (id)initWithJavaIoOutputStream:(id)arg1 withJavaUtilZipInflater:(id)arg2;
- (id)initWithJavaIoOutputStream:(id)arg1;

@end

