//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaIoInputStream.h"

@class NSString;

@interface JavaIoStringBufferInputStream : JavaIoInputStream
{
    NSString *buffer_;
    int count_;
    int pos_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations;
- (void)dealloc;
- (long long)skipWithLong:(long long)arg1;
- (void)reset;
- (int)readWithByteArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (int)read;
- (int)available;
- (id)initWithNSString:(id)arg1;

@end

