//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilConcurrentConcurrentLinkedDeque_AbstractItr.h"

@class JavaUtilConcurrentConcurrentLinkedDeque;

@interface JavaUtilConcurrentConcurrentLinkedDeque_Itr : JavaUtilConcurrentConcurrentLinkedDeque_AbstractItr
{
    JavaUtilConcurrentConcurrentLinkedDeque *this$1_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)initWithJavaUtilConcurrentConcurrentLinkedDeque:(id)arg1;
- (id)nextNodeWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1;
- (id)startNode;

@end

