//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "JavaTextCharacterIterator.h"
#import "NSObject.h"

@class JavaTextAttributedCharacterIterator_Attribute;

@protocol JavaTextAttributedCharacterIterator <JavaTextCharacterIterator, NSObject, JavaObject>
- (int)getRunStartWithJavaUtilSet:(id <JavaUtilSet>)arg1;
- (int)getRunStartWithJavaTextAttributedCharacterIterator_Attribute:(JavaTextAttributedCharacterIterator_Attribute *)arg1;
- (int)getRunStart;
- (int)getRunLimitWithJavaUtilSet:(id <JavaUtilSet>)arg1;
- (int)getRunLimitWithJavaTextAttributedCharacterIterator_Attribute:(JavaTextAttributedCharacterIterator_Attribute *)arg1;
- (int)getRunLimit;
- (id <JavaUtilMap>)getAttributes;
- (id)getAttributeWithJavaTextAttributedCharacterIterator_Attribute:(JavaTextAttributedCharacterIterator_Attribute *)arg1;
- (id <JavaUtilSet>)getAllAttributeKeys;
@end

