//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JavaNetAuthenticator_RequestorTypeEnum, JavaNetInetAddress, JavaNetURL, NSString;

@interface JavaNetAuthenticator : NSObject
{
    NSString *host_;
    JavaNetInetAddress *addr_;
    int port_;
    NSString *protocol_;
    NSString *prompt_;
    NSString *scheme_;
    JavaNetURL *url_;
    JavaNetAuthenticator_RequestorTypeEnum *rt_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)requestPasswordAuthenticationWithNSString:(id)arg1 withJavaNetInetAddress:(id)arg2 withInt:(int)arg3 withNSString:(id)arg4 withNSString:(id)arg5 withNSString:(id)arg6 withJavaNetURL:(id)arg7 withJavaNetAuthenticator_RequestorTypeEnum:(id)arg8;
+ (id)requestPasswordAuthenticationWithNSString:(id)arg1 withJavaNetInetAddress:(id)arg2 withInt:(int)arg3 withNSString:(id)arg4 withNSString:(id)arg5 withNSString:(id)arg6;
+ (void)setDefaultWithJavaNetAuthenticator:(id)arg1;
+ (id)requestPasswordAuthenticationWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2 withNSString:(id)arg3 withNSString:(id)arg4 withNSString:(id)arg5;
- (void)dealloc;
- (id)init;
- (id)getRequestorType;
- (id)getRequestingURL;
- (id)getRequestingHost;
- (id)getRequestingScheme;
- (id)getRequestingProtocol;
- (id)getRequestingPrompt;
- (id)getRequestingSite;
- (int)getRequestingPort;
- (id)getPasswordAuthentication;

@end

