//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilHashSet.h"

#import "JavaIoSerializable.h"
#import "JavaUtilSet.h"
#import "NSCopying.h"

@class NSString;

@interface JavaUtilLinkedHashSet : JavaUtilHashSet <JavaUtilSet, NSCopying, JavaIoSerializable>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (id)createBackingMapWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)initWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initWithInt:(int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

