//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractCollection.h"

#import "JavaIoSerializable.h"
#import "JavaUtilDeque.h"

@class NSString;

@interface JavaUtilConcurrentConcurrentLinkedDeque : JavaUtilAbstractCollection <JavaUtilDeque, JavaIoSerializable>
{
    // Error parsing type: A^v, name: head_
    // Error parsing type: A^v, name: tail_
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (void)checkNotNullWithId:(id)arg1;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (void)__javaClone;
- (void)dealloc;
- (BOOL)casTailWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1 withJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg2;
- (BOOL)casHeadWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1 withJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg2;
- (void)readObjectWithJavaIoObjectInputStream:(id)arg1;
- (void)writeObjectWithJavaIoObjectOutputStream:(id)arg1;
- (id)descendingIterator;
- (id)iterator;
- (id)toArrayWithNSObjectArray:(id)arg1;
- (id)toArray;
- (void)clear;
- (BOOL)addAllWithJavaUtilCollection:(id)arg1;
- (BOOL)removeWithId:(id)arg1;
- (int)size;
- (BOOL)isEmpty;
- (BOOL)containsWithId:(id)arg1;
- (BOOL)removeLastOccurrenceWithId:(id)arg1;
- (BOOL)removeFirstOccurrenceWithId:(id)arg1;
- (id)pop;
- (void)pushWithId:(id)arg1;
- (id)element;
- (id)peek;
- (id)remove;
- (id)poll;
- (BOOL)addWithId:(id)arg1;
- (BOOL)offerWithId:(id)arg1;
- (id)removeLast;
- (id)removeFirst;
- (id)pollLast;
- (id)pollFirst;
- (id)getLast;
- (id)getFirst;
- (id)peekLast;
- (id)peekFirst;
- (BOOL)offerLastWithId:(id)arg1;
- (BOOL)offerFirstWithId:(id)arg1;
- (void)addLastWithId:(id)arg1;
- (void)addFirstWithId:(id)arg1;
- (void)initHeadTailWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1 withJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg2;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)init;
- (id)toArrayList;
- (id)screenNullResultWithId:(id)arg1;
- (id)last;
- (id)first;
- (id)predWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1;
- (id)succWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1;
- (void)skipDeletedSuccessorsWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1;
- (void)skipDeletedPredecessorsWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1;
- (void)updateTail;
- (void)updateHead;
- (void)unlinkLastWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1 withJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg2;
- (void)unlinkFirstWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1 withJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg2;
- (void)unlinkWithJavaUtilConcurrentConcurrentLinkedDeque_Node:(id)arg1;
- (void)linkLastWithId:(id)arg1;
- (void)linkFirstWithId:(id)arg1;
- (id)nextTerminator;
- (id)prevTerminator;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

