//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JBTStatus_SyncStatusChangedEvent.h"

@class ComGoogleAppsBigtopDataCommonCommonSyncProtos_SyncStatus, NSString;

@interface JBTBigTopDataStatusManager_$4 : NSObject <JBTStatus_SyncStatusChangedEvent>
{
    ComGoogleAppsBigtopDataCommonCommonSyncProtos_SyncStatus *val$syncStatus_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)initWithComGoogleAppsBigtopDataCommonCommonSyncProtos_SyncStatus:(id)arg1;
- (int)getPendingBackgroundSyncActiveCount;
- (int)getPendingBackgroundSyncCount;
- (int)getAllBackgroundSyncObjectCount;
- (int)getPendingModifiedHighPriorityCount;
- (int)getPendingModifiedCount;
- (BOOL)hasPendingModifiedObjects;
- (id)getSpan;
- (id)getType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

