//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JBTEntityListElementProducer_EntityFetcher.h"

@class JBTContactListElementProducerFactory, NSString;

@interface JBTContactListElementProducerFactory_ContactEntityFetcher : NSObject <JBTEntityListElementProducer_EntityFetcher>
{
    JBTContactListElementProducerFactory *this$0_;
    int maxResults_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)requestStrategyFromConfigWithComGoogleAppsBigtopSyncClientImplProducersElementProducer_Config:(id)arg1;
- (id)getRequestFromConfigWithComGoogleAppsBigtopSyncClientImplProducersElementProducer_Config:(id)arg1;
- (id)fetchWithComGoogleAppsBigtopSyncClientImplProducersElementProducer_Config:(id)arg1;
- (id)initWithJBTContactListElementProducerFactory:(id)arg1 withInt:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

