//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JBTICommonEventImpl.h"

#import "JBTErrorEvent.h"

@class NSString;

@interface JBTICommonErrorEventImpl : JBTICommonEventImpl <JBTErrorEvent>
{
    id <JBTError> error_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)getError;
- (id)initWithJBTError:(id)arg1 withJBTSpan:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

