//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JBTFormattedTime.h"

@class JBTFormattedTime_FormatEnum, JavaLangLong, NSString;

@interface JBTICommonFormattedTimeImpl : NSObject <JBTFormattedTime>
{
    long long timestampMs_;
    JBTFormattedTime_FormatEnum *format_;
    JavaLangLong *tzOffsetMinutes_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_tzOffsetMinutes_;
+ (id)__annotations_equalsWithId__params;
+ (id)__annotations_initWithLong_withJBTFormattedTime_FormatEnum_withJavaLangLong__params;
+ (id)fromDurationWithLong:(long long)arg1;
+ (id)fromSecondsWithTimeZoneOffsetWithLong:(long long)arg1 withLong:(long long)arg2 withJBTFormattedTime_FormatEnum:(id)arg3;
+ (id)fromMillisTimestampWithLong:(long long)arg1 withJBTFormattedTime_FormatEnum:(id)arg2;
+ (id)fromSecondsTimestampWithLong:(long long)arg1 withJBTFormattedTime_FormatEnum:(id)arg2;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned int hash;
- (long long)getSuggestedTzOffsetMinutes;
- (BOOL)hasSuggestedTzOffsetMinutes;
- (id)getSuggestedFormat;
- (long long)getMillis;
- (long long)getSeconds;
- (id)initWithLong:(long long)arg1 withJBTFormattedTime_FormatEnum:(id)arg2 withJavaLangLong:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

