//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JBTClusterConfigEditor.h"

@class JBTIClustersClusterConfigFactory, JBTICommonEventListenersList, NSString;

@interface JBTIClustersClusterConfigEditorImpl : NSObject <JBTClusterConfigEditor>
{
    id <JBTClusterConfig> config_;
    id <ComGoogleCumulusApiBigSet> bigSet_;
    id <ComGoogleCumulusApiObjectHandle> objectHandle_;
    id <JBTClusters> clustersApi_;
    JBTICommonEventListenersList *eventListeners_;
    JBTIClustersClusterConfigFactory *clusterConfigFactory_;
    id <JBTICommonObjectMonitor> monitor_;
    id <JBTICommonObjectMonitorFactory> objectMonitorFactory_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_monitor_;
+ (id)__annotations_stopWithJBTSpan__params;
+ (id)__annotations_startWithJBTSpan__params;
+ (id)__annotations_updateWithJBTClusterConfig_withJBTCallback_withJBTSpan__params;
+ (void)initialize;
- (void)dealloc;
- (id)createConfigFromProtoWithComGoogleAppsBigtopServicesClustersBigTopCluster:(id)arg1;
- (void)removeListenerWithJBTEventListener:(id)arg1;
- (void)addListenerWithJBTEventListener:(id)arg1;
- (void)stopWithJBTSpan:(id)arg1;
- (void)startWithJBTSpan:(id)arg1;
- (id)getClusterConfig;
- (void)updateWithJBTClusterConfig:(id)arg1 withJBTCallback:(id)arg2 withJBTSpan:(id)arg3;
- (id)initWithComGoogleCumulusApiBigSet:(id)arg1 withJBTClusters:(id)arg2 withJBTIClustersClusterConfigFactory:(id)arg3 withJBTClusterConfig:(id)arg4 withJBTICommonObjectMonitorFactory:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

