//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangComparable.h"

@class ComGoogleAppsBigtopServicesSmartmailSmartMailMetricsProto_ContextViewCount_ViewContextEnum, NSString;

@interface JBTISmartMailSmartMailMetricsRecorderImpl_SmartMailViewAggregator_SmartMailCardMetadata : NSObject <JavaLangComparable>
{
    ComGoogleAppsBigtopServicesSmartmailSmartMailMetricsProto_ContextViewCount_ViewContextEnum *viewContext_;
    NSString *smartMailType_;
    NSString *senderDomain_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_equalsWithId__params;
+ (id)__annotations_initWithComGoogleAppsBigtopServicesSmartmailSmartMailMetricsProto_ContextViewCount_ViewContextEnum_withNSString_withNSString__params;
- (void)dealloc;
- (int)compareToWithId:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned int hash;
- (id)initWithComGoogleAppsBigtopServicesSmartmailSmartMailMetricsProto_ContextViewCount_ViewContextEnum:(id)arg1 withNSString:(id)arg2 withNSString:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

