//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JBTCallback.h"

@class JBTIItemsPermanentlyDeleteAllHelper, JBTIItemsPermanentlyDeleteAllHelper_DeleteCanceler, JBTIItemsPermanentlyDeleteAllHelper_IncrementalRequestState, JBTIItemsPermanentlyDeleteAllHelper_QueryTypeEnum, NSString;

@interface JBTIItemsPermanentlyDeleteAllHelper_$2 : NSObject <JBTCallback>
{
    JBTIItemsPermanentlyDeleteAllHelper *this$0_;
    JBTIItemsPermanentlyDeleteAllHelper_DeleteCanceler *val$canceler_;
    id <JBTItemList> val$itemList_;
    id <JBTICommonTransactionFactory> val$transactionFactory_;
    JBTIItemsPermanentlyDeleteAllHelper_QueryTypeEnum *val$queryType_;
    id <JBTCallback> val$clientCallback_;
    id <JBTICommonSapiSpan> val$sapiSpan_;
    JBTIItemsPermanentlyDeleteAllHelper_IncrementalRequestState *val$requestState_;
    id <JBTProgressListener> val$progressListener_;
    id <JBTICommonSapiSpan> val$childSpan_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)initWithJBTIItemsPermanentlyDeleteAllHelper:(id)arg1 withJBTIItemsPermanentlyDeleteAllHelper_DeleteCanceler:(id)arg2 withJBTItemList:(id)arg3 withJBTICommonTransactionFactory:(id)arg4 withJBTIItemsPermanentlyDeleteAllHelper_QueryTypeEnum:(id)arg5 withJBTCallback:(id)arg6 withJBTICommonSapiSpan:(id)arg7 withJBTIItemsPermanentlyDeleteAllHelper_IncrementalRequestState:(id)arg8 withJBTProgressListener:(id)arg9 withJBTICommonSapiSpan:(id)arg10;
- (void)onErrorWithJBTError:(id)arg1;
- (void)onSuccessWithId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

