//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JBTIItemsItemListImpl.h"

#import "JBTFilterResultsList.h"

@class NSString;

@interface JBTIClustersFilterResultsListImpl : JBTIItemsItemListImpl <JBTFilterResultsList>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_updateFiltersWithJBTClusterFilter_Builder_withJBTSpan__params;
+ (id)__annotations_initWithComGoogleAppsBigtopSyncClientImplLivelistLiveListsManager_withComGoogleAppsBigtopSyncClientImplProducersElementProducer_withJBTIItemsItemListByIdImpl_withDaggerLazy_withDaggerLazy_withJBTICommonSapiSpan_Factory_withJBTICommonTransactionFactory__params;
- (BOOL)canMarkAllAsSeen;
- (void)updateFiltersWithJBTClusterFilter_Builder:(id)arg1 withJBTSpan:(id)arg2;
- (id)initWithComGoogleAppsBigtopSyncClientImplLivelistLiveListsManager:(id)arg1 withComGoogleAppsBigtopSyncClientImplProducersElementProducer:(id)arg2 withJBTIItemsItemListByIdImpl:(id)arg3 withDaggerLazy:(id)arg4 withDaggerLazy:(id)arg5 withJBTICommonSapiSpan_Factory:(id)arg6 withJBTICommonTransactionFactory:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

