//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "NSObject.h"

@protocol JBTLocationAliases <NSObject, JavaObject>
- (id <JBTLocationAlias_Factory>)getLocationAliasFactory;
- (id <JBTLocationAliasList>)getLocationListWithInt:(int)arg1;
@end

