//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JBTOrganization : NSObject
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_NONE_;
+ (id)__annotations_getLogo;
+ (id)__annotations_isOpen;
+ (id)__annotations_getPhoneNumber;
+ (id)__annotations_getAddress;
+ (id)__annotations_getUrl;
+ (id)__annotations;
+ (void)initialize;

@end

