//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ComGoogleCommonBaseOptional;

@interface JCGCuHttpResponse : NSObject
{
    int statusCode_;
    id <JavaUtilMap> responseHeaders_;
    ComGoogleCommonBaseOptional *payload_;
}

+ (id)okWithJavaUtilMap:(id)arg1 withId:(id)arg2;
+ (id)notOkWithInt:(int)arg1 withJavaUtilMap:(id)arg2;
- (void)dealloc;
- (id)getPayload;
- (id)getResponseHeaders;
- (int)getStatusCode;
- (id)initWithInt:(int)arg1 withJavaUtilMap:(id)arg2 withComGoogleCommonBaseOptional:(id)arg3;

@end

