//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleCumulusSyncClientMemoryObjectCache.h"

@class ComGoogleCumulusCommonMetric2SpanHelper, NSString;

@interface JCGCuImmediateEvictionCache : NSObject <ComGoogleCumulusSyncClientMemoryObjectCache>
{
    id <JavaUtilMap> cachedObjects_;
    id <ComGoogleCumulusApiPluginSlicer> slicer_;
    ComGoogleCumulusCommonMetric2SpanHelper *spanHelper_;
}

+ (void)initialize;
- (void)dealloc;
- (void)updateSizeWithComGoogleCumulusSyncClientDefaultObjectManager_CachedObject:(id)arg1 withInt:(int)arg2;
- (int)getPendingEvictionSize;
- (id)dumpWithJavaLangStringBuffer:(id)arg1;
- (int)getObjectCount;
- (void)markSliceableWithNSString:(id)arg1 withJavaUtilCollection:(id)arg2;
- (void)markEvictableWithNSString:(id)arg1 withComGoogleCumulusSyncClientCacheEvictionPolicy_EvictionStatusEnum:(id)arg2;
- (void)putWithNSString:(id)arg1 withComGoogleCumulusSyncClientDefaultObjectManager_CachedObject:(id)arg2;
- (id)acquireWithNSString:(id)arg1;
- (id)getWithNSString:(id)arg1;
- (id)initWithComGoogleCumulusApiPluginSlicer:(id)arg1 withComGoogleCumulusCommonMetric2SpanHelper:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

