//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ComGoogleCumulusCommonConfigConfiguration_AdapterFactory.h"

@class NSString;

@interface JCGCuInstrumentingWorkQueueBundle_ConditionalStoreAdapter : NSObject <ComGoogleCumulusCommonConfigConfiguration_AdapterFactory>
{
    id <ComGoogleCumulusCommonConfigConfiguration_AdapterFactory> realAdapterFactory_;
}

- (void)dealloc;
- (id)createWithId:(id)arg1 withComGoogleCumulusCommonConfigConfiguration:(id)arg2;
- (id)initWithJCGCuInstrumentingWorkQueueBundle:(id)arg1 withComGoogleCumulusCommonConfigConfiguration_AdapterFactory:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

