//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JCGCuWorkerAppMessagesManager : NSObject
{
    id <JavaUtilMap> producersByClientId_;
    id <ComGoogleCumulusApiPluginWorkerAppMessageReceiver> workerAppMessagesReceiver_;
}

+ (void)initialize;
- (void)dealloc;
- (id)createMessageProducerWithNSString:(id)arg1 withComGoogleCumulusCommonUtilEventBus:(id)arg2;
- (id)createMessageReceiverWithNSString:(id)arg1;
- (void)sendToClientWithNSString:(id)arg1 withComGoogleCumulusCommonAppMessageProto_AppMessage:(id)arg2;
- (id)initWithComGoogleCumulusApiPluginWorkerAppMessageReceiver:(id)arg1;

@end

