//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@class JCSDateFormattingOptions, JCSFormatEnum, JCSTime;

@protocol JCSDatePlaceholderOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (JCSFormatEnum *)getFormat;
- (BOOL)hasFormat;
- (JCSDateFormattingOptions *)getOptions;
- (BOOL)hasOptions;
- (JCSTime *)getEnd;
- (BOOL)hasEnd;
- (JCSTime *)getDate;
- (BOOL)hasDate;
@end

