//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComGoogleProtobufMessageOrBuilder.h"

@class JCSAssignedId, JCSFlightReservation_FlightSegment_FlightPassengerInfo, JCSFlightReservation_FlightSegment_StatusCodeEnum, JCSImage, JCSTime, NSString;

@protocol JCSFlightReservation_FlightSegmentOrBuilder <ComGoogleProtobufMessageOrBuilder>
- (JCSFlightReservation_FlightSegment_FlightPassengerInfo *)getPassengerInfoWithInt:(int)arg1;
- (id <JavaUtilList>)getPassengerInfoList;
- (int)getPassengerInfoCount;
- (JCSTime *)getLastUpdated;
- (BOOL)hasLastUpdated;
- (JCSImage *)getImage;
- (BOOL)hasImage;
- (NSString *)getFlightStatusMessage;
- (BOOL)hasFlightStatusMessage;
- (JCSFlightReservation_FlightSegment_StatusCodeEnum *)getStatusCode;
- (BOOL)hasStatusCode;
- (NSString *)getArrivalGate;
- (BOOL)hasArrivalGate;
- (NSString *)getDepartureGate;
- (BOOL)hasDepartureGate;
- (NSString *)getArrivalTerminal;
- (BOOL)hasArrivalTerminal;
- (NSString *)getDepartureTerminal;
- (BOOL)hasDepartureTerminal;
- (NSString *)getDivertedArrivalCity;
- (BOOL)hasDivertedArrivalCity;
- (NSString *)getDivertedArrivalAirportCode;
- (BOOL)hasDivertedArrivalAirportCode;
- (NSString *)getArrivalCity;
- (BOOL)hasArrivalCity;
- (NSString *)getArrivalAirportCode;
- (BOOL)hasArrivalAirportCode;
- (NSString *)getDepartureCity;
- (BOOL)hasDepartureCity;
- (NSString *)getDepartureAirportCode;
- (BOOL)hasDepartureAirportCode;
- (JCSTime *)getActualArrivalTime;
- (BOOL)hasActualArrivalTime;
- (JCSTime *)getArrivalTime;
- (BOOL)hasArrivalTime;
- (JCSTime *)getActualDepartureTime;
- (BOOL)hasActualDepartureTime;
- (JCSTime *)getDepartureTime;
- (BOOL)hasDepartureTime;
- (NSString *)getFlightNumber;
- (BOOL)hasFlightNumber;
- (NSString *)getAirlineCode;
- (BOOL)hasAirlineCode;
- (NSString *)getAirlineName;
- (BOOL)hasAirlineName;
- (NSString *)getBookingReference;
- (BOOL)hasBookingReference;
- (JCSAssignedId *)getAssignedId;
- (BOOL)hasAssignedId;
@end

