//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MoreActionsViewController, NSString;

@protocol MoreActionsViewControllerDelegate <NSObject>
- (void)moreActionsViewControllerDidCancel:(MoreActionsViewController *)arg1;
- (void)moreActionsViewController:(MoreActionsViewController *)arg1 didSelectAction:(unsigned int)arg2;
- (void)moreActionsViewController:(MoreActionsViewController *)arg1 didSelectMoveToNewClusterWithDisplayName:(NSString *)arg2;
- (void)moreActionsViewController:(MoreActionsViewController *)arg1 didSelectMoveToCluster:(id <JBTClusterConfig>)arg2;
- (void)moreActionsViewControllerDidSelectRemoveFromCurrentCluster:(MoreActionsViewController *)arg1;
@end

