//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "ClusterNameViewControllerDelegate.h"
#import "JBTEventListener.h"
#import "MoreActionsViewControllerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ActionHandler, JBTTopicTypeEnum, NSMutableArray, NSMutableDictionary, NSString;

@interface MoreActionsViewController : UITableViewController <ClusterNameViewControllerDelegate, JBTEventListener, MoreActionsViewControllerDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate>
{
    ActionHandler *actionHandler_;
    id <JBTClusterConfig> currentCluster_;
    id <JBTClusterConfigList> clusterList_;
    id <JBTItem> item_;
    NSMutableArray *moveToRows_;
    NSMutableDictionary *topicClusterLists_;
    BOOL _hideNewClusterButton;
    id <MoreActionsViewControllerDelegate> _delegate;
    JBTTopicTypeEnum *_topicType;
}

+ (id)createTopicClusterLists;
+ (id)moreActionsViewControllerWithActionHandler:(id)arg1;
+ (id)moreActionsViewControllerWithItem:(id)arg1;
@property(retain, nonatomic) JBTTopicTypeEnum *topicType; // @synthesize topicType=_topicType;
@property(nonatomic) BOOL hideNewClusterButton; // @synthesize hideNewClusterButton=_hideNewClusterButton;
@property(nonatomic) __weak id <MoreActionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)moreActionsViewControllerDidCancel:(id)arg1;
- (void)moreActionsViewController:(id)arg1 didSelectAction:(unsigned int)arg2;
- (void)moreActionsViewController:(id)arg1 didSelectMoveToNewClusterWithDisplayName:(id)arg2;
- (void)moreActionsViewController:(id)arg1 didSelectMoveToCluster:(id)arg2;
- (void)moreActionsViewControllerDidSelectRemoveFromCurrentCluster:(id)arg1;
- (void)clusterNameViewControllerDidCancel:(id)arg1;
- (void)clusterNameViewController:(id)arg1 didFinishWithName:(id)arg2;
- (void)newClusterTapped:(id)arg1;
- (id)rightBarButton;
- (void)openTripsMoveTo;
- (id)navBarTitleForTopic;
- (id)navBarTitle;
- (id)leftBarButton;
- (BOOL)isActionTypeApplicable:(unsigned int)arg1 clusterConfig:(id)arg2;
- (void)initializeMoveToDestinationsForTopicCluster;
- (void)initializeMoveToDestinations;
- (void)cancelButtonTapped:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)onEventWithJBTEvent:(id)arg1;
- (int)preferredStatusBarStyle;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)cancel;
- (id)initWithItem:(id)arg1 actionHandler:(id)arg2 currentCluster:(id)arg3 clusterList:(id)arg4 topicClusterLists:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

