//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OrgApacheHarmonySecurityFortressEngine : NSObject
{
    NSString *serviceName_;
    // Error parsing type: A^v, name: serviceCache_
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)__javaClone;
- (void)dealloc;
- (id)notFoundWithNSString:(id)arg1 withNSString:(id)arg2;
- (id)getInstanceWithNSString:(id)arg1 withJavaSecurityProvider:(id)arg2 withId:(id)arg3;
- (id)getServicesWithNSString:(id)arg1;
- (id)getInstanceWithJavaSecurityProvider_Service:(id)arg1 withNSString:(id)arg2;
- (id)getInstanceWithNSString:(id)arg1 withId:(id)arg2;
- (id)initWithNSString:(id)arg1;

@end

