//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrgJodaTimeChronoBasicChronology.h"

@interface OrgJodaTimeChronoBasicGJChronology : OrgJodaTimeChronoBasicChronology
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
- (long long)setYearWithLong:(long long)arg1 withInt:(int)arg2;
- (long long)getYearDifferenceWithLong:(long long)arg1 withLong:(long long)arg2;
- (long long)getTotalMillisByYearMonthWithInt:(int)arg1 withInt:(int)arg2;
- (int)getDaysInMonthMaxForSetWithLong:(long long)arg1 withInt:(int)arg2;
- (int)getDaysInMonthMaxWithInt:(int)arg1;
- (int)getDaysInYearMonthWithInt:(int)arg1 withInt:(int)arg2;
- (int)getMonthOfYearWithLong:(long long)arg1 withInt:(int)arg2;
- (id)initWithOrgJodaTimeChronology:(id)arg1 withId:(id)arg2 withInt:(int)arg3;

@end

