//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "NSObject.h"

@class NSString, OrgJodaTimeDurationFieldType, OrgJodaTimeMutablePeriod, OrgJodaTimePeriod, OrgJodaTimePeriodType;

@protocol OrgJodaTimeReadablePeriod <NSObject, JavaObject>
- (NSString *)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (OrgJodaTimeMutablePeriod *)toMutablePeriod;
- (OrgJodaTimePeriod *)toPeriod;
- (BOOL)isSupportedWithOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)arg1;
- (int)getWithOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)arg1;
- (int)getValueWithInt:(int)arg1;
- (OrgJodaTimeDurationFieldType *)getFieldTypeWithInt:(int)arg1;
- (int)size;
- (OrgJodaTimePeriodType *)getPeriodType;
@end

