//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OrgJodaTimeFormatISODateTimeFormat : NSObject
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)dateHourMinuteSecondFraction;
+ (id)dateHourMinuteSecondMillis;
+ (id)dateHourMinuteSecond;
+ (id)dateHourMinute;
+ (id)dateHour;
+ (id)hourMinuteSecondFraction;
+ (id)hourMinuteSecondMillis;
+ (id)hourMinuteSecond;
+ (id)hourMinute;
+ (id)hour;
+ (id)weekyearWeekDay;
+ (id)weekyearWeek;
+ (id)weekyear;
+ (id)yearMonthDay;
+ (id)yearMonth;
+ (id)year;
+ (id)basicWeekDateTimeNoMillis;
+ (id)basicWeekDateTime;
+ (id)basicWeekDate;
+ (id)basicOrdinalDateTimeNoMillis;
+ (id)basicOrdinalDateTime;
+ (id)basicOrdinalDate;
+ (id)basicDateTimeNoMillis;
+ (id)basicDateTime;
+ (id)basicTTimeNoMillis;
+ (id)basicTTime;
+ (id)basicTimeNoMillis;
+ (id)basicTime;
+ (id)basicDate;
+ (id)weekDateTimeNoMillis;
+ (id)weekDateTime;
+ (id)weekDate;
+ (id)ordinalDateTimeNoMillis;
+ (id)ordinalDateTime;
+ (id)ordinalDate;
+ (id)dateTimeNoMillis;
+ (id)dateTime;
+ (id)tTimeNoMillis;
+ (id)tTime;
+ (id)timeNoMillis;
+ (id)time;
+ (id)date;
+ (id)localDateOptionalTimeParser;
+ (id)dateOptionalTimeParser;
+ (id)dateTimeParser;
+ (id)timeElementParser;
+ (id)localTimeParser;
+ (id)timeParser;
+ (id)dateElementParser;
+ (id)localDateParser;
+ (id)dateParser;
+ (void)appendSeparatorWithOrgJodaTimeFormatDateTimeFormatterBuilder:(id)arg1 withBoolean:(BOOL)arg2;
+ (void)checkNotStrictISOWithJavaUtilCollection:(id)arg1 withBoolean:(BOOL)arg2;
+ (void)timeWithOrgJodaTimeFormatDateTimeFormatterBuilder:(id)arg1 withJavaUtilCollection:(id)arg2 withBoolean:(BOOL)arg3 withBoolean:(BOOL)arg4 withBoolean:(BOOL)arg5 withBoolean:(BOOL)arg6;
+ (BOOL)dateByWeekWithOrgJodaTimeFormatDateTimeFormatterBuilder:(id)arg1 withJavaUtilCollection:(id)arg2 withBoolean:(BOOL)arg3 withBoolean:(BOOL)arg4;
+ (BOOL)dateByOrdinalWithOrgJodaTimeFormatDateTimeFormatterBuilder:(id)arg1 withJavaUtilCollection:(id)arg2 withBoolean:(BOOL)arg3 withBoolean:(BOOL)arg4;
+ (BOOL)dateByMonthWithOrgJodaTimeFormatDateTimeFormatterBuilder:(id)arg1 withJavaUtilCollection:(id)arg2 withBoolean:(BOOL)arg3 withBoolean:(BOOL)arg4;
+ (id)forFieldsWithJavaUtilCollection:(id)arg1 withBoolean:(BOOL)arg2 withBoolean:(BOOL)arg3;
- (id)init;

@end

