//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrgJodaTimeFieldPreciseDurationDateTimeField.h"

@class OrgJodaTimeChronoBasicChronology;

@interface OrgJodaTimeChronoBasicDayOfYearDateTimeField : OrgJodaTimeFieldPreciseDurationDateTimeField
{
    OrgJodaTimeChronoBasicChronology *iChronology_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (void)dealloc;
- (id)readResolve;
- (int)getMaximumValueForSetWithLong:(long long)arg1 withInt:(int)arg2;
- (int)getMaximumValueWithOrgJodaTimeReadablePartial:(id)arg1 withIntArray:(id)arg2;
- (int)getMaximumValueWithOrgJodaTimeReadablePartial:(id)arg1;
- (int)getMaximumValueWithLong:(long long)arg1;
- (int)getMaximumValue;
- (int)getMinimumValue;
- (id)getRangeDurationField;
- (int)getWithLong:(long long)arg1;
- (id)initWithOrgJodaTimeChronoBasicChronology:(id)arg1 withOrgJodaTimeDurationField:(id)arg2;

@end

