//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "OrgJodaTimeFormatPeriodParser.h"
#import "OrgJodaTimeFormatPeriodPrinter.h"

@class NSString;

@interface OrgJodaTimeFormatPeriodFormatterBuilder_Literal : NSObject <OrgJodaTimeFormatPeriodPrinter, OrgJodaTimeFormatPeriodParser>
{
    NSString *iText_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
- (void)dealloc;
- (int)parseIntoWithOrgJodaTimeReadWritablePeriod:(id)arg1 withNSString:(id)arg2 withInt:(int)arg3 withJavaUtilLocale:(id)arg4;
- (void)printToWithJavaIoWriter:(id)arg1 withOrgJodaTimeReadablePeriod:(id)arg2 withJavaUtilLocale:(id)arg3;
- (void)printToWithJavaLangStringBuffer:(id)arg1 withOrgJodaTimeReadablePeriod:(id)arg2 withJavaUtilLocale:(id)arg3;
- (int)calculatePrintedLengthWithOrgJodaTimeReadablePeriod:(id)arg1 withJavaUtilLocale:(id)arg2;
- (int)countFieldsToPrintWithOrgJodaTimeReadablePeriod:(id)arg1 withInt:(int)arg2 withJavaUtilLocale:(id)arg3;
- (id)initWithNSString:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

