//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TopToolBar.h"

#import "ExpandableTextFieldDelegate.h"

@class ExpandableTextField, NSString, UIButton, UIImage, UILabel, UIView;

@interface ParticipantSearchBar : TopToolBar <ExpandableTextFieldDelegate>
{
    UIButton *clearButton_;
    UIView *containerView_;
    UILabel *placeholderLabel_;
    UIView *separator_;
    ExpandableTextField *textField_;
    UIButton *typeSelectionButton_;
    UIImage *participantTypeIcon_;
    NSString *text_;
    id <ParticipantSearchBarDelegate> _participantSearchDelegate;
}

@property(nonatomic) __weak id <ParticipantSearchBarDelegate> participantSearchDelegate; // @synthesize participantSearchDelegate=_participantSearchDelegate;
@property(copy, nonatomic) NSString *text; // @synthesize text=text_;
@property(retain, nonatomic) UIImage *participantTypeIcon; // @synthesize participantTypeIcon=participantTypeIcon_;
- (void).cxx_destruct;
- (id)createParticipantSelectionIconWithImage:(id)arg1;
- (void)updateClearButtonState;
- (void)clear;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidChangeText:(id)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)isFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)changeType;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)createSubViews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(unsigned int)arg2 withDataSource:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

