//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CellPositionSupport.h"
#import "GBTNetworkImageViewDelegate.h"

@class GBTNetworkImageView, NSMutableArray, NSString, SmartMailDetailedLayoutSectionView, SmartMailImageAttributionView, SmartMailInteractionForwarder, UIColor, UIImage, UIImageView, UILabel;

@interface SmartMailDetailedLayoutView : UIView <GBTNetworkImageViewDelegate, CellPositionSupport>
{
    UIView *collapsedContainer_;
    UIView *expandedContainer_;
    UIImageView *cardBackground_;
    GBTNetworkImageView *headerImage_;
    UIView *sectionSpacer_;
    NSMutableArray *sectionViews_;
    NSMutableArray *snippetViews_;
    UILabel *subtitleLabel_;
    UIView *titleBackground_;
    UILabel *titleLabel_;
    UIImageView *backgroundView_;
    SmartMailDetailedLayoutSectionView *collapsedDetails_;
    UIView *separator_;
    SmartMailInteractionForwarder *forwarder_;
    unsigned int numberOfRows_;
    UIColor *mainColor_;
    BOOL attributionShown_;
    SmartMailImageAttributionView *attributionView_;
    UIImage *upscaledImage_;
    BOOL bleedHeaderImage_;
    BOOL expanded_;
    BOOL imageHidden_;
    unsigned int cellPosition_;
    id <JBTGenericSmartMailDetailedLayout> layout_;
    id <SmartMailDetailedLayoutViewDelegate> _delegate;
}

+ (float)heightForTitle:(id)arg1 width:(float)arg2 isSubtitle:(BOOL)arg3;
+ (id)subtitleStringFromLayout:(id)arg1;
+ (id)titleStringFromLayout:(id)arg1;
+ (float)heightForRowWithSections:(id)arg1 width:(float)arg2 collapsed:(BOOL)arg3;
+ (float)heightForSectionAtIndex:(unsigned int)arg1 sections:(id)arg2 numberOfRows:(unsigned int)arg3 width:(float)arg4 collapsed:(BOOL)arg5;
+ (float)heightWithLayout:(id)arg1 expanded:(BOOL)arg2 bleedHeader:(BOOL)arg3 cellPosition:(unsigned int)arg4 imageHidden:(BOOL)arg5 width:(float)arg6;
+ (void)initialize;
@property(nonatomic) __weak id <SmartMailDetailedLayoutViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <JBTGenericSmartMailDetailedLayout> layout; // @synthesize layout=layout_;
@property(nonatomic) BOOL imageHidden; // @synthesize imageHidden=imageHidden_;
@property(nonatomic) BOOL expanded; // @synthesize expanded=expanded_;
@property(nonatomic) unsigned int cellPosition; // @synthesize cellPosition=cellPosition_;
@property(nonatomic) BOOL bleedHeaderImage; // @synthesize bleedHeaderImage=bleedHeaderImage_;
- (void).cxx_destruct;
- (id)accessibilityIdentifierOfTappableSubviewForExpanded:(BOOL)arg1;
- (void)showAttribution:(BOOL)arg1;
- (void)hideAttribution;
- (void)updateWithImageMetadata:(id)arg1;
- (void)resetAttribution;
- (void)createAttributionViewIfNeeded;
- (void)setStockImageOnHeader;
- (void)updateHeaderImageContentMode;
- (float)heightForSectionAtIndex:(unsigned int)arg1 width:(float)arg2;
- (struct CGRect)backgroundViewFrameForCurrentCellPosition;
- (void)headerLongPressed:(id)arg1;
- (void)expandedTitleTapped:(id)arg1;
- (void)collapsedBackgroundTapped:(id)arg1;
- (void)updateWithImage:(id)arg1;
- (void)updateBackgroundView;
- (void)createSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)imageViewDidFailToLoadImage:(id)arg1;
- (void)imageViewDidLoadImage:(id)arg1 isThumbnail:(BOOL)arg2;
@property(readonly, nonatomic) float titleTop;
@property(nonatomic) __weak id <SmartMailInteractionSupport> smartMailDelegate;
- (void)setExpanded:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

