//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SnoozeUtil : NSObject
{
}

+ (BOOL)isItemPendingBump:(id)arg1;
+ (id)resnoozeAckStringFromSnoozeConfig:(id)arg1;
+ (id)resnoozeActionStringFromSnoozeConfig:(id)arg1;
+ (id)snoozeActionStringFromSnoozeConfig:(id)arg1 font:(id)arg2;
+ (id)stringForSetSnoozePreset:(id)arg1 success:(BOOL)arg2;
+ (id)stringForSuggestedSnoozePreset:(id)arg1;
+ (id)stringForSnoozePresetTime:(id)arg1;
+ (id)stringForSnoozePresetName:(id)arg1;
+ (id)snoozeAckStringFromSnoozeConfig:(id)arg1;
+ (id)snoozeReturnStringColorForItem:(id)arg1;
+ (id)snoozeReturnStringForItem:(id)arg1;
+ (BOOL)shouldShowSnoozeReturnStringForItem:(id)arg1;
+ (id)snoozeReturnTimeStringForItem:(id)arg1;
+ (id)textFromLocationAlias:(id)arg1;
+ (id)textFromLocation:(id)arg1;
+ (id)snoozeTargetStringFromSnoozeConfig:(id)arg1;
+ (id)snoozePrefixForSnoozeConfig:(id)arg1 snoozePrefixType:(unsigned int)arg2;
+ (void)initialize;

@end

