//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SSOIdentity : NSObject
{
}

- (id)identityPropertyForKey:(id)arg1;
- (BOOL)canSelect;
- (id)userFullName;
- (BOOL)hasValidAuth;
- (BOOL)isSignedIn;
- (id)hashedUserID;
- (id)userID;
- (id)userEmail;

@end

