//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "JBTCallback.h"

@class GIPNetworkImageView, NSString, UILabel, UIView;

@interface TaskComposeSuggestionCell : UITableViewCell <JBTCallback>
{
    UILabel *suggestionLabel_;
    GIPNetworkImageView *contactImage_;
    UIView *separatorView_;
    id <JBTTaskSuggestion_RenderingData> renderingData_;
    id <TaskComposeSuggestCellDelegate> _taskDelegate;
}

+ (id)attributedStringForSubtext:(id)arg1;
+ (id)attributedStringForHelpText:(id)arg1;
+ (float)heightForLabelWithSuggestion:(id)arg1 query:(id)arg2 cellWidth:(float)arg3;
@property(nonatomic) __weak id <TaskComposeSuggestCellDelegate> taskDelegate; // @synthesize taskDelegate=_taskDelegate;
@property(retain, nonatomic) id <JBTTaskSuggestion_RenderingData> renderingData; // @synthesize renderingData=renderingData_;
- (void).cxx_destruct;
- (void)onErrorWithJBTError:(id)arg1;
- (void)onSuccessWithId:(id)arg1;
- (void)setSuggestionTextForSuggestion:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

