//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TimeUtils : NSObject
{
}

+ (id)sharedCalendar;
+ (id)iosDateTimeFromNSDateUsingDefaultTimeZone:(id)arg1;
+ (id)dateByAddingComponents:(id)arg1 toDate:(id)arg2 timeZone:(id)arg3;
+ (id)dateComponentsFromMinusPeriod:(id)arg1;
+ (id)dateComponentsFromPeriod:(id)arg1;
+ (id)defaultTimedPeriod;
+ (id)dateFromInstant:(id)arg1;
+ (id)defaultIOSDateTimeFromNow:(id)arg1;
+ (long long)defaultTimeSinceMidnightInMillis:(id)arg1;
+ (long long)millisPerSeconds:(double)arg1;
+ (double)secondsPerMillis:(long long)arg1;
+ (void)refreshLocale;
+ (unsigned int)daysUntilEndOfMonthForDate:(id)arg1 timeZone:(id)arg2;
+ (struct _NSRange)rangeOfUnit:(unsigned int)arg1 inUnit:(unsigned int)arg2 forDate:(id)arg3 timeZone:(id)arg4;
+ (int)firstWeekdayWithTimeZone:(id)arg1;
+ (id)midnightFromDate:(id)arg1 timeZone:(id)arg2;
+ (id)dateFromComponents:(id)arg1 timeZone:(id)arg2;
+ (id)components:(unsigned int)arg1 fromDate:(id)arg2 timeZone:(id)arg3;

@end

