//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (gbt)
+ (float)gbt_screenHeight;
+ (float)gbt_screenWidth;
+ (float)gbt_screenWidthInPortrait;
+ (BOOL)isWideScreenDevice;
+ (BOOL)isIPhone6Plus;
+ (BOOL)isIPhone6Standard;
+ (BOOL)isIPhone;
+ (BOOL)isIPad;
+ (BOOL)isIOS8OrLater;
@end

