//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBAllocationTrackerLogger, NSObject<OS_dispatch_queue>;

@interface FBAllocationTrackerManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _userOptedIn;
    BOOL _passedGK;
    FBAllocationTrackerLogger *_ctscanLogger;
}

+ (void)_startTrackingAllocations;
+ (id)sharedManager;
+ (BOOL)isAllocationTrackerEnabled;
+ (void)startTrackingAllocationsIfEnabled;
+ (void)stopTrackingAllocations;
- (void).cxx_destruct;
- (id)currentAllocationSummary;
- (void)userPassedGK;
- (void)userOptedIn;
- (void)_startAllocationTrackerIfPossible;
- (id)init;
- (void)_CTScanStartTrackingAllocations;

@end

