//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol FBAudioSessionManagerClient <NSObject>
- (void)finishInterruptionAndResume:(BOOL)arg1;
- (void)beginInterruption;

@optional
@property(readonly, nonatomic) unsigned int clientPriority;
@property(readonly, nonatomic) unsigned int inputOptions;
@property(readonly, nonatomic) unsigned int outputOptions;
@property(readonly, nonatomic) unsigned int outputCoordinationMode;
@property(readonly, nonatomic) unsigned int audioDirection;
- (void)highPriorityClientDeactivated;
- (void)highPriorityClientBecameActive;
@end

