//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBComposerCompositionStateChangedListener.h"

@class FBComposerCompositionState, NSString;

@interface FBComposerPrivacyFetchController : NSObject <FBComposerCompositionStateChangedListener>
{
    FBComposerCompositionState *_compositionState;
    id <FBComposerDefaultAudienceAndAvailablePrivacyCacheListener> _listener;
    id <FBComposerPrivacySettingFetcher> _scopedPrivacySettingFetcher;
}

- (void).cxx_destruct;
- (void)fetchAllPrivacySettingsForPrivacySettingLoadType:(unsigned int)arg1 withSelectedPrivacySetting:(id)arg2;
- (void)composerCompositionStateChangedFromPreviousCompositionState:(id)arg1 toCurrentCompositionState:(id)arg2;
- (id)initWithPrivacySettingFetcher:(id)arg1 audienceListener:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

