//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "FBComposerDoodlesViewDelegate.h"
#import "FBMediaGalleryToolProtocol.h"

@class FBComposerDoodlesView, FBDrawViewController, FBMediaGalleryTopBarConfiguration, FBUserSession, NSString, UIImage;

@interface FBComposerDoodlesViewController : UIViewController <FBComposerDoodlesViewDelegate, FBMediaGalleryToolProtocol>
{
    BOOL _addedInitialDoodles;
    NSString *_assetID;
    BOOL _didChangePhotoOverlay;
    FBComposerDoodlesView *_doodlesView;
    FBDrawViewController *_drawViewController;
    UIImage *_imageToAddDoodles;
    UIImage *_photoOverlayLayer;
    FBUserSession *_session;
    FBMediaGalleryTopBarConfiguration *_topBarConfiguration;
    id <FBComposerDoodlesViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBComposerDoodlesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)mediaGalleryWillPresentTool:(unsigned int)arg1;
- (void)mediaGalleryDidPressCurrentTool;
- (unsigned int)getMediaGalleryToolType;
- (void)composerDoodlesViewDidTapCancel:(id)arg1;
- (void)composerDoodlesViewDidTapDone:(id)arg1;
- (void)_doodlesControllerDoneWithNavBarHit:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithImage:(id)arg1 photoOverlayLayer:(id)arg2 photoAssetID:(id)arg3 topBarConfiguration:(id)arg4 session:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

