//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBComposerFeedTopicPickerViewController, NSArray;

@protocol FBComposerFeedTopicPickerViewControllerDelegate <NSObject>
- (void)feedTopicPickerDidCancel:(FBComposerFeedTopicPickerViewController *)arg1;
- (void)feedTopicPicker:(FBComposerFeedTopicPickerViewController *)arg1 didSelectTopics:(NSArray *)arg2;
@end

