//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "FBCrowdsourcingCityPickerDelegate.h"
#import "FBCrowdsourcingCreationPrivacyViewControllerDelegate.h"
#import "FBCrowdsourcingHomeViewDelegate.h"
#import "FBKeyboardObserverDelegate.h"
#import "FBMediaAttachmentPickerControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITextFieldDelegate.h"

@class CLLocation, FBCrowdsourcingCreationErrorHandleController, FBCrowdsourcingCreationPrivacyViewController, FBCrowdsourcingHomeView, FBKeyboardFocusedViewDisplayer, FBKeyboardObserver, FBMediaAttachmentPickerController, FBMemPerson, FBUserSession, NSString, UITextField, UIView;

@interface FBCrowdsourcingHomeBaseViewController : UIViewController <UITextFieldDelegate, UIScrollViewDelegate, FBCrowdsourcingCreationPrivacyViewControllerDelegate, FBCrowdsourcingHomeViewDelegate, FBKeyboardObserverDelegate, FBMediaAttachmentPickerControllerDelegate, FBCrowdsourcingCityPickerDelegate>
{
    BOOL _isInitialDisplay;
    CLLocation *_location;
    FBMemPerson *_currentUser;
    FBUserSession *_session;
    FBKeyboardObserver *_keyboardObserver;
    FBKeyboardFocusedViewDisplayer *_keyboardFocusedViewDisplayer;
    FBCrowdsourcingCreationPrivacyViewController *_privacyViewController;
    FBMediaAttachmentPickerController *_photoPickerController;
    UIViewController *_photoPickerViewController;
    FBCrowdsourcingCreationErrorHandleController *_errorHandler;
    FBCrowdsourcingHomeView *_homeView;
    UIView *_spinnerOverlay;
    UITextField *_activeField;
    int _statusBarStyle;
}

@property(nonatomic) BOOL isInitialDisplay; // @synthesize isInitialDisplay=_isInitialDisplay;
@property(nonatomic) int statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
@property(nonatomic) __weak UITextField *activeField; // @synthesize activeField=_activeField;
@property(retain, nonatomic) UIView *spinnerOverlay; // @synthesize spinnerOverlay=_spinnerOverlay;
@property(retain, nonatomic) FBCrowdsourcingHomeView *homeView; // @synthesize homeView=_homeView;
@property(retain, nonatomic) FBCrowdsourcingCreationErrorHandleController *errorHandler; // @synthesize errorHandler=_errorHandler;
@property(retain, nonatomic) UIViewController *photoPickerViewController; // @synthesize photoPickerViewController=_photoPickerViewController;
@property(retain, nonatomic) FBMediaAttachmentPickerController *photoPickerController; // @synthesize photoPickerController=_photoPickerController;
@property(retain, nonatomic) FBCrowdsourcingCreationPrivacyViewController *privacyViewController; // @synthesize privacyViewController=_privacyViewController;
@property(readonly, nonatomic) FBKeyboardFocusedViewDisplayer *keyboardFocusedViewDisplayer; // @synthesize keyboardFocusedViewDisplayer=_keyboardFocusedViewDisplayer;
@property(readonly, nonatomic) FBKeyboardObserver *keyboardObserver; // @synthesize keyboardObserver=_keyboardObserver;
@property(retain, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(retain, nonatomic) FBMemPerson *currentUser; // @synthesize currentUser=_currentUser;
@property(copy, nonatomic) CLLocation *location; // @synthesize location=_location;
- (void).cxx_destruct;
- (BOOL)_isLightContentStatusBarStyle:(int)arg1;
- (void)_createUpdatePhotoActionDialog;
- (void)_didTapRemoveProfilePhotoOption;
- (void)_didTapUpdateProfilePhotoOption;
- (void)_handleTapAddPhotoIcon;
- (void)_showAlertViewWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;
- (BOOL)_hasProfilePhoto;
- (void)_setHomeViewPhoto:(id)arg1;
- (void)_updateHomeViewWithSelectedPhoto:(id)arg1;
- (void)_tapOnView:(id)arg1;
- (void)_showPrivacyViewControllerWithComposerPrivacy:(id)arg1;
- (void)_showPhotoPicker;
- (void)_showFullScreenSpinner;
- (void)_dismissPhotoPicker;
- (void)_didTapDone;
- (void)_didTapCancel;
- (void)_didEnterBackgroundNotification;
- (void)_configKeyboardAndObserver;
- (void)_allowUserInteraction:(BOOL)arg1;
- (void)crowdsourcingCityPickerViewControllerDidCancel;
- (void)mediaAttachmentPickerController:(id)arg1 openURL:(id)arg2;
- (void)mediaAttachmentPickerControllerDidClearMediaAttachments:(id)arg1;
- (void)mediaAttachmentPickerController:(id)arg1 didSelectMediaAttachments:(id)arg2 fromSource:(int)arg3;
- (void)mediaAttachmentPickerControllerPermissionDenied:(id)arg1;
- (void)mediaAttachmentPickerControllerDidCancel:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)keyboardObserver:(id)arg1 keyboardWillHideWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(int)arg5;
- (void)keyboardObserver:(id)arg1 keyboardWillShowWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(int)arg5;
- (void)crowdsourcingCreationPrivacyViewControllerDidTapCancel;
- (void)crowdsourcingCreationPrivacyViewControllerDidUpdatePrivacy:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)crowdsourcingHomeViewDidTapOnRemovePhotoActionSheetOption;
- (void)crowdsourcingHomeViewDidTapOnUpdatePhotoActionSheetOption;
- (void)crowdsourcingHomeViewDidChangeHomeName;
- (void)crowdsourcingHomeViewDidTapOnPrivacySetting;
- (void)crowdsourcingHomeViewDidTapOnCityField;
- (void)crowdsourcingHomeViewDidTapOnAddPhotoIcon;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (int)preferredInterfaceOrientationForPresentation;
- (unsigned int)supportedInterfaceOrientations;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

