//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBDetailComponentController, NSURL, UIViewController;

@protocol FBDetailComponentControllerDelegate <NSObject>
- (id <FBTableViewMutating>)tableViewMutator;
- (void)controller:(FBDetailComponentController *)arg1 openViewController:(UIViewController *)arg2;
- (void)controller:(FBDetailComponentController *)arg1 openURL:(NSURL *)arg2;
@end

