//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBGraphQLConnectionStorePersistentCache : NSObject
{
    id <FBDiskCacheProtocol> _diskCache;
}

- (void).cxx_destruct;
- (void)cacheData:(id)arg1 forKey:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)fetchCachedDataForKey:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)fetchCachedDataForKey:(id)arg1;
- (id)init;
- (id)initWithDiskCache:(id)arg1;

@end

