//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBGraphQLService.h"

@class NSString;

@interface FBGraphQLFatalingService : NSObject <FBGraphQLService>
{
}

- (id)sendQueries:(id)arg1 callbackQueue:(id)arg2 successCallback:(CDUnknownBlockType)arg3 failureCallback:(CDUnknownBlockType)arg4 progressCallback:(CDUnknownBlockType)arg5 configurationCallback:(CDUnknownBlockType)arg6;
- (id)sendQuery:(id)arg1 callbackQueue:(id)arg2 networkRequestThresholdInSeconds:(unsigned int)arg3 cachedResponseCallback:(CDUnknownBlockType)arg4 downloadedResponseCallback:(CDUnknownBlockType)arg5 failureCallback:(CDUnknownBlockType)arg6 progressCallback:(CDUnknownBlockType)arg7 configurationCallback:(CDUnknownBlockType)arg8;
- (id)sendQuery:(id)arg1 callbackQueue:(id)arg2 successCallback:(CDUnknownBlockType)arg3 failureCallback:(CDUnknownBlockType)arg4 progressCallback:(CDUnknownBlockType)arg5 configurationCallback:(CDUnknownBlockType)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

