//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBInlineComposerPromptsProvider.h"
#import "FBInlineComposerPromptsProviderListener.h"

@class FBInlineComposerPrompt, FBInlineComposerPromptsProviderListenerAnnouncer, NSString;

@interface FBInlineComposerTogglePromptsProvider : NSObject <FBInlineComposerPromptsProviderListener, FBInlineComposerPromptsProvider>
{
    FBInlineComposerPromptsProviderListenerAnnouncer *_announcer;
    id <FBInlineComposerPromptsProvider> _provider;
    BOOL _enabled;
    FBInlineComposerPrompt *_currentPrompt;
}

@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) FBInlineComposerPrompt *currentPrompt; // @synthesize currentPrompt=_currentPrompt;
- (void).cxx_destruct;
- (void)promptsProviderDidUpdatePrompt:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (void)didClosePrompt:(id)arg1;
- (void)didDisplayPrompt;
- (void)reloadPrompt;
- (void)_updateCurrentPromptIfNeeded;
- (id)initWithProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

