//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CKComponentProvider.h"
#import "FBComponentTableViewDataSourceAnimationDelegate.h"
#import "FBComponentTableViewDataSourceEventListener.h"
#import "FBComponentTableViewDataSourceSelectionEventListener.h"
#import "FBComposerAudiencePickerController.h"
#import "FBLinearComposerAudiencePickerDataStoreDelegate.h"

@class FBComponentTableViewDataSource, FBLinearComposerAudiencePickerDataStore, FBUserSession, NSString, UITableView;

@interface FBLinearComposerAudiencePickerViewController : UIViewController <FBLinearComposerAudiencePickerDataStoreDelegate, CKComponentProvider, FBComponentTableViewDataSourceSelectionEventListener, FBComponentTableViewDataSourceAnimationDelegate, FBComponentTableViewDataSourceEventListener, FBComposerAudiencePickerController>
{
    FBUserSession *_session;
    FBLinearComposerAudiencePickerDataStore *_dataStore;
    UITableView *_tableView;
    FBComponentTableViewDataSource *_componentTableViewDataSource;
    unsigned int _recentlyExpandedGroupIndex;
    id <FBComposerAudiencePickerControllerDelegate> _delegate;
}

+ (id)componentForModel:(id)arg1 context:(id)arg2;
+ (id)_barButtonItemWithGlyphName:(unsigned int)arg1 color:(id)arg2 accessibilityLabel:(id)arg3 target:(id)arg4 action:(SEL)arg5;
@property(nonatomic) __weak id <FBComposerAudiencePickerControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dataSourceDidEndUpdates:(id)arg1 changeset:(struct Changeset)arg2;
- (struct FBComponentTableViewDataSourceAnimationContext)dataSource:(id)arg1 rowAnimationContextForChangeset:(const struct Changeset *)arg2;
- (BOOL)dataSource:(id)arg1 shouldAnimateApplicationOfChangeset:(const struct Changeset *)arg2;
- (void)dataSource:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)dataStore:(id)arg1 didExpandGroupWithIndex:(unsigned int)arg2;
- (void)dataStore:(id)arg1 selectedAudienceDidChange:(id)arg2;
- (void)dataStore:(id)arg1 didUpdateWithChangeSet:(struct Changeset)arg2;
- (void)taggedEventChanged:(id)arg1;
- (void)taggedAndMentionedUsersChanged:(id)arg1;
- (void)compositionAudienceChanged:(id)arg1;
- (void)showContentState;
- (void)activateFBComposerAudienceDataSourceWithTaggableCollection:(id)arg1;
- (void)pickerControllerWasDismissedByTappingOutsidePopover;
- (void)availablePrivacySettingsChanged:(id)arg1 audienceTouchedByUser:(BOOL)arg2;
- (void)configureWithAvailablePrivacySettings:(id)arg1 selectedAudience:(id)arg2 taggedAndMentionedUsers:(id)arg3 taggedEvent:(id)arg4;
- (void)_onRightBarButtonTap;
- (void)_onLeftBarButtonTap;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

