//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBMention, FBMentionDecorator, NSDictionary, NSString;

@protocol FBMentionDecoratorDelegate <NSObject>
- (void)mentionDecoratorFinishedDetecting:(FBMentionDecorator *)arg1;
- (void)mentionDecorator:(FBMentionDecorator *)arg1 detectedQuery:(NSString *)arg2 context:(id)arg3;

@optional
- (NSDictionary *)mentionDecorator:(FBMentionDecorator *)arg1 attributesForRemovedMention:(FBMention *)arg2;
- (NSDictionary *)mentionDecorator:(FBMentionDecorator *)arg1 attributesForMention:(FBMention *)arg2;
- (void)mentionDecoratorMentionsDidChange:(FBMentionDecorator *)arg1;
@end

