//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FBNearbyPlaceBuilder : NSObject
{
    CDStruct_2c43369c _coordinates;
    NSString *_name;
    NSString *_targetID;
    unsigned int _targetType;
    NSString *_visitorsSubtext;
}

+ (id)aNearbyPlace;
- (void).cxx_destruct;
- (id)withVisitorsSubtext:(id)arg1;
- (id)withTargetType:(unsigned int)arg1;
- (id)withTargetID:(id)arg1;
- (id)withName:(id)arg1;
- (id)withCoordinates:(CDStruct_c3b9c2ee)arg1;
- (id)build;

@end

