//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBNowFeedQueryPollTopFriends : NSObject
{
}

+ (id)graphQLQueryWithCoverHeight:(id)arg1 coverWidth:(id)arg2 device:(id)arg3 favoritesNewer:(id)arg4 feedType:(id)arg5 mediaType:(id)arg6 numFavsToPoll:(id)arg7 scale:(id)arg8 seeFirstEnabled:(id)arg9 tempProfilePicEnabled:(id)arg10 useCoverPreview:(id)arg11;

@end

