//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBPageFollowupFeedUnitQuery : NSObject
{
}

+ (id)graphQLQueryWithDevice:(id)arg1 followupActionType:(id)arg2 mediaType:(id)arg3 renderLocation:(id)arg4 scale:(id)arg5 targetID:(id)arg6 videoThumbnailSize:(id)arg7;

@end

