//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBModelObjectProtocol.h"

@class FBMemImage, NSString;

@protocol FBQueriedEntityWithImageFieldsProtocol <FBModelObjectProtocol>
- (FBMemImage *)image;
- (NSString *)graphQLID;
@end

