//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "FBFIGConfig.h"

@class NSArray, NSString, UIColor, UIFont;

@interface FBSegmentedViewConfig : FBValueObject <FBFIGConfig>
{
    BOOL _momentary;
    NSArray *_items;
    unsigned int _size;
    unsigned int _type;
    float _regularSizeHeight;
    float _smallSizeHeight;
    int _selectedIndex;
    UIFont *_titleFallbackFont;
    UIColor *_titleFallbackColor;
    UIFont *_highlightedTitleFallbackFont;
    UIColor *_highlightedTitleFallbackColor;
    UIColor *_dividerColor;
    unsigned int _dividerThickness;
    float _topLineThickness;
    UIColor *_topLineColor;
    float _bottomLineThickness;
    UIColor *_bottomLineColor;
    UIColor *_tintColor;
    float _scrollItemPadding;
    float _scrollItemMinimumWidth;
    float _scrollItemMaximumWidth;
    struct UIOffset _titleOffset;
    struct UIEdgeInsets _dividerInsets;
}

+ (id)newWithItems:(id)arg1 size:(unsigned int)arg2 type:(unsigned int)arg3 momentary:(BOOL)arg4 regularSizeHeight:(float)arg5 smallSizeHeight:(float)arg6 selectedIndex:(int)arg7 titleOffset:(struct UIOffset)arg8 titleFallbackFont:(id)arg9 titleFallbackColor:(id)arg10 highlightedTitleFallbackFont:(id)arg11 highlightedTitleFallbackColor:(id)arg12 dividerColor:(id)arg13 dividerThickness:(unsigned int)arg14 dividerInsets:(struct UIEdgeInsets)arg15 topLineThickness:(float)arg16 topLineColor:(id)arg17 bottomLineThickness:(float)arg18 bottomLineColor:(id)arg19 tintColor:(id)arg20 scrollItemPadding:(float)arg21 scrollItemMinimumWidth:(float)arg22 scrollItemMaximumWidth:(float)arg23;
@property(readonly, nonatomic) float scrollItemMaximumWidth; // @synthesize scrollItemMaximumWidth=_scrollItemMaximumWidth;
@property(readonly, nonatomic) float scrollItemMinimumWidth; // @synthesize scrollItemMinimumWidth=_scrollItemMinimumWidth;
@property(readonly, nonatomic) float scrollItemPadding; // @synthesize scrollItemPadding=_scrollItemPadding;
@property(readonly, copy, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(readonly, copy, nonatomic) UIColor *bottomLineColor; // @synthesize bottomLineColor=_bottomLineColor;
@property(readonly, nonatomic) float bottomLineThickness; // @synthesize bottomLineThickness=_bottomLineThickness;
@property(readonly, copy, nonatomic) UIColor *topLineColor; // @synthesize topLineColor=_topLineColor;
@property(readonly, nonatomic) float topLineThickness; // @synthesize topLineThickness=_topLineThickness;
@property(readonly, nonatomic) struct UIEdgeInsets dividerInsets; // @synthesize dividerInsets=_dividerInsets;
@property(readonly, nonatomic) unsigned int dividerThickness; // @synthesize dividerThickness=_dividerThickness;
@property(readonly, copy, nonatomic) UIColor *dividerColor; // @synthesize dividerColor=_dividerColor;
@property(readonly, copy, nonatomic) UIColor *highlightedTitleFallbackColor; // @synthesize highlightedTitleFallbackColor=_highlightedTitleFallbackColor;
@property(readonly, copy, nonatomic) UIFont *highlightedTitleFallbackFont; // @synthesize highlightedTitleFallbackFont=_highlightedTitleFallbackFont;
@property(readonly, copy, nonatomic) UIColor *titleFallbackColor; // @synthesize titleFallbackColor=_titleFallbackColor;
@property(readonly, copy, nonatomic) UIFont *titleFallbackFont; // @synthesize titleFallbackFont=_titleFallbackFont;
@property(readonly, nonatomic) struct UIOffset titleOffset; // @synthesize titleOffset=_titleOffset;
@property(readonly, nonatomic) int selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(readonly, nonatomic) float smallSizeHeight; // @synthesize smallSizeHeight=_smallSizeHeight;
@property(readonly, nonatomic) float regularSizeHeight; // @synthesize regularSizeHeight=_regularSizeHeight;
@property(readonly, nonatomic) BOOL momentary; // @synthesize momentary=_momentary;
@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned int size; // @synthesize size=_size;
@property(readonly, copy, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (id)_initWithItems:(id)arg1 size:(unsigned int)arg2 type:(unsigned int)arg3 momentary:(BOOL)arg4 regularSizeHeight:(float)arg5 smallSizeHeight:(float)arg6 selectedIndex:(int)arg7 titleOffset:(struct UIOffset)arg8 titleFallbackFont:(id)arg9 titleFallbackColor:(id)arg10 highlightedTitleFallbackFont:(id)arg11 highlightedTitleFallbackColor:(id)arg12 dividerColor:(id)arg13 dividerThickness:(unsigned int)arg14 dividerInsets:(struct UIEdgeInsets)arg15 topLineThickness:(float)arg16 topLineColor:(id)arg17 bottomLineThickness:(float)arg18 bottomLineColor:(id)arg19 tintColor:(id)arg20 scrollItemPadding:(float)arg21 scrollItemMinimumWidth:(float)arg22 scrollItemMaximumWidth:(float)arg23;
- (float)height;
- (float)dividerWidth;
- (id)highlightedTitleWithFontAndColorFallback:(id)arg1;
- (id)titleWithFontAndColorFallback:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

