//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBComposerAlertPresentationListener.h"
#import "FBPublicationErrorAlertListener.h"
#import "FBPublicationErrorAlertPresenter.h"

@class NSString;

@interface FBSystemPublicationErrorAlertPresenter : NSObject <FBPublicationErrorAlertListener, FBComposerAlertPresentationListener, FBPublicationErrorAlertPresenter>
{
    id <FBComposerAlertPresenter> _alertPresenter;
    BOOL _isPresentingAnAlert;
    id <FBPublicationErrorAlertPresentationListener> _listener;
    unsigned int _reportProblemStatus;
}

- (void).cxx_destruct;
- (void)presentAlert:(id)arg1 actionListener:(id)arg2;
- (void)presentedAlertDismissed;
- (void)reportThisProblemButtonPressed;
- (void)okButtonPressed;
- (void)presentAlertForError:(id)arg1;
- (void)doNotAllowUserToReportProblem;
- (void)allowUserToReportProblem;
- (id)init;
- (id)initWithListener:(id)arg1 presentingViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

