//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBWebImageSpecifier.h"

@class FBWebImageNetworkSpecifierInfoNode, NSArray, NSURL;

@protocol FBWebImageNetworkFetchFirstSpecifier <FBWebImageSpecifier>
@property(readonly, nonatomic) unsigned int targetImageFlag;
@property(readonly, copy, nonatomic) NSArray *allInfoURLsSortedByDescImageFlag;
- (FBWebImageNetworkSpecifierInfoNode *)infoNodeForURL:(NSURL *)arg1;
@end

