//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollViewDelegate.h"

@class FBZoomingPhotoView;

@protocol FBZoomingPhotoViewDelegate <UIScrollViewDelegate>

@optional
- (void)zoomingPhotoViewDidLayoutSubviews:(FBZoomingPhotoView *)arg1;
- (void)zoomingPhotoViewDidResetSize:(FBZoomingPhotoView *)arg1;
@end

