//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"

@class ALAssetsLibrary, NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface RCTImageLoader : NSObject <RCTBridgeModule>
{
    ALAssetsLibrary *_assetsLibrary;
    RCTBridge *_bridge;
}

+ (BOOL)isRemoteImage:(id)arg1;
+ (BOOL)isAssetLibraryImage:(id)arg1;
+ (void)load;
+ (id)moduleName;
@property(nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (CDUnknownBlockType)loadImageWithTag:(id)arg1 size:(struct CGSize)arg2 scale:(float)arg3 resizeMode:(int)arg4 progressBlock:(CDUnknownBlockType)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)assetsLibrary;
- (CDUnknownBlockType)loadImageWithTag:(id)arg1 callback:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

