//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBCropViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIButton;

@interface THCoverPhotoCropViewController : FBCropViewController <UIGestureRecognizerDelegate>
{
    UIButton *_confirmButton;
    UIButton *_cancelButton;
}

- (void).cxx_destruct;
- (void)_confirmButtonTapped:(id)arg1;
- (void)_cancelButtonTapped:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithImage:(id)arg1 contentFrame:(struct CGRect)arg2 groupName:(id)arg3 delegate:(id)arg4;
- (id)initWithImage:(id)arg1 contentFrame:(struct CGRect)arg2 previousCrop:(id)arg3 delegate:(id)arg4 behavior:(int)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

