//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FBItemView_DEPRECATED, FBMemGroupsYouShouldJoinEdge, FBNetworkImageView, FBUserSession, UIButton, UIView;

@interface THSuggestedGroupCell : UITableViewCell
{
    FBUserSession *_session;
    FBMemGroupsYouShouldJoinEdge *_groupsYouShouldJoinEdge;
    FBItemView_DEPRECATED *_summaryView;
    FBNetworkImageView *_coverPhotoView;
    UIView *_groupPogView;
    UIButton *_joinButton;
    UIButton *_xoutButton;
    id <THSuggestedGroupCellDelegate> _delegate;
}

@property(nonatomic) __weak id <THSuggestedGroupCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_sizeToFitActionButton:(id)arg1;
- (void)_xoutButtonTapped:(id)arg1;
- (void)_setJoinState:(id)arg1;
- (void)_joinButtonTapped:(id)arg1;
- (id)accessibilityElements;
- (void)setHasSeparator:(BOOL)arg1;
- (void)setGroupsYouShouldJoinEdge:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)prepareForReuse;
- (id)initWithSession:(id)arg1 reuseIdentifier:(id)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

