//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSOrderedSet;

@interface FBAggregatedEntitiesAtRange : NSObject
{
    NSNumber *_offset;
    NSNumber *_length;
    NSOrderedSet *_sampleEntities;
}

+ (id)entityName;
+ (id)graphQLTypeName;
@property(copy, nonatomic) NSOrderedSet *sampleEntities; // @synthesize sampleEntities=_sampleEntities;
@property(copy, nonatomic) NSNumber *length; // @synthesize length=_length;
@property(copy, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
- (void)dealloc;

@end

