//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBWebPivotsToolbarViewControllerDelegate.h"

@class FBUserSession, FBWebViewContainerController, FBWebViewController, NSString;

@interface FBAttachmentPickerWebViewController : NSObject <FBWebPivotsToolbarViewControllerDelegate>
{
    FBUserSession *_session;
    id <FBAttachmentPickerWebViewControllerDelegate> _delegate;
    FBWebViewController *_webViewController;
    FBWebViewContainerController *_containerWebViewController;
    unsigned int _entryType;
}

- (void).cxx_destruct;
- (void)webPivotsToolbarViewControllerDidSelectForwardButton:(id)arg1;
- (void)webPivotsToolbarViewControllerDidSelectBackButton:(id)arg1;
- (void)webPivotsToolbarViewControllerDidSelectCloseButton:(id)arg1;
- (void)_onTapWebViewFooterAddLink:(id)arg1;
- (id)_webViewToolbar;
- (id)webViewController;
- (void)loadURL:(id)arg1;
- (id)initWithSession:(id)arg1 delegate:(id)arg2 entryType:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

