//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBDBLLoginRequest;

@interface FBAuthenticationDeviceBasedLoginHandler : NSObject
{
    FBDBLLoginRequest *_loginRequest;
}

- (void).cxx_destruct;
- (void)cancel;
- (void)submitDeviceBasedLoginWithUserID:(id)arg1 nonce:(id)arg2 pin:(id)arg3 machineID:(id)arg4 success:(CDUnknownBlockType)arg5 error:(CDUnknownBlockType)arg6;

@end

