//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBFIGConfigBuilder.h"

@class NSString, UIColor, UIFont, UIImage;

@interface FBBadgeViewConfigBuilder : NSObject <FBFIGConfigBuilder>
{
    unsigned int _contentMode;
    int _badgeCount;
    int _maxBadgeCount;
    NSString *_badgeValue;
    UIColor *_backgroundColor;
    UIImage *_badgeViewImage;
    UIFont *_countLabelFont;
    UIColor *_countLabelTextColor;
    struct UIEdgeInsets _padding;
    struct UIEdgeInsets _badgeViewImageCapInsets;
}

+ (id)builderForInstance:(id)arg1;
+ (id)builderFromConfig:(id)arg1;
+ (id)builderIgnoringClassLevelOverrides;
+ (id)builder;
+ (id)builderForStyle:(unsigned int)arg1;
@property(copy, nonatomic) UIColor *countLabelTextColor; // @synthesize countLabelTextColor=_countLabelTextColor;
@property(copy, nonatomic) UIFont *countLabelFont; // @synthesize countLabelFont=_countLabelFont;
@property(nonatomic) struct UIEdgeInsets badgeViewImageCapInsets; // @synthesize badgeViewImageCapInsets=_badgeViewImageCapInsets;
@property(copy, nonatomic) UIImage *badgeViewImage; // @synthesize badgeViewImage=_badgeViewImage;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(copy, nonatomic) NSString *badgeValue; // @synthesize badgeValue=_badgeValue;
@property(nonatomic) int maxBadgeCount; // @synthesize maxBadgeCount=_maxBadgeCount;
@property(nonatomic) int badgeCount; // @synthesize badgeCount=_badgeCount;
@property(nonatomic) unsigned int contentMode; // @synthesize contentMode=_contentMode;
- (void).cxx_destruct;
- (id)_init;
- (id)build;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

