//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBCameraComponentModelBuilder : NSObject
{
    BOOL _cameraAccessGranted;
    int _captureDevicePosition;
    unsigned int _captureState;
    int _deviceOrientation;
}

+ (id)cameraComponentModelFromExistingCameraComponentModel:(id)arg1;
+ (id)cameraComponentModel;
- (id)withDeviceOrientation:(int)arg1;
- (id)withCaptureState:(unsigned int)arg1;
- (id)withCaptureDevicePosition:(int)arg1;
- (id)withCameraAccessGranted:(BOOL)arg1;
- (id)build;

@end

