//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBContextualTimelineTopContextItemQuery : NSObject
{
}

+ (id)graphQLQueryWithMediaType:(id)arg1 renderLocation:(id)arg2 rootID:(id)arg3 scale:(id)arg4 timelineContextItemImageSize:(id)arg5 topItemType:(id)arg6;

@end

