//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying.h"

@class NSDictionary, NSString;

@interface FBColdStartReasonPipelineComputation : FBValueObject <NSCopying>
{
    BOOL _shouldLog;
    NSString *_reason;
    NSDictionary *_loggingContext;
}

@property(readonly, nonatomic) BOOL shouldLog; // @synthesize shouldLog=_shouldLog;
@property(readonly, copy, nonatomic) NSDictionary *loggingContext; // @synthesize loggingContext=_loggingContext;
@property(readonly, copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
- (void).cxx_destruct;
- (id)initWithReason:(id)arg1 loggingContext:(id)arg2 shouldLog:(BOOL)arg3;

@end

