//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBGraphQLQuery, NSDictionary, NSManagedObjectContext;

@protocol FBGraphQLResponseParserImpl <NSObject>
@property(nonatomic) BOOL allowResponsesWithStrippedNulls;
@property(readonly, retain, nonatomic) id <FBGraphQLObjectFactory> objectFactory;
- (NSDictionary *)parse:(NSDictionary *)arg1 query:(FBGraphQLQuery *)arg2 managedObjectContext:(NSManagedObjectContext *)arg3 error:(id *)arg4;
@end

