//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBUserSession, NSMutableDictionary;

@interface FBGraphSearchServerSuggestionCache : NSObject
{
    FBUserSession *_session;
    NSMutableDictionary *_suggestionCache;
}

- (void).cxx_destruct;
- (id)suggestionsFromCache:(id)arg1 numRequested:(unsigned int)arg2;
- (void)cacheServerSuggestions:(id)arg1 forInputString:(id)arg2;
- (id)init;
- (id)initWithSession:(id)arg1;

@end

