//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBContactImportPermissionListener.h"
#import "FBImportedContactsSyncListener.h"

@class FBDeviceImportIdStore, FBLocalContactSyncBlocker, FBLocalContactsSyncCancellationProcessor, FBLocalContactsSyncEventTranslator, FBLocalContactsSyncStatusListenerAnnouncer, FBSyncedLocalContactsDeduplicator, FBSyncedLocalContactsStoreUpdater, NSObject<OS_dispatch_queue>, NSString;

@interface FBLocalContactsSyncQueueDispatcher : NSObject <FBContactImportPermissionListener, FBImportedContactsSyncListener>
{
    void *_addressBook;
    FBLocalContactsSyncCancellationProcessor *_cancellationProcessor;
    id <FBLocalContactsSyncCancellationListener> _cancellationProcessorCancellationEventsToCancellationListenerDispatcher;
    id <FBImportedContactsSyncListener> _contactImportEventsToSyncBlockerDispatcher;
    id <FBContactsStore> _contactsStore;
    FBDeviceImportIdStore *_deviceImportIdStore;
    FBLocalContactsSyncStatusListenerAnnouncer *_localContactsEventAnnouncer;
    FBSyncedLocalContactsDeduplicator *_syncedLocalContactsDeduplicator;
    FBSyncedLocalContactsStoreUpdater *_syncedLocalContactsStoreUpdater;
    FBLocalContactsSyncEventTranslator *_syncEventTranslator;
    id <FBLocalContactsSyncStatusListener> _syncEventTranslatorSyncEventsToListenerDispatcher;
    FBLocalContactSyncBlocker *_localContactsSyncBlocker;
    NSObject<OS_dispatch_queue> *_localContactsQueue;
    NSObject<OS_dispatch_queue> *_queueOntoWhichEventsAreDispatched;
}

- (void)contactImportCancelled;
- (void)contactImportFailedDueToContactImportingBeingLocked;
- (void)contactImportFailed;
- (void)contactImportCompleted;
- (void)contactImportProgressedWithStatus:(id)arg1;
- (void)contactImportStartedForNumberOfContacts:(unsigned int)arg1;
- (void)_stopMonitoringAddressbookImmediately;
- (void)stopMonitoringAddressbook;
- (void)startMonitoringAddressbook;
- (void)contactImportingDisallowed;
- (void)contactImportingAllowed;
- (void)syncContacts;
- (void)dealloc;
- (id)initWithNetworker:(id)arg1 session:(id)arg2 queueOntoWhichEventsAreDispatched:(id)arg3 listener:(id)arg4 cancellationListener:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

