//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBMemModelObject.h"

#import "FBDisplayableMedia.h"
#import "FBFeedbackTargetProtocol.h"
#import "FBMultiResolutionImageSourceProtocol.h"
#import "FBPhotoTaggingAssetProtocol.h"
#import "FBQueriedEntityFieldsProtocol.h"
#import "FBQueriedGoodwillThrowbackAccentImageFieldsProtocol.h"
#import "FBQueriedMediaFieldsProtocol.h"
#import "FBQueriedNodeFieldsProtocol.h"
#import "FBQueriedPlaceQuestionValueFieldsProtocol.h"
#import "FBSearchPivotsSource.h"
#import "FBShareable.h"

@class NSString;

@interface FBMemPhoto : FBMemModelObject <FBDisplayableMedia, FBFeedbackTargetProtocol, FBMultiResolutionImageSourceProtocol, FBPhotoTaggingAssetProtocol, FBSearchPivotsSource, FBShareable, FBQueriedNodeFieldsProtocol, FBQueriedEntityFieldsProtocol, FBQueriedMediaFieldsProtocol, FBQueriedGoodwillThrowbackAccentImageFieldsProtocol, FBQueriedPlaceQuestionValueFieldsProtocol>
{
}

+ (unsigned int)supportedImageFlags;
- (float)aspectRatio;
- (id)mediaID;
- (id)accessibilityLabel;
- (id)tagsEdges;
- (id)faceBoxesEdges;
- (id)assetID;
- (void)taggableSourceAvatarWithSession:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)shareableImage;
- (id)shareableImageURL;
- (id)shareableDescription;
- (id)shareableSubtitle;
- (id)shareableTitle;
- (id)shareableType;
- (id)shareableText;
- (id)shareableURL;
- (id)shareableID;
- (id)streamingImageSource;
- (id)imageClosestToFlag:(unsigned int)arg1;
- (id)place;
- (BOOL)isFullInfoLoaded;
- (id)accessibilityLabelStringIncludingCaption:(BOOL)arg1;
- (id)accessibilityLabelString;
- (id)supportedImageURLs;
- (id)tagsArray;
- (id)faceBoxesArray;
- (id)fbid;
- (struct CGSize)size;
- (struct CGPoint)focusPoint;
- (BOOL)isDisplayable;
- (unsigned int)imageFlagClosestToSize:(float)arg1;
- (unsigned int)imageFlagClosestToFlag:(unsigned int)arg1;
- (struct CGSize)imageSizeForFlag:(unsigned int)arg1;
- (id)imageSourceForFlag:(unsigned int)arg1 skipCheckingStreamImage:(BOOL)arg2;
- (id)imageSourceForFlag:(unsigned int)arg1;
- (id)imageForFlag:(unsigned int)arg1;
- (id)entityURL;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

