//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBNavigationBarTitleControl, FBNavigationBarTitleControlConfig, UIBarButtonItem, UINavigationItem;

@interface FBMediaPickerNavigationItemManager : NSObject
{
    FBNavigationBarTitleControlConfig *_config;
    UIBarButtonItem *_leftBarButtonItem;
    UIBarButtonItem *_rightBarButtonItem;
    FBNavigationBarTitleControl *_titleControl;
    UINavigationItem *_navigationItem;
    id <FBMediaPickerNavigationItemManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBMediaPickerNavigationItemManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setTitleViewToTitleControlIfNeeded:(id)arg1;
- (void)_didTapTitleView;
- (void)_didTapRightBarButton;
- (void)_didTapLeftBarButton;
- (void)updateTitle:(id)arg1;
- (void)updateSubtitle:(id)arg1;
- (void)setShowTitleView:(BOOL)arg1;
- (void)setRightBarButtonTitle:(id)arg1;
- (void)setRightBarButtonEnabled:(BOOL)arg1;
- (void)setBarButtonOption:(unsigned int)arg1;
- (id)initWithNavigationItem:(id)arg1;

@end

