//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface FBMLocationAttachmentDataToSend : NSObject <NSCopying>
{
    unsigned int _subtype;
    double _coordinates_latitude;
    double _coordinates_longitude;
    BOOL _coordinates_isCurrentLocation;
    NSString *_place_placeID;
}

+ (id)placeWithPlaceID:(id)arg1;
+ (id)coordinatesWithLatitude:(double)arg1 longitude:(double)arg2 isCurrentLocation:(BOOL)arg3;
- (void).cxx_destruct;
- (void)matchCoordinates:(CDUnknownBlockType)arg1 place:(CDUnknownBlockType)arg2;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

