//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBCancelable.h"
#import "FBClassProvidable.h"
#import "FBMDetachable.h"
#import "FBNetworkerRequestDelegate.h"

@class FBMDetchedNetworkRequestsQueue, FBMThreadSummaryUpdate, FBSimpleNetworkerRequest, FBUserSession, MNMessagingRegionHeaderHelper, MNThreadUpdateService, NSString;

@interface FBMLeaveGroupThreadRequester : NSObject <FBNetworkerRequestDelegate, FBClassProvidable, FBCancelable, FBMDetachable>
{
    FBUserSession *_userSession;
    FBMDetchedNetworkRequestsQueue *_detachedQueue;
    NSString *_userId;
    NSString *_threadFbId;
    MNThreadUpdateService *_threadUpdateService;
    id <MNAuthenticationManager> _authenticationManager;
    MNMessagingRegionHeaderHelper *_messagingRegionHeaderHelper;
    id <FBMLeaveGroupThreadRequesterDelegate> _delegate;
    FBSimpleNetworkerRequest *_networkRequest;
    BOOL _requestFinished;
    FBMThreadSummaryUpdate *_deleteUpdate;
}

@property(readonly, copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (void)_didFailWithError:(id)arg1;
- (void)networkerRequest:(id)arg1 didFail:(id)arg2 status:(id)arg3;
- (void)networkerRequest:(id)arg1 didSucceed:(id)arg2 status:(id)arg3;
- (void)_cleanUpDetachedState;
- (void)detach;
- (void)cancel;
- (void)configureAndRequestUserId:(id)arg1 toLeaveThreadFbId:(id)arg2 withDelegate:(id)arg3;
- (void)configureAndRequestLoggedInUserToLeaveThreadWithFbId:(id)arg1 withDelegate:(id)arg2;
- (id)initWithProviderMapData:(id)arg1;
- (id)initWithUserSession:(id)arg1 detachedQueue:(id)arg2 authenticaionManager:(id)arg3 threadUpdateService:(id)arg4 messagingRegionHeaderHelper:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

