//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@protocol FBMProfileURLUtils <NSObject>
- (NSURL *)profileURLForAppOrMSiteWithUID:(NSString *)arg1 identityType:(unsigned int)arg2;
- (NSURL *)groupURLForAppOrMSiteWithUID:(NSString *)arg1;
- (NSURL *)pageURLForAppOrMSiteWithUID:(NSString *)arg1;
- (NSURL *)personURLForAppOrMSiteWithUID:(NSString *)arg1;
@end

