//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class FBFourRoundedCornerView, UIColor;

@interface FBMRoundedCornerImageView : UIImageView
{
    FBFourRoundedCornerView *_roundedCornerView;
    UIColor *_cornerColor;
}

- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithColor:(id)arg1 radius:(float)arg2;
- (id)initWithColor:(id)arg1;

@end

