//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FBMNetworkMonitorController, FBMNetworkProtocolController, FBMSPDataStore, FBMobileConfigFactory, FBUserSession, NSString, UISwitch, UITableView;

@interface FBMSPSettingsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    UISwitch *_syncProtocolSwitch;
    FBMSPDataStore *_dataStore;
    FBUserSession *_session;
    FBMNetworkProtocolController *_networkProtocolController;
    FBMNetworkMonitorController *_networkMonitorController;
    FBMobileConfigFactory *_mobileConfigFactory;
    id <FBMNetworkProtocolChangeListener> _networkProtocolChangeListenerDispatcher;
}

- (void).cxx_destruct;
- (void)_updateSyncProtocolSwitchStatus;
- (void)_networkMonitorChanged:(id)arg1;
- (void)_syncProtocolChanged:(id)arg1;
- (id)_version;
- (void)networkProtocolDidChange:(unsigned int)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

