//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBPublicationResponse, NSError;

@protocol FBPublishingRequestSenderDelegate <NSObject>
- (void)publishDidCancel;
- (void)publishDidFail:(NSError *)arg1 status:(id <FBNetworkerRequestStatus>)arg2 numberOfRequestsSent:(int)arg3;
- (void)publishDidSucceed:(FBPublicationResponse *)arg1 status:(id <FBNetworkerRequestStatus>)arg2 numberOfRequestsSent:(int)arg3;
- (void)publishDidStart;
@end

