//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBStickerResourceTypeConfigProvider;

@interface FBStickerResourceImageConverter : NSObject
{
    FBStickerResourceTypeConfigProvider *_resourceTypeConfigProvider;
}

- (void).cxx_destruct;
- (id)imageForData:(id)arg1 fileExtension:(id)arg2;
- (id)imageForData:(id)arg1 resourceType:(unsigned int)arg2;
- (id)initWithResourceTypeConfigProvider:(id)arg1;

@end

