//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol FBVideoAssetExporter <NSObject>
@property(readonly, nonatomic) CDStruct_1b6d18a9 outputDuration;
@property(readonly, nonatomic) long long estimatedOutputFileLength;
- (void)cancelExportWithCompletionBlock:(void (^)(void))arg1;
- (void)exportAsynchronouslyWithProgress:(void (^)(float))arg1 completion:(void (^)(NSString *, NSString *, NSError *))arg2;

@optional
- (void)exportAsynchronouslyWithProgress:(void (^)(float))arg1 segmentCompletion:(void (^)(FBAVAssetSegment *))arg2 completion:(void (^)(NSString *, NSString *, NSError *))arg3;
@end

