//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol FBWebRTCCapabilities <NSObject>
@property(readonly, nonatomic, getter=isWebInteropSupported) BOOL webInteropSupported;
@property(readonly, nonatomic, getter=isDirectVideoCallingEnabled) BOOL directVideoCallingEnabled;
@property(readonly, nonatomic, getter=isVideoCallingEnabled) BOOL videoCallingEnabled;
@property(readonly, nonatomic, getter=isVoipBlockedByCountry) BOOL voipBlockedByCountry;
@property(readonly, nonatomic, getter=isVoipEnabled) BOOL voipEnabled;
@end

