//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSessionClassProvidable.h"
#import "NSObject.h"

@class UIView<MNAttachmentView>;

@protocol MNAttachmentStyleViewFactory <NSObject, FBSessionClassProvidable>
- (Class)attachmentViewClass;
- (UIView<MNAttachmentView> *)newAttachmentView;

@optional
- (id <MNMessageCellElementController>)newAttachmentViewController;
@end

