//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MNLoadingIndicator, UIButton, UIColor, UIImage, UIImageView, UILabel;

@interface MNAudioPlayerControlsView : UIView
{
    MNLoadingIndicator *_loadingIndicator;
    unsigned int _state;
    UIView *_patternView;
    UIButton *_playButton;
    UILabel *_timerPanelLabel;
    UIImageView *_timerPanelBackground;
    UIImage *_playButtonBackground;
    UIImage *_pauseButtonBackground;
    UIImage *_patternLabelBackground;
    UIImage *_timerPanelBackgroundImage;
    UIColor *_timerTextColor;
    double _audioDuration;
    struct MNBubbleViewAttributes _bubbleAttributes;
}

@property(retain, nonatomic) UIColor *timerTextColor; // @synthesize timerTextColor=_timerTextColor;
@property(retain, nonatomic) UIImage *timerPanelBackgroundImage; // @synthesize timerPanelBackgroundImage=_timerPanelBackgroundImage;
@property(retain, nonatomic) UIImage *patternLabelBackground; // @synthesize patternLabelBackground=_patternLabelBackground;
@property(retain, nonatomic) UIImage *pauseButtonBackground; // @synthesize pauseButtonBackground=_pauseButtonBackground;
@property(retain, nonatomic) UIImage *playButtonBackground; // @synthesize playButtonBackground=_playButtonBackground;
@property(retain, nonatomic) UIImageView *timerPanelBackground; // @synthesize timerPanelBackground=_timerPanelBackground;
@property(retain, nonatomic) UILabel *timerPanelLabel; // @synthesize timerPanelLabel=_timerPanelLabel;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UIView *patternView; // @synthesize patternView=_patternView;
@property(nonatomic) double audioDuration; // @synthesize audioDuration=_audioDuration;
@property(nonatomic) struct MNBubbleViewAttributes bubbleAttributes; // @synthesize bubbleAttributes=_bubbleAttributes;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)_cancelLoadingAnimation;
- (void)_startLoadingAnimation;
- (id)_durationLabel;
- (void)_layoutSubiews;
- (void)resizeView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

