//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MNPresentableDialog.h"

@class MNImportedContactCardHostView, NSString;

@interface MNContactImportDialogViewController : UIViewController <MNPresentableDialog>
{
    id <MNContactImportDialogDismissalListener> _dismissalListener;
}

@property(nonatomic) __weak id <MNContactImportDialogDismissalListener> dismissalListener; // @synthesize dismissalListener=_dismissalListener;
- (void).cxx_destruct;
- (BOOL)willOpenKeyboardOnAppear;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)displayView:(id)arg1;
- (void)dismiss;
- (void)loadView;
- (id)initWithDismissalListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) MNImportedContactCardHostView *view; // @dynamic view;

@end

