//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying.h"

@class MNCommerceListViewModel, NSArray, NSString;

@interface MNCommerceDeliveryUpdateInformationViewModel : FBValueObject <NSCopying>
{
    NSString *_scheduledDeliveryDate;
    NSArray *_addressLines;
    NSString *_shippingMethod;
    MNCommerceListViewModel *_listViewModel;
}

@property(readonly, copy, nonatomic) MNCommerceListViewModel *listViewModel; // @synthesize listViewModel=_listViewModel;
@property(readonly, copy, nonatomic) NSString *shippingMethod; // @synthesize shippingMethod=_shippingMethod;
@property(readonly, copy, nonatomic) NSArray *addressLines; // @synthesize addressLines=_addressLines;
@property(readonly, copy, nonatomic) NSString *scheduledDeliveryDate; // @synthesize scheduledDeliveryDate=_scheduledDeliveryDate;
- (void).cxx_destruct;
- (id)initWithScheduledDeliveryDate:(id)arg1 addressLines:(id)arg2 shippingMethod:(id)arg3 listViewModel:(id)arg4;

@end

