//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class CLLocation, FBNearbyCache, FBNearbyDataSet, FBTimeThrottler, FBUserSession, NSString;

@interface MNLocationPickerNearbyPlacesViewController : UITableViewController
{
    FBUserSession *_session;
    FBNearbyCache *_nearbyCache;
    FBNearbyDataSet *_nearbyPlacesDataSet;
    FBNearbyDataSet *_searchResultsDataSet;
    FBTimeThrottler *_searchThrottler;
    NSString *_searchQuery;
    CLLocation *_searchCurrentLocation;
    NSString *_placePickerSessionId;
    id <MNLocationPickerNearbyPlacesViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <MNLocationPickerNearbyPlacesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_logEvent:(id)arg1 withDataSet:(id)arg2 extra:(id)arg3;
- (void)_startNewAnalyticsSession;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)_dataSetForTableView:(id)arg1;
- (void)_updateSearchResultsWithDataSet:(id)arg1;
- (void)_updateNearbyPlacesWithDataSet:(id)arg1;
- (void)_sendNewSearchRequest;
- (void)_getNearbyPlacesWithLocation:(id)arg1 query:(id)arg2 success:(CDUnknownBlockType)arg3;
- (void)_scrollToTop;
- (void)searchNearbyPlacesWithQuery:(id)arg1 location:(id)arg2;
- (void)searchNearbyPlacesWithLocation:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithSession:(id)arg1;

@end

