//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBClassProvidable.h"
#import "MNMediaPreviewActionSheetViewControllerDelegate.h"

@class FBAnalytics, MNMediaPreviewActionSheetViewController, MNTextAndAttachmentForwardContent, NSString;

@interface MNMediaPreviewActionSheetPresenter : NSObject <MNMediaPreviewActionSheetViewControllerDelegate, FBClassProvidable>
{
    FBAnalytics *_analytics;
    NSString *_attributionAppId;
    MNTextAndAttachmentForwardContent *_replyContent;
    id <MNMediaActionSheetPresentationListener> _listener;
    MNMediaPreviewActionSheetViewController *_presentedVC;
    id <MNModalPresentation> _modalPresenter;
    id <MNMediaPreviewActionSheetPresenterDelegate> _delegate;
}

@property(nonatomic) __weak id <MNMediaPreviewActionSheetPresenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_analyticsExtras;
- (void)mediaPreviewActionSheetViewController:(id)arg1 didTapAttribution:(id)arg2;
- (void)mediaPreviewActionSheetViewControllerDidDeselectContent:(id)arg1;
- (void)mediaPreviewActionSheetViewController:(id)arg1 didTapEditContent:(id)arg2;
- (void)mediaPreviewActionSheetViewController:(id)arg1 didSendContent:(id)arg2;
- (void)mediaPreviewActionSheetViewControllerDidCancel:(id)arg1;
- (void)dismissAnimated:(BOOL)arg1;
- (void)presentActionSheetWithViewController:(id)arg1 attributionViewModel:(id)arg2;
- (void)presentActionSheetWithContent:(id)arg1 delay:(double)arg2 inThreadWithKey:(id)arg3;
- (void)dealloc;
- (id)initWithProviderMapData:(id)arg1;
- (id)initWithModalPresenter:(id)arg1 analytics:(id)arg2 listener:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

