//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MNMessageSendQueueMutationListening.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface MNMessageSendQueueDiskHandler : NSObject <MNMessageSendQueueMutationListening>
{
    id <MNMessageSendQueueDiskHandlingDelegate> _delegate;
    id <MNMessageSendQueueQuerying> _sendQueueQuerier;
    id <MNMessageSendStateQuerying> _sendStateQuerier;
    id <MNMessageSendQueueRestorationListening> _listener;
    NSObject<OS_dispatch_queue> *_listenerQueue;
    NSObject<OS_dispatch_queue> *_diskHandlingQueue;
}

- (void).cxx_destruct;
- (void)didRemoveMessageFromSendQueue:(id)arg1;
- (void)didAddMessageToSendQueue:(id)arg1 sendStateInfo:(id)arg2;
- (void)_didRestoreSendQueues:(id)arg1;
- (void)_restoreAllSendQueues;
- (void)_persistAllSendQueues;
- (id)initWithDiskHandlingDelegate:(id)arg1 sendQueueQuerier:(id)arg2 sendStateQuerier:(id)arg3 listener:(id)arg4 listenerQueue:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

