//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MNPaymentsFlowSessionController : NSObject
{
    NSMutableDictionary *_flowSessionDataById;
}

- (void).cxx_destruct;
- (void)destroyFlowSessionWithFlowId:(id)arg1;
- (void)destroyFlowSessionContextWithFlowId:(id)arg1 flowContextIdentifier:(id)arg2;
- (id)flowSessionContextWithFlowId:(id)arg1 flowContextIdentifier:(id)arg2;
- (void)updateFlowSessionWithFlowId:(id)arg1 flowContextIdentifier:(id)arg2 flowSessionContext:(id)arg3;
- (id)newFlowSession;
- (id)init;

@end

