//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MNConversationContact;

@protocol MNPeopleCellDelegate <NSObject>
- (void)inviteButtonTappedForConversationContact:(id <FBConversationContact>)arg1;
- (void)callButtonTappedForConversationContact:(id <FBConversationContact>)arg1 isVideoCall:(BOOL)arg2;
- (void)contextTappedForConversationContact:(MNConversationContact *)arg1;
@end

