//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface MNPhotoEditingTabContainerView : UIView
{
    UIView *_backgroundView;
    UIView *_composeTabBar;
    UIView *_topSeparatorView;
}

- (void).cxx_destruct;
- (void)_layoutSeparatorViews;
- (void)_layoutTabBar;
- (void)_layoutBackgroundView;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)_separatorView;
- (void)_initSeparatorViews;
- (void)_initBackgroundView;
- (id)initWithComposeTabBar:(id)arg1;

@end

