//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString, NSURL;

@interface MNPlatformAppItem : FBValueObject <NSCopying, NSCoding>
{
    BOOL _installed;
    NSString *_appID;
    NSString *_storeID;
    NSString *_name;
    NSString *_shortDescription;
    NSURL *_iconURL;
    NSURL *_bannerURL;
}

@property(readonly, nonatomic) BOOL installed; // @synthesize installed=_installed;
@property(readonly, copy, nonatomic) NSURL *bannerURL; // @synthesize bannerURL=_bannerURL;
@property(readonly, copy, nonatomic) NSURL *iconURL; // @synthesize iconURL=_iconURL;
@property(readonly, copy, nonatomic) NSString *shortDescription; // @synthesize shortDescription=_shortDescription;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *storeID; // @synthesize storeID=_storeID;
@property(readonly, copy, nonatomic) NSString *appID; // @synthesize appID=_appID;
- (void).cxx_destruct;
- (id)initWithAppID:(id)arg1 storeID:(id)arg2 name:(id)arg3 shortDescription:(id)arg4 iconURL:(id)arg5 bannerURL:(id)arg6 installed:(BOOL)arg7;

@end

