//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying.h"

@class NSArray;

@interface MNProfileImageSpec : FBValueObject <NSCopying>
{
    NSArray *_imageUrls;
    int _style;
    int _badgeType;
}

@property(readonly, nonatomic) int badgeType; // @synthesize badgeType=_badgeType;
@property(readonly, nonatomic) int style; // @synthesize style=_style;
@property(readonly, copy, nonatomic) NSArray *imageUrls; // @synthesize imageUrls=_imageUrls;
- (void).cxx_destruct;
- (id)initWithImageUrls:(id)arg1 style:(int)arg2 badgeType:(int)arg3;

@end

