//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MNRegistrationLoadingIndicatorView;

@interface MNRegistrationLoadingIndicatorViewController : UIViewController
{
    MNRegistrationLoadingIndicatorView *_loadingIndicatorView;
}

- (void).cxx_destruct;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;

@end

