//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBExperimentContext.h"

@interface MNUserSetUpFlowExperimentContext : FBExperimentContext
{
    BOOL _requirePushStepPositionExperimentEnabled;
    int _requirePushStepPosition;
}

+ (BOOL)allowUserInterfaceIdiom:(int)arg1;
+ (id)parameterConfigurations;
+ (id)experimentName;
@property(readonly, nonatomic) int requirePushStepPosition; // @synthesize requirePushStepPosition=_requirePushStepPosition;
@property(readonly, nonatomic) BOOL requirePushStepPositionExperimentEnabled; // @synthesize requirePushStepPositionExperimentEnabled=_requirePushStepPositionExperimentEnabled;

@end

