//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@class NSString, NSURL;

@interface NSError (FBLoginErrorStateManager)
@property(copy, nonatomic) NSURL *errorURL;
@property(copy, nonatomic) NSString *otherButtonTitle;
@property(copy, nonatomic) NSString *cancelButtonTitle;
@property(copy, nonatomic) NSString *message;
@property(copy, nonatomic) NSString *title;
@end

