//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "FBModallyPresentableItem.h"

@class NSString, UIView;

@interface UIViewController (FBModalPresentation) <FBModallyPresentableItem>
- (void)_setContainingModalPresentationLayer:(id)arg1;
@property(readonly, nonatomic) id <FBModalPresentationLayer> containingModalPresentationLayer; // @dynamic containingModalPresentationLayer;
@property(readonly, nonatomic) UIViewController *modalPresentationViewController;
@property(readonly, nonatomic) UIView *modalPresentationView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) BOOL occludesScreen;
@property(readonly) Class superclass;
@end

