//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (FBFIGLayout)
@property(readonly, nonatomic) float height;
@property(readonly, nonatomic) float width;
@property(readonly, nonatomic) float bottom;
@property(readonly, nonatomic) float right;
@property(readonly, nonatomic) float top;
@property(readonly, nonatomic) float left;
@end

