//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFEditorFrameContentPackViewController.h"

@interface AFAceFrameContentPackViewController : AFEditorFrameContentPackViewController
{
}

- (void)customizeDetailNavigationItem:(id)arg1 withFrame:(id)arg2;
- (void)animateFrameWidthViewDismissal:(id)arg1 withFramesView:(id)arg2 inContainerView:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)animateFrameWidthViewPresentation:(id)arg1 withFramesView:(id)arg2 inContainerView:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)contentSelectionController:(id)arg1 willVendHeaderView:(id)arg2;
- (void)contentSelectionController:(id)arg1 willVendCollectionViewCell:(id)arg2 withContentPackItem:(id)arg3;
- (void)contentSelectionController:(id)arg1 willVendCollectionViewCell:(id)arg2 withContentPack:(id)arg3;
- (void)contentSelectionController:(id)arg1 willVendCollectionViewCellForShop:(id)arg2;
- (id)initWithRenderInstance:(id)arg1 configuration:(id)arg2;

@end

