//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSLayoutConstraint;

@interface AFAutoTextView : UITextView
{
    NSLayoutConstraint *_descriptionHeightContraint;
}

@property(retain, nonatomic) NSLayoutConstraint *descriptionHeightContraint; // @synthesize descriptionHeightContraint=_descriptionHeightContraint;
- (void).cxx_destruct;
- (void)setBounds:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

