//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFContentDownloadControllerDelegate.h"
#import "AFSupplyShopViewControllerDelegate.h"

@class AFContentDownloadController, AFInterfaceRenderInstance, AFPurchasable, AFSupplyShopDetailViewController, AFSupplyShopViewController, NSString, UINavigationController;

@interface AFContentStoreController : NSObject <AFSupplyShopViewControllerDelegate, AFContentDownloadControllerDelegate>
{
    BOOL _purchasing;
    unsigned int _currentFlowType;
    id <AFContentStoreControllerDelegate> _delegate;
    CDUnknownBlockType _dismissBlock;
    CDUnknownBlockType _purchaseBlock;
    CDUnknownBlockType _restoreBlock;
    CDUnknownBlockType _failBlock;
    CDUnknownBlockType _willPurchaseBlock;
    AFSupplyShopDetailViewController *_detailController;
    UINavigationController *_supplyNavController;
    AFSupplyShopViewController *_supplyShopController;
    AFPurchasable *_purchasingItem;
    AFContentDownloadController *_downloadProgressController;
    AFInterfaceRenderInstance *_renderInstance;
}

@property(retain, nonatomic) AFInterfaceRenderInstance *renderInstance; // @synthesize renderInstance=_renderInstance;
@property(retain, nonatomic) AFContentDownloadController *downloadProgressController; // @synthesize downloadProgressController=_downloadProgressController;
@property(retain, nonatomic) AFPurchasable *purchasingItem; // @synthesize purchasingItem=_purchasingItem;
@property(nonatomic, getter=isPurchasing) BOOL purchasing; // @synthesize purchasing=_purchasing;
@property(retain, nonatomic) AFSupplyShopViewController *supplyShopController; // @synthesize supplyShopController=_supplyShopController;
@property(retain, nonatomic) UINavigationController *supplyNavController; // @synthesize supplyNavController=_supplyNavController;
@property(retain, nonatomic) AFSupplyShopDetailViewController *detailController; // @synthesize detailController=_detailController;
@property(copy, nonatomic) CDUnknownBlockType willPurchaseBlock; // @synthesize willPurchaseBlock=_willPurchaseBlock;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType restoreBlock; // @synthesize restoreBlock=_restoreBlock;
@property(copy, nonatomic) CDUnknownBlockType purchaseBlock; // @synthesize purchaseBlock=_purchaseBlock;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(nonatomic) __weak id <AFContentStoreControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int currentFlowType; // @synthesize currentFlowType=_currentFlowType;
- (void).cxx_destruct;
- (void)dismissCurrentFlowAnimated:(BOOL)arg1;
- (void)downloadController:(id)arg1 contentPackDownloadStateDidChange:(id)arg2 withUpdateType:(int)arg3;
- (void)didFailOrDefer:(id)arg1;
- (void)didRestore:(id)arg1;
- (void)didPurchase:(id)arg1;
- (void)willPurchase:(id)arg1;
- (void)purchaseBundle:(id)arg1;
- (void)downloadContentPack:(id)arg1;
- (void)purchasePurchasable:(id)arg1;
- (void)detailControllerDidFinish:(id)arg1;
- (void)detailControllerInitiatedPurchase:(id)arg1;
- (id)currentRenderInstanceForSupplyShopController:(id)arg1;
- (void)supplyShopControllerRequestsRestore:(id)arg1;
- (void)supplyShopController:(id)arg1 requestsPurchaseForPurchasable:(id)arg2;
- (void)supplyShopControllerDidFinish:(id)arg1;
- (void)dismissSupplyShopFlowAnimated:(BOOL)arg1;
- (void)dismissDetailControllerAnimated:(BOOL)arg1;
- (void)presentDetailFlowForPurchasable:(id)arg1 asChildViewControllerOfViewControler:(id)arg2 animated:(BOOL)arg3;
- (void)presentDetailFlowForPurchasable:(id)arg1 asChildViewControllerOfViewControler:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)presentDetailFlowForPurchasable:(id)arg1 asChildViewControllerOfViewControler:(id)arg2 animated:(BOOL)arg3 context:(unsigned int)arg4 completion:(CDUnknownBlockType)arg5;
- (void)presentSupplyShopWithInitialPurchasableClass:(Class)arg1 asChildOfViewControler:(id)arg2 sourceAnalyticsKey:(id)arg3 animated:(BOOL)arg4;
- (void)presentSupplyShopWithInitialPurchasableClass:(Class)arg1 asChildOfViewControler:(id)arg2 sourceAnalyticsKey:(id)arg3 animated:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
- (void)registerForNotifcations;
- (void)dealloc;
- (id)initWithRenderInstance:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

