//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AFCollectionViewUpdateContextSectionMoveHelper : NSObject
{
    int _fromSection;
    int _toSection;
}

@property(nonatomic) int toSection; // @synthesize toSection=_toSection;
@property(nonatomic) int fromSection; // @synthesize fromSection=_fromSection;

@end

