//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AFSlider, NSString, UIButton, UIColor, UILabel;

@interface AFEditorIntensityView : UIView
{
    AFSlider *_slider;
    UIButton *_applyButton;
    UIButton *_cancelButton;
    UILabel *_label;
}

@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *applyButton; // @synthesize applyButton=_applyButton;
@property(retain, nonatomic) AFSlider *slider; // @synthesize slider=_slider;
- (void).cxx_destruct;
- (void)updateLabelPosition;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) UIColor *labelTextColor;
@property(copy, nonatomic) NSString *labelText;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

