//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "AFDataSourceView.h"
#import "AFInfinitePagingViewDataSource.h"
#import "AFInfinitePagingViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class AFInfinitePagingView, AFSupplyShopFeaturedSectionDataObject, NSString, UIPageControl;

@interface AFSupplyShopFeaturedCell : UICollectionViewCell <AFInfinitePagingViewDelegate, AFInfinitePagingViewDataSource, UIGestureRecognizerDelegate, AFDataSourceView>
{
    BOOL _beenTouched;
    id <AFSupplyShopFeaturedCellDelegate> _delegate;
    AFInfinitePagingView *_pageView;
    AFSupplyShopFeaturedSectionDataObject *_dataObject;
    UIPageControl *_pageControl;
}

@property(nonatomic) BOOL beenTouched; // @synthesize beenTouched=_beenTouched;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) AFSupplyShopFeaturedSectionDataObject *dataObject; // @synthesize dataObject=_dataObject;
@property(retain, nonatomic) AFInfinitePagingView *pageView; // @synthesize pageView=_pageView;
@property(nonatomic) __weak id <AFSupplyShopFeaturedCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)infinitePagingViewInteractionBegan:(id)arg1;
- (void)infinitePagingView:(id)arg1 didPageToItemAtIndex:(unsigned int)arg2;
- (id)infinitePagingView:(id)arg1 itemAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfItemsInInfinitePagingView:(id)arg1;
- (void)cancelPaging;
- (void)pageFeaturedItems;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)longPressRecognized:(id)arg1;
- (void)tapRecognized:(id)arg1;
- (void)updateCells;
- (void)layoutSubviews;
- (void)preparePagingView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

