//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "AFDataSourceView.h"
#import "AFPurchasableCellUpdating.h"

@class AFPurchasable, NSString, UIButton, UIImageView, UILabel;

@interface AFSupplyShopPurchasableCell : UICollectionViewCell <AFDataSourceView, AFPurchasableCellUpdating>
{
    AFPurchasable *_dataObject;
    UIImageView *_packThumbnailView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_purchaseButton;
    id <AFSupplyShopPurchasableCellDelegate> _delegate;
}

@property(nonatomic) __weak id <AFSupplyShopPurchasableCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *packThumbnailView; // @synthesize packThumbnailView=_packThumbnailView;
@property(retain, nonatomic) AFPurchasable *dataObject; // @synthesize dataObject=_dataObject;
- (void).cxx_destruct;
- (id)purchaseImagePressed;
- (id)purchaseImage;
- (void)configurePurchaseButton;
- (void)reloadView;
- (void)configureCellForPurchasableState;
- (void)configureLabel;
- (void)configureIconImage;
- (void)purchaseButtonPressed:(id)arg1;
- (void)layoutSubviews;
- (void)prepareView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

