//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CityGroupList : NSObject
{
    NSString *_cityId;
    NSString *_cityName;
    NSMutableArray *_restaurantList;
}

@property(retain, nonatomic) NSMutableArray *restaurantList; // @synthesize restaurantList=_restaurantList;
@property(copy, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(copy, nonatomic) NSString *cityId; // @synthesize cityId=_cityId;
- (void).cxx_destruct;

@end

