//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "UITextFieldDelegate.h"

@class FMStepperButton, NSNumber, NSString, UIColor, UIFont, UITextField;

@interface FMStepper : UIControl <UITextFieldDelegate>
{
    int longTouchAccelDelay;
    BOOL _continuous;
    BOOL _wraps;
    BOOL _autorepeat;
    UIColor *_tintColor;
    FMStepperButton *_decreaseStepperButton;
    UITextField *_valueTextField;
    FMStepperButton *_increaseStepperButton;
    NSNumber *_currentValue;
    UIFont *_textFont;
    NSNumber *_valueDuringAction;
    double _minimumValue;
    double _maximumValue;
    double _stepValue;
    double _autorepeatInterval;
}

+ (id)stepperWithFrame:(struct CGRect)arg1 min:(float)arg2 max:(float)arg3 step:(float)arg4 value:(float)arg5;
@property(retain, nonatomic) NSNumber *valueDuringAction; // @synthesize valueDuringAction=_valueDuringAction;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(retain, nonatomic) NSNumber *currentValue; // @synthesize currentValue=_currentValue;
@property(retain, nonatomic) FMStepperButton *increaseStepperButton; // @synthesize increaseStepperButton=_increaseStepperButton;
@property(retain, nonatomic) UITextField *valueTextField; // @synthesize valueTextField=_valueTextField;
@property(retain, nonatomic) FMStepperButton *decreaseStepperButton; // @synthesize decreaseStepperButton=_decreaseStepperButton;
@property(nonatomic) double autorepeatInterval; // @synthesize autorepeatInterval=_autorepeatInterval;
@property(nonatomic) BOOL autorepeat; // @synthesize autorepeat=_autorepeat;
@property(nonatomic) BOOL wraps; // @synthesize wraps=_wraps;
@property(nonatomic, getter=isContinuous) BOOL continuous; // @synthesize continuous=_continuous;
@property(nonatomic) double stepValue; // @synthesize stepValue=_stepValue;
@property(nonatomic) double maximumValue; // @synthesize maximumValue=_maximumValue;
@property(nonatomic) double minimumValue; // @synthesize minimumValue=_minimumValue;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
- (void).cxx_destruct;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)incrementValue:(id)arg1;
- (void)longTouchInProgress;
- (void)longTouchDidEnd;
- (void)longTouchDidBegin:(id)arg1;
- (void)buttonPressed:(id)arg1;
- (BOOL)resignFirstResponder;
- (void)setCornerRadius:(float)arg1;
- (void)setFont:(id)arg1 size:(float)arg2;
- (void)setValue:(double)arg1;
- (double)value;
- (id)valueObject;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

