//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class UIButton, UIImageView, UITextField;

@interface LoginWithEmailViewController : BaseViewController
{
    BOOL _closeScreenWithoutPresentIntroduction;
    UITextField *_txtEmail;
    UITextField *_txtPassword;
    UIButton *_btnLogin;
    UIButton *_btnForgotPass;
    UIButton *_btnRegister;
    UIImageView *_background;
}

@property(nonatomic) __weak UIImageView *background; // @synthesize background=_background;
@property(retain, nonatomic) UIButton *btnRegister; // @synthesize btnRegister=_btnRegister;
@property(nonatomic) __weak UIButton *btnForgotPass; // @synthesize btnForgotPass=_btnForgotPass;
@property(nonatomic) __weak UIButton *btnLogin; // @synthesize btnLogin=_btnLogin;
@property(nonatomic) __weak UITextField *txtPassword; // @synthesize txtPassword=_txtPassword;
@property(nonatomic) __weak UITextField *txtEmail; // @synthesize txtEmail=_txtEmail;
@property(nonatomic) BOOL closeScreenWithoutPresentIntroduction; // @synthesize closeScreenWithoutPresentIntroduction=_closeScreenWithoutPresentIntroduction;
- (void).cxx_destruct;
- (void)didReceivedUserLoginEvent:(id)arg1;
- (void)stopSpinner;
- (void)startSpinner;
- (void)doLoginWithEmailAndPassword:(id)arg1;
- (void)dismissControl;
- (void)hideKeyboard:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDone:(id)arg1;
- (void)doSwitchRegisterScreen:(id)arg1;
- (void)doForgotPass:(id)arg1;
- (void)doLogin:(id)arg1;
- (void)viewDidUnload;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)trackPageView;
- (void)backToLoginScreen:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

