//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface PagingRequestInfo : NSObject <NSCopying>
{
    BOOL _hasmoreData;
    NSString *_nextItemId;
    int _totalCount;
}

@property(nonatomic) int totalCount; // @synthesize totalCount=_totalCount;
@property(nonatomic) BOOL hasmoreData; // @synthesize hasmoreData=_hasmoreData;
@property(copy, nonatomic) NSString *nextItemId; // @synthesize nextItemId=_nextItemId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

