//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RDVTabBarDelegate.h"

@class NSArray, NSString, RDVTabBar, UIView;

@interface RDVTabBarController : UIViewController <RDVTabBarDelegate>
{
    UIView *_contentView;
    BOOL isHiding;
    BOOL _tabBarHidden;
    id <RDVTabBarControllerDelegate> _delegate;
    NSArray *_viewControllers;
    RDVTabBar *_tabBar;
    UIViewController *_selectedViewController;
    unsigned int _selectedIndex;
}

@property(nonatomic, getter=isTabBarHidden) BOOL tabBarHidden; // @synthesize tabBarHidden=_tabBarHidden;
@property(nonatomic) unsigned int selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) __weak UIViewController *selectedViewController; // @synthesize selectedViewController=_selectedViewController;
@property(retain, nonatomic) RDVTabBar *tabBar; // @synthesize tabBar=_tabBar;
@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(nonatomic) __weak id <RDVTabBarControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tabBar:(id)arg1 didSelectItemAtIndex:(int)arg2;
- (BOOL)tabBar:(id)arg1 shouldSelectItemAtIndex:(int)arg2;
- (void)setTabBarHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (id)contentView;
- (int)indexForViewController:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (int)preferredStatusBarUpdateAnimation;
- (int)preferredStatusBarStyle;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

