//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UIImageView, UIScrollView, UITextField;

@interface RegisterViewController : BaseViewController <UITextFieldDelegate>
{
    BOOL _closeScreenWithoutPresentIntroduction;
    UITextField *_txtEmail;
    UITextField *_txtPass;
    UITextField *_txtRePass;
    UITextField *_txtDisplayName;
    UIImageView *_backgroundImage;
    UIScrollView *_scrollView;
    UIButton *_btnLogin;
    UIButton *_btnRegister;
}

@property(nonatomic) __weak UIButton *btnRegister; // @synthesize btnRegister=_btnRegister;
@property(retain, nonatomic) UIButton *btnLogin; // @synthesize btnLogin=_btnLogin;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIImageView *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(nonatomic) __weak UITextField *txtDisplayName; // @synthesize txtDisplayName=_txtDisplayName;
@property(nonatomic) __weak UITextField *txtRePass; // @synthesize txtRePass=_txtRePass;
@property(nonatomic) __weak UITextField *txtPass; // @synthesize txtPass=_txtPass;
@property(nonatomic) __weak UITextField *txtEmail; // @synthesize txtEmail=_txtEmail;
@property(nonatomic) BOOL closeScreenWithoutPresentIntroduction; // @synthesize closeScreenWithoutPresentIntroduction=_closeScreenWithoutPresentIntroduction;
- (void).cxx_destruct;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)didReceivedUserLoginEvent:(id)arg1;
- (void)stopSpinner;
- (void)startSpinner;
- (void)doRegisterUser;
- (void)dismissControl;
- (void)doSwitchLoginView:(id)arg1;
- (void)doRegister:(id)arg1;
- (void)setPlaceholderColor;
- (void)textFieldDone:(id)arg1;
- (void)hideKeyboard:(id)arg1;
- (void)viewDidUnload;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)trackPageView;
- (void)backToIntroScreen:(id)arg1;
- (void)closeScreen:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

