//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UITextField;

@interface RTAlertViewDoubleTextFieldView : UIView
{
    UITextField *_textField0;
    UITextField *_textField1;
}

@property(nonatomic) __weak UITextField *textField1; // @synthesize textField1=_textField1;
@property(nonatomic) __weak UITextField *textField0; // @synthesize textField0=_textField0;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (id)initWithFrame:(struct CGRect)arg1;

@end

