//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSArray, UITableView;

@interface SubmittedPromotionViewController : BaseViewController
{
    NSArray *resultList;
    id <ListLoaderProtocol> dataListLoader;
    UITableView *_contentTbv;
}

@property(nonatomic) __weak UITableView *contentTbv; // @synthesize contentTbv=_contentTbv;
@property(retain, nonatomic) id <ListLoaderProtocol> dataListLoader; // @synthesize dataListLoader;
@property(retain, nonatomic) NSArray *resultList; // @synthesize resultList;
- (void).cxx_destruct;
- (void)loadDataForScreen:(BOOL)arg1;
- (void)loadMoreDataForScreen;
- (void)loadMoreContentForTableView;
- (void)refreshContentForTableView;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)promotionCellForIndexPath:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)objectImageDownloadDidPartialFinish;
- (void)removeTableViewEmptyMessage;
- (void)setTableViewEmptyMessage;
- (void)initializeUIControls:(BOOL)arg1;
- (void)trackPageView;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

