//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel;

@interface SuggestResCell : UITableViewCell
{
    UILabel *resNameLabel;
    UILabel *cityLabel;
    UIButton *closeButton;
}

@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton;
@property(retain, nonatomic) UILabel *cityLabel; // @synthesize cityLabel;
@property(retain, nonatomic) UILabel *resNameLabel; // @synthesize resNameLabel;
- (void).cxx_destruct;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSuggestResName:(id)arg1;
- (void)setSuggestCity:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

