//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TAGAddRemoveSetPopulator.h"

@class NSDictionary;

@interface TAGAddRemoveMacrosPopulator : NSObject <TAGAddRemoveSetPopulator>
{
    NSDictionary *_addMacros;
    NSDictionary *_removeMacros;
}

@property(retain, nonatomic) NSDictionary *removeMacros; // @synthesize removeMacros=_removeMacros;
@property(retain, nonatomic) NSDictionary *addMacros; // @synthesize addMacros=_addMacros;
- (void).cxx_destruct;
- (void)rulePassed:(id)arg1 add:(id)arg2 remove:(id)arg3;
- (id)initWithAddMacros:(id)arg1 removeMacros:(id)arg2;

@end

