//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSFastEnumeration.h"
#import "NSMutableCopying.h"

@class NSMutableDictionary;

@interface TAGPBUnknownFieldSet : NSObject <NSFastEnumeration, NSCopying, NSMutableCopying>
{
    NSMutableDictionary *fields_;
}

+ (BOOL)isFieldTag:(int)arg1;
- (id)sortedFields;
- (void)mergeFromCodedInputStream:(id)arg1;
- (BOOL)mergeFieldFrom:(int)arg1 input:(id)arg2;
- (void)mergeVarintField:(int)arg1 value:(int)arg2;
- (void)mergeFromData:(id)arg1;
- (void)mergeUnknownFields:(id)arg1;
- (void)mergeField:(id)arg1;
- (id)getFieldBuilder:(int)arg1 create:(BOOL)arg2;
- (void)addField:(id)arg1;
- (id)data;
- (unsigned long)serializedSizeAsMessageSet;
- (void)writeAsMessageSetTo:(id)arg1;
- (unsigned long)serializedSize;
- (id)description;
- (void)writeToCodedOutputStream:(id)arg1;
- (unsigned int)countOfFields;
- (id)getField:(int)arg1;
- (BOOL)hasField:(int)arg1;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFields:(id)arg1;

@end

