//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface WorkEducation : NSObject <NSCopying>
{
    NSString *_studyAt;
    NSString *_company;
    NSString *_career;
}

@property(copy, nonatomic) NSString *career; // @synthesize career=_career;
@property(copy, nonatomic) NSString *company; // @synthesize company=_company;
@property(copy, nonatomic) NSString *studyAt; // @synthesize studyAt=_studyAt;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

